Makefile
build.sh
cmd/clean.go
cmd/init.go
cmd/join.go
cmd/version.go
install/check.go
install/clean.go
install/config.go
install/generator.go
install/init.go
install/join.go
install/sealos.go
install/utils.go
install/vars.go
version/version.go

fix #183
init/join 命令新增了masters/nodes参数，格式为`ip-ip`
```
sealos init --passwd vagrant --podcidr 172.16.0.0/16 --repo registry.cn-hangzhou.aliyuncs.com/google_containers --version 1.17.0 --pkg-url /root/kube1.17.0.tar.gz \
--masters 192.168.100.101-192.168.100.101 \
--nodes 192.168.100.102-192.168.100.102 \
--node 192.168.100.103
```

feat: 支持ip段

---

install/generator.go

- k8s 服务启动挂载`/etc/localtime`
- 新增了自动清理Job特性`TTLAfterFinished `
原因：
利用Job跑CI，大量pod/job完成后成功于否都未被清理
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1

kubeadm 集群配置优化

---

pkg/sshcmd/sshutil/scp.go

Fixes #374 缺陷: ssh中使用3des-cbc加密方式，导致文件无法scp

缺陷: ssh中使用3des-cbc加密方式，导致文件无法scp

---

Makefile
build-in-docker-and-put-oss.sh
build.sh
version/version.go

./sealos version
sealos version v3.3.8, build 9c94143 go1.14.3, UTC Build Time : 2020-06-29 08:31:25 UTC

add build timestamp to sealos version

---

cmd/init.go
install/generator.go
install/init.go
install/vars.go

1. 在kubeadm的默认的模板文件,添加certsans信息
2. 如果默认模板解析失效的时候, 用户增加了certs-san, 则需要添加默认的certs-sans

#377 add --cert-sans参数, 快速把指定ip或者域名放入apiserver证书使用.

---

cmd/install.go
install/utils.go

sealos init 有pkgurl判断．　
sealos install 同理应该是一样的判断．　都可以从远程安装．　所以判断是一样的
这里我没有考虑到install命令的一些插件的大小，　
比如kuboard.tar只有57Ｍ，　所以前面写的`resp.ContentLength < MinDownloadFileSize` 这个判断可能还不合适．　
＠cuisongliu  有什么好方法么．．

sealos install --pkg-url ，pkg-url文件位置不对，则立即退出安装　

---

cmd/init.go
install/check.go
install/config.go
install/utils_test.go
pkg/sshcmd/sshutil/connect.go
pkg/sshcmd/sshutil/scp.go
pkg/sshcmd/sshutil/ssh.go
pkg/sshcmd/sshutil/types.go
version/version.go

0. 默认pk文件是`/root/.ssh/id_rsa`. 
1. 验证先判断 pk 文件 , 如果能够获取`ssh.AuthMethod` , 则添加 至 auth. 
2. 验证 password. 如果 password不为空, 则添加  `ssh.AuthMethod` 至auth.
1,2 验证都获取到了 `ssh.AuthMethod` 进入验证阶段, 这部分逻辑没变. 
ps: 
判断pk文件的时候, 如果pk文件有密码, 则需添加 `--pk-passwd`命令行参数. 默认为空. 
如果用户只想用密码验证.  但是`/root/.ssh/id_rsa` 这个文件不存在, 则直接返回auth.

默认pk先认证。 #395 ssh 验证优化。

---

install/config.go

load config时, 未考虑pk-passwod.  #395

ssh 验证优化.修复load未考虑pk-password

---

cmd/install.go
install/install.go
install/utils.go

sealos  install -f  时。 增加stdin读取。  #399 
功能为：   当读取stdin时， 在`workdir`生成 `values.yaml `。 然后复制到各节点。 
当读取文件时， 直接复制到个节点。
当不带参数 -f 时。 默认使用 `tar`包里面的默认` values.yaml `。
tips： 
感觉需要在 `CONFIG `文件在添加一句 `APPLY kubectl apply -f  values.yaml` . 不然用户还得定义这一行。

#399  install -f - support stdin

---

install/init.go

If `sealos init` fails and runs multiple times, there will be duplicate entries in /etc/hosts .

Only append to /etc/hosts if entry not exists

---

cmd/etcd.go
install/etcd_restore.go
install/etcd_save.go
install/init.go

fix ETCD CaCert or key file is not exist occurs panic. @cuisongliu 
```
$ ./sealos etcd health
17:53:53 [EROR] [etcd_save.go:211] open /root/.sealos/pki/etcd/healthcheck-client.crt: permission denied
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x166141e]
goroutine 127 [running]:
github.com/fanux/sealos/install.(*EtcdFlags).HealthCheck.func1(0xc0002c3e00, 0xc0003d8240, 0x0)
/home/louis/go/src/github.com/oldthreefeng/sealos/install/etcd_save.go:221 +0x6e
created by github.com/fanux/sealos/install.(*EtcdFlags).HealthCheck
/home/louis/go/src/github.com/oldthreefeng/sealos/install/etcd_save.go:219 +0x23c
```

fix ETCD CaCert or key file is not exist occurs panic

---

cmd/etcd.go
docs/etcdbackup.md
pkg/appmanager/deleteapp.go
test/cronjob.yaml.example

添加`sealos etcd`相关的使用说明. 以及修复错别字.

add kubernetes cronjob example yaml file

---

cmd/exec.go
install/exec.go
k8s/node.go
k8s/utlis.go
k8s/utlis_test.go
pkg/sshcmd/sshutil/scp_test.go

这版支持了 `--node hostname` .  k8s 里面操作`node`对象感觉有点生疏.  ~~从里面获取资源用了`n个for`循环~~  
@fanux  ~~对`k8s里面node`对象的操作有好的推荐么?  如果nodes节点过多, 感觉这个算法就不行了.~~
实现如下: 
使用Get方法, 通过`nodename`直接找到定位到node节点.
```
node, err := k8sClient.CoreV1().Nodes().Get(context.TODO(), nodeName, metav1.GetOptions{})
```
使用ListOptions, 通过`labelSelector`直接定位到nodeList节点
```
func GetNodeListByLabel(k8sClient *kubernetes.Clientset, label string) (*v1.NodeList, error) {
listOption := &metav1.ListOptions{LabelSelector: label}
return k8sClient.CoreV1().Nodes().List(context.TODO(), *listOption)
}
```
避免使用for循环来找. 效率太低且难看
主要改版点是 , 将 `--label , --node hostname` 所关联的对象全部转为ip, 以ip为基点去执行. 避免了各种判断
在转换过程中, 必不可少会导致去重和删除不必要的信息. 
以下是测试过程的信息. 
<details><summary><code>1. Use --label to exec cmd </code> …

refactor exec andadd test 

---

cmd/etcd.go
install/etcd_save.go
install/join.go

fix sealos etcd health check for mutil master.
```
[root@K8s-DEV-master ~]# ./sealos etcd health
19:10:48 [INFO] [etcd_save.go:259] health check for etcd: [{192.168.160.243:2379 true 6.002112ms }]
[root@K8s-DEV-master ~]# ./sealos etcd health
19:16:41 [INFO] [etcd_save.go:280] health check for etcd: [{192.168.160.243:2379 true 9.874935ms } {192.168.160.244:2379 true 11.982802ms }]
```

fix sealos etcd health check for mutil master

---

cmd/completion.go

sealos 目前的子命令过多， 需要命令行补全功能了。 完全参考`kubectl`。
bash
```
source <(sealos completion bash)
```
zsh
```
source <(sealos completion zsh)
```

add bash/zsh completion for sealos.

---

cmd/route.go
docs/route.md
go.mod
go.sum
install/check.go
install/clean.go
install/generator.go
install/generator_test.go
install/init.go
install/join.go
install/route.go
install/sealos.go
install/send.go
install/vars.go

add sealos route cmd docs
use github.com/vishvananda/netlink to set default route gateway instead
of `ip route del default && ip route add default via 192.168.0.1`
when use mulit Iface to check default route first.
use `sealos init --gateway` to set default gateway on master .

add sealos route cmd docs

---

pkg/sshcmd/sshutil/ssh.go

修复readPipe的两个bug：
1. 第一个bug是bufio.NewReader需要在for循环之前，否则只会输出一行日志
2. 第二个bug是函数返回值为session.Wait()，否则session.Start()不会返回执行命令的错误码，即命令即使出错也不会报错

fix bugs in readPipe function

---

install/download.go
pkg/sshcmd/sshutil/scp.go

fix #491 . 复制过程 如果文件存在和`PkgUrl`路径下的进行MD5比对, 
比对不一样, 就删除远程的主机文件(是退出安装还是删除文件靠谱点..), 
不存在复制,沿用逻辑.. 
日志
```
$ sealos  init --master 192.168.1.21 --pkg-url kube1.18.8.tar.gz  --version v1.18.8
14:25:11 [INFO] [ssh.go:13] [ssh][192.168.1.21:22] hostname
14:25:11 [DEBG] [ssh.go:25] [ssh][192.168.1.21:22]command result is: k8s-dev
14:25:11 [INFO] [ssh.go:58] [ssh][192.168.1.21:22] cat /etc/hosts |grep k8s-dev || echo '192.168.1.21 k8s-dev' >> /etc/hosts
14:25:11 [INFO] [ssh.go:51] [192.168.1.21:22] 192.168.1.21 k8s-dev
14:25:11 [INFO] [check.go:52] [192.168.1.21:22]  ------------ check ok
14:25:11 [INFO] [print.go:13] 
[globals]sealos config is:  {"Hosts":["192.168.1.21:22"],"Masters":["192.168.1.21:22"],"Nodes":null}
14:25:11 [INFO] [ssh.go:58] …
```

validate copy kubetarball

---

cmd/init.go
install/config.go

add sealos init gen  subcommand to get default config
fix init with --config 

add sealos init gen  subcommand to get default config

---

Dockerfile

alpine 作为 base 测试 ok 
保持alpine apk 源的干净
第三层使用干净 alpine 作为 base
最后的镜像大小为18MB，较原镜像多出的6MB
```bash
docker image ls|grep sealos
sealos                                develop             a4942be0834e        1 hours ago         18MB
```

Support docker deploy

---

install/init.go
install/join.go

[SKIP CI]seaols: 解决helm执行的警告，如下：
root@master1:~# helm list
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/.kube/config
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION

/root/.kube/config设置为600，否则默认其它组有r权限，导致helm工具执行有警告

---

cmd/root.go
go.sum
install/utils.go
pkg/logger/config.go
pkg/sshcmd/sshutil/scp.go
pkg/sshcmd/sshutil/ssh.go

sealos change cri to containerd when Version greater than 1.20
fix init cobra value, use --info to show info logs. default is DEBUG

sealos change cri to containerd when Version greater than 1.20

---

cmd/clean.go

测试通过..
```
[root@k8s-dev ~]# kubectl get nodes -owide
NAME        STATUS   ROLES    AGE   VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION           CONTAINER-RUNTIME
k8s-dev     Ready    master   57m   v1.19.4   192.168.60.136   <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   docker://19.3.12
k8s-node1   Ready    <none>   56m   v1.19.4   192.168.60.138   <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   docker://19.3.12
[root@k8s-dev ~]# ./sealos  clean --node 192.168.60.136
00:43:50 [EROR] [clean.go:99] clean master Use "sealos clean --master 192.168.60.136:22" to clean it, exit...
[root@k8s-dev ~]# ./sealos  clean --master 192.168.60.138
00:43:56 [EROR] [clean.go:104] clean nodes Use "sealos clean …
```

clean master use --master ; clean node use --node, if not ;exit

---

install/init.go
install/send.go
install/upgrade.go
install/upgrade_pool.go
install/utils_test.go
k8s/drain.go

升级最多并发升级两个节点. 
```
01:02:37 [INFO] [upgrade.go:77] UpgradeMaster0
01:02:37 [INFO] [upgrade.go:106] first: to drain master node k8s-dev
01:02:37 [DEBG] [ssh.go:58] [192.168.60.136:22] kubectl drain k8s-dev --ignore-daemonsets --delete-local-data
01:02:38 [INFO] [ssh.go:51] [192.168.60.136:22] node/k8s-dev already cordoned
01:02:38 [INFO] [ssh.go:51] [192.168.60.136:22] WARNING: ignoring DaemonSet-managed Pods: kube-system/calico-node-hrgfv, kube-system/kube-proxy-bpqfs, kube-system/upgrade-prepull-kube-apiserver-cc7hc, kube-system/upgrade-prepull-kube-controller-manager-pbp99, kube-system/upgrade-prepull-kube-scheduler-vmzcn
01:02:38 [INFO] [ssh.go:51] [192.168.60.136:22] node/k8s-dev drained
01:02:38 …
```

use channel to manage goroutine when upgrade nodes

---

README.md
README_en.md
README_zh.md
install/init.go
net/flannel.go

Requirements and Recommendations for #591

---

README.md
README_en.md
README_zh.md
install/constants.go
install/generator.go
install/generator_test.go
install/init.go
install/join.go
install/vars.go

本次 PR的主要内容： 
- 使用`kubeadm init/join` 前，判断当前主机cgroupdriver 并在kubeadm-config.yaml 写入cgroupdriver.  
PR的优势: 
- 可以兼容节点不同的cgroupdriver . 比如 有 1/2/3三台机器 ,  1的`cgroup Driver `为 systemd, 2/3 为 cgroupfs.    当然这个不推荐.
- 可以减少一些因为cgroup不一致, 导致的安装报错问题. 增加安装的丝滑.
- 使用阿里云的kubelet的config.yaml(目前使用默认配置)配置.  减少默认配置造成的一些不必要的问题.
需要测试`sealos init / join `

[need to test] staging for cgroupdriver , fix #582

---

install/check.go
install/clean.go
install/constants.go
install/etcd_save.go
install/generator.go
install/generator_test.go
install/init.go
install/join.go
install/upgrade.go
install/utils.go
install/vars.go

kubeadm 的 v1beta3 1.22 开始启动. 1.23 部分 api 开始切换, 因此 sealos 从 1.23 开始使用v1beta3.
需要测试一下: 
1.18.x/1.21.x/1.23.x
此 pr 需要等 1.23.0 发布前一天合并.  v1beta3 功能完全 ok 即可合入. 
also fix #672 
and more kubeadm api `Implementation History` can be found in https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/kubeadm/970-kubeadm-config

[WIP]Sealos kubeadm 1.23 v1beta3

---

.goreleaser.yml
Makefile

[SKIP CI]seaols:  修改为静态编译，移除cgo开启后依赖 libgpgme.so的要求

fix cross build arm ,using statically build

---

cmd/sealctl/cmd/registry.go
cmd/sealos/cmd/build.go
pkg/image/binary/image.go
pkg/image/buildah/image/build.go
pkg/image/types/types.go
pkg/registry/interface.go
pkg/registry/save.go
pkg/registry/save_test.go

Fix #994 
Affected commands: `sealos build`, `seactl registry pull`. Add a flag `--max-pull-procs` for both.

feat: customize maximum goroutines for pulling

---

pkg/image/types/types.go

[SKIP CI]seaols: Remove `--max-pull-procs` flag in `BuildOptions.String()`

fix: remove max-pull-procs flag in BuildOptions.String()

---

cmd/sealos/cmd/add.go
cmd/sealos/cmd/delete.go

sealos delete can not only delect cluster ,but also delete a single node,while sealos add is supported to add new one.

modify help

---

cmd/sealctl/cmd/registry.go
cmd/sealos/cmd/build.go
pkg/image/binary/image.go
pkg/image/buildah/image/build.go
pkg/image/types/types.go
pkg/registry/distributionpkg/client/auth/api_version.go
pkg/registry/distributionpkg/client/auth/challenge/addr.go
pkg/registry/distributionpkg/client/auth/challenge/authchallenge.go
pkg/registry/distributionpkg/client/auth/session.go
pkg/registry/distributionpkg/client/blob_writer.go
pkg/registry/distributionpkg/client/errors.go
pkg/registry/distributionpkg/client/repository.go
pkg/registry/distributionpkg/client/transport/http_reader.go
pkg/registry/distributionpkg/client/transport/transport.go
pkg/registry/distributionpkg/proxy/proxyauth.go
pkg/registry/distributionpkg/proxy/proxyblobstore.go
pkg/registry/distributionpkg/proxy/proxymanifeststore.go
pkg/registry/distributionpkg/proxy/proxyregistry.go
pkg/registry/interface.go
pkg/registry/save.go
pkg/registry/save_test.go

1. default only support token auth , add basic auth to cache registry
2. proxyauth.go (func configureAuth) if basicAuth and getAuthURLs is empty append remoteURL to default authURLs
3. proxyregistry.go (func Repository) default use tokenAuth ,if  basicAuth is true  use basicAuthHandler.
4. session.go (func AuthorizeRequest) bh.creds.Basic use remoteURL  to fetch authURLs  username password

feature(main): support cache http registry #1022

---

pkg/runtime/kubeadm.go
pkg/utils/iputils/iputils_v2.go

[SKIP CI]sealos: validate virtual IP for masters
virtual IP address of masters MUST NOT in podSubnet and serviceSubnet range, otherwise, when the same IP address is allocated in cluster, unexpected network connectivity from components to APIServer may failed.
or, even we can make the constant `DefaultVIP` configurable?

fix: validate vip before initialization

---

Makefile
amd64.yaml
arm64.yaml

[SKIP CI]seaols: Add rpm & deb build script for sealos with nfpm
```bash
brew install nfpm
```
```bash
make build
make package
```
```bash
$ md5sum bin/linux_amd64/*
MD5 (bin/linux_amd64/seactl) = 108e8a42b748c0e9be3ba941656a00c5
MD5 (bin/linux_amd64/sealos) = 9521d81960d1905b6f1d12595b9731be
MD5 (bin/linux_amd64/sealos-4.0.0.x86_64.rpm) = 24b06f6d44ac5e3c6099f048cc2a037f
MD5 (bin/linux_amd64/sealos_4.0.0_amd64.deb) = 92143841ab8af926b11bda454e55ad49
$ md5sum bin/linux_arm64/*
MD5 (bin/linux_arm64/seactl) = 002894239bcc7fd507444a30bed47720
MD5 (bin/linux_arm64/sealos) = f6ae4d21075c3aa475545295890ce860
MD5 (bin/linux_arm64/sealos-4.0.0.aarch64.rpm) = fa40dce776dd4107b13568f07c030f7e
MD5 (bin/linux_arm64/sealos_4.0.0_arm64.deb) = 15078e4b70ffcac44d5b1cd5430e2552
```

Add rpm & deb build script with nfpm

---

CONTRIBUTING.md

When compiling sealos in go under 1.16, the following error will raise
> build command-line-arguments: cannot load io/fs: malformed module path "io/fs": missing dot in first path element

docs: update go version

---

pkg/image/buildah/image/build.go

sealos default build file is  kubefile , the same as binary method build, and can specified by cli args.
fix: https://github.com/labring/sealos/issues/1150

fix: can't specify dockerfile 

---

scripts/make-rules/golang.mk

Now sealos will be built with `CGO_ENABLED=0` too, which makes cross-platform building possible.

fix: merge go.build.%.sealctl/sealos

---

DEVELOPGUIDE.md
scripts/make-rules/golang.mk

Signed-off-by: maybaby <ybyang7@iflytek.com>
[SKIP CI]sealos:  no longer explicitly specify cgo_enabled . and i think we should close the https://github.com/labring/sealos/pull/1244.

fix: no longer explicitly specify cgo_enabled

---

.clabot
.github/workflows/ci.yml
.goreleaser.yml
scripts/make-rules/common.mk
scripts/make-rules/golang.mk

ci: Update ci.yml to use simpler make build to build testing binaries

---

.github/workflows/ci.yml
scripts/make-rules/golang.mk

Now sealos will be built with `CGO_ENABLED=1` (even in Makefile) to unleash its full power.

ci: enable CGO

---

staging/src/github.com/labring/lvscare/care/care.go
staging/src/github.com/labring/lvscare/care/utils.go
staging/src/github.com/labring/lvscare/care/vars.go
staging/src/github.com/labring/lvscare/pkg/utils/netlink.go

automatic create a dummy network interface and bind virtual IP to it when any of real server is listening locally(by automatic dectection), setting this parameter to null will skip this behaviour.

feat: auto create dummy link if needed

---

service/auth/deploy/manifests/casdoor.yaml

Signed-off-by: abingcbc <abingcbc626@gmail.com>
The default reclaim policy of storage class created by Openebs is `Delete`. 
https://github.com/labring/cluster-image/blob/46dfc576d274e7422e35852a1938c8a13f8a44cb/applications/openebs/v1.9.0/manifests/host-path-sc.yaml#L14
So I add a new storage class for MySQL whose reclaim policy is `Retain` to protect users' data.

fix(auth): retain mysql pv when delete pvc

---

pkg/auth/sso/casdoor.go
pkg/auth/sso/client.go
pkg/auth/utils/config.go

Fix:
1. Each time restarting service-auth, load the existing Casdoor init data instead of creating a new one.
2. Redirect URL to Casdoor (ssoEndpoint in config.yaml)
3. Wrap all errors with `errors.Wrap`
4. Parsing OAuth token error. 
The root cause is that Casdoor raised a breaking change. In PR https://github.com/casdoor/casdoor/pull/894, `PublicKey` is renamed to `Certificate`. Therefore, the jwt publickey we created is ignored by Casdoor.

fix(auth): connect to casdoor

---

pkg/auth/conf/config.go
pkg/auth/utils/config.go
service/auth/deploy/manifests/auth.yaml

Get CA Cert from kubeconfig instead of :
1. From `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` for in cluster mode
2. From config.CaCert for out of cluster mode

fix(auth): get ca cert from kubeconfig

---

cloud/deploy/manifests/ingress-nginx-with-cert.yaml
pkg/auth/conf/casdoor.yaml
service/auth/Dockerfile

1. Ingress for Casdoor
2. Fix HTTPS certificate of Golang OAuth client in the docker image. A same problem: https://github.com/casdoor/casdoor/pull/491
FYI: Image size becomes 32MB to 44MB after using `alphine` as the base image instead of `scratch`.

feat(auth): deploy for service auth

---

staging/src/github.com/labring/lvscare/README.md
staging/src/github.com/labring/lvscare/care/iptables.go

1. ruler will create a goroutine to ensure iptables rules every 1 minute incase some external program flush iptables rules;
2. cilium CNI will create rules in `filter` table, non-matched marked packets will be dropped, so lvscare must ACCEPT those packets at the very first chain.

fix: incompatible with cilium

---

pkg/buildimage/chart.go

fix chart‘s dependencies rendering are not affected by `dependencies[].condition` and `dependencies[].alias`

fix: chart deps rendering

---

pkg/apply/processor/create.go
pkg/apply/processor/install.go
pkg/apply/processor/scale.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/test_clusterfile.yaml
pkg/types/v1beta1/config.go

Merge config into file in specified application image. defaults is overwriting all configs into all images(works but not necessary), when `Config.spec.strategy` is `merge`, modified files will be overwritten with null values again in later for-loop processing.

fix: unexpected config merge

---

pkg/constants/bash.go
pkg/runtime/defaults/default_kubeadm_config.go
pkg/runtime/defaults/v125/default_kubeadm_config.go
pkg/runtime/kubeadm.go
pkg/runtime/kubeadm_config.go
pkg/runtime/registry.go
pkg/runtime/utils.go

feature(main): add v1.25 k8s support

---

pkg/buildimage/chart.go
pkg/buildimage/manifests/utils.go

bufio.Scanner will return error when length of line is far more large than MaxScanTokenSize, use bufio.Reader instead.

fix: use bufio.reader to avoid token too long error

---

pkg/apply/applydrivers/apply_drivers_default.go
pkg/apply/reset.go
pkg/apply/run.go
pkg/apply/utils.go
pkg/apply/utils_test.go
pkg/clusterfile/pre_process.go
pkg/utils/iputils/iputils_v2.go

Refactor `Applier` to ensure consistent patterns for flagset

refactor: applier

---

controllers/user/go.mod
controllers/user/go.sum

Fix user controller module

---

scripts/generate_certificate.sh

```shell
Generate certificate suitable for use with any Kubernetes Mutating Webhook.
This script uses k8s' CertificateSigningRequest API to generate a certificate signed by k8s CA suitable for use with any Kubernetes Mutating Webhook service pod.
This requires permissions to create and approve CSR. See: https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster for detailed explanation and additional instructions.
The server key/cert k8s CA cert are stored in a k8s secret.
usage: ./scripts/generate_certificate.sh [OPTIONS]
The following flags are required.
--service          Service name of webhook.
--webhook          Webhook config name.
--namespace        Namespace where webhook service and secret reside.
--secret           Secret for CA certificate and server certificate/key pair. …
```

Generate certificate suitable for use with any Kubernetes Webhook.

---

docker/sealos/Dockerfile
docker/sealos/Dockerfile.main

When trying to run `sealos` tasks with the dev container, error `bash: /usr/local/sealos: Permission denied` occured. this PR sets default permission of the binary to `755`

fix: copy binary with execute permission

---

controllers/user/Makefile
controllers/user/README.md
controllers/user/config/manager/manager.yaml
controllers/user/controllers/payment_controller.go
controllers/user/deploy/manifests/deploy.yaml

Inject the password into the payment environment variable through secret
secret example(data is base64)
```yaml
apiVersion: v1
kind: Secret
metadata:
name: payment-secret
namespace: sealos
type: Opaque
data:
xxxx: "xxxx"
```

feat:add payment secvet set env

---

cmd/sealos/cmd/run.go
pkg/image/binary/image.go
pkg/image/buildah/image/load.go
pkg/image/buildah/registry/pull.go
pkg/image/cmd/load.go
pkg/image/cmd/save.go
pkg/image/types/interface.go

Fix #1770 
Now `sealos save` supports pulling image if there's no image locally, and `sealos run` supports loading image from archive if the command line argument ends with `.tar` or `.gz`.
```shell
$ sealos save -o kubernetes-v1.24.0.tar.gz labring/kubernetes:v1.24.0
```
There's no need to `sealos pull` in advance.
```shell
$ sealos run kubernetes-v1.24.0.tar.gz --single
```
There's no need to `sealos load` in advance.

feat: support pulling in sealos save and loading in sealos run

---

controllers/user/controllers/account_controller.go

Fix #1816 
account delete payment more than 5 minutes

feat:account delete payment delay 5 minutes

---

controllers/terminal/api/v1/terminal_types.go
controllers/terminal/config/crd/bases/terminal.sealos.io_terminals.yaml
controllers/terminal/config/rbac/role.yaml
controllers/terminal/controllers/ingress.go
controllers/terminal/controllers/terminal_controller.go
controllers/terminal/deploy/Dockerfile
controllers/terminal/deploy/manifests/deploy.yaml

In order to make the ingress work normally, deploy the terminal in terminal-app namespace. And granting the read permissions of terminal-app namespace to the user. Thus the front can apply the yaml in user's namespace, and get terminal domain in terminal-app namespace.

feat: deploy terminal in terminal-app ns

---

pkg/auth/auth.go
pkg/auth/utils/config.go

fix: https://github.com/labring/sealos/issues/1887

fix: watch+select to get kubeconfig

---

desktop/frontend/src/components/app_window/help_dropdown.tsx

fix: alert cause copy fail

---

pkg/apply/run.go
pkg/apply/scale.go
pkg/apply/utils.go

Should fix #1787.
I'm not sure if these changes cover all the related cases and whether I'm using SSH correctly though.
@cuisongliu PTAL.

fix: get host arch using SSH for apply/run, apply/reset and apply/scale

---

pkg/apply/run.go

feature(main): fix nodes for single

---

.github/workflows/release.yml
.goreleaser.yml
docker/lvscare/Dockerfile.release
docker/sealos/Dockerfile.release

Re-introduce docker image building using GoReleaser as we are now able to fix issues with ARM64 images. This should (hopefully) be less error-prone than manual scripts.

ci: publish docker image for the release workflow with goreleaser

---

cmd/sealos/cmd/run.go
pkg/apply/applydrivers/apply_drivers_default.go
pkg/apply/args.go
pkg/apply/processor/create.go
pkg/apply/processor/delete.go
pkg/apply/processor/install.go
pkg/apply/run.go
pkg/constants/data.go
pkg/filesystem/rootfs/rootfs_default.go
pkg/runtime/registry.go
pkg/runtime/runtime_getter.go
pkg/types/v1beta1/cluster_args.go
pkg/types/v1beta1/constants.go

Signed-off-by: xuehaipeng <hpxue13@hotmail.com>
issue link: [1285](https://github.com/labring/sealos/issues/1285)
separated the registry from the first master node if specified `--registry` in command line, eg:
`sealos run labring/kubernetes:v1.25.0 labring/helm:v3.8.2 labring/calico:v3.24.1 --masters 192.168.116.138 --nodes 192.168.116.139 --registry 192.168.116.135 `
if the `--registry` option is not specified, the first master node (master0) is used as the registry node, as before.

feature(main): separate registry from master0

---

pkg/image/buildah.go

feature(main): fix already installed buildah

---

controllers/imagehub/config/manager/kustomization.yaml
controllers/imagehub/deploy/Dockerfile
controllers/imagehub/deploy/manifests/deploy.yaml

add deply yaml
Signed-off-by: lingdie <lingdie.yy@outlook.com>

add imagehub controller deply yaml

---

controllers/user/controllers/account_controller.go
controllers/user/controllers/helper/kubeconfig.go
controllers/user/controllers/helper/sa.go
controllers/user/controllers/helper/suite_test.go
controllers/user/controllers/helper/webhook.go
controllers/user/controllers/helper/webhook.md
controllers/user/controllers/user_controller.go
pkg/apply/args.go
pkg/constants/contants.go

feature(main): add webhook config to sdk

---

pkg/apply/run.go

should use a copy of *v2.Cluster.

fix: misuse of *cluster pointer

---

pkg/checker/cluster_checker.go
pkg/checker/node_checker.go
pkg/env/env.go
pkg/image/buildah/cluster/buildah/inspect.go
pkg/image/merge.go
pkg/remote/remote.go
pkg/remote/util.go
pkg/template/funcmap.go
pkg/template/template.go
pkg/utils/template/template.go

use `text/template` to avoid string escaping.

fix: replace text/template from html/template

---

staging/src/github.com/labring/image-cri-shim/pkg/server/cri_server.go

bug: fixed parse image name and tag

---

controllers/infra/api/v1/infra_types.go

infra calculate price has error,fix it and change int64 to float64 in calculating.
price search:https://www.amazonaws.cn/ec2/pricing/ec2-linux-pricing/

Fix: fix aws ec2 price

---

controllers/infra/drivers/aws/create_instance.go
controllers/infra/drivers/aws/get_image.go

1. add aws images client api
2. get root device name from image
3.  rename data disks to bdms(blockdevicemappings)
Signed-off-by: ybyang <ybyang7@iflytek.com>

feat:  add describe image api and get root device name from ami.

---

pkg/buildah/buildah.go
pkg/buildah/create.go
pkg/buildah/interface.go
pkg/buildah/unshare.go

Since PR#2163 remove `create` subcommand, now it's back.

feat: add back create subcommand and support manually unshare

---

pkg/bootstrap/bootstrap.go
pkg/runtime/reset.go
pkg/types/v1beta1/cluster_args.go

Move nodes reset(including addons and system reset) process after kubeadm reset.

fix: adjust sealos reset process order

---

pkg/apply/applydrivers/apply_drivers_default.go
pkg/ssh/scp.go

Replace default checkRemoteFileExist function but still provide a way to use the legacy function(for testing purpose)…
The legacy one will be removed in the next few commits.

enchance: optimizing ssh copy

---

pkg/buildah/common.go
pkg/buildah/setup.go
pkg/ssh/scp.go
pkg/ssh/sshcmd.go
pkg/unshare/unshare.go

In case some other go module require pkg/ssh, so move the only necessary function out of pkg/buildah.

fix: move IsRootless out of pkg/buildah

---

pkg/guest/guest.go

No need to run guest command for rootfs/patch type cloudimages.

fix: only run guest command for app type cloudimage

---

.github/workflows/ci.yml

According to [this blog](https://github.blog/changelog/2022-12-01-github-actions-larger-runners-using-ubuntu-latest-label-will-now-use-ubuntu-22-04/), `ubuntu-latest` version for actions runner may be updated soon and may affect the compiled binaries within. We should pin the ubuntu version to avoid possible breaking changes.

ci: pin ubuntu version in CI to 20.04

---

.github/workflows/release.yml
.goreleaser.yml

1. In the Release workflow we were still using `ubuntu-latest`. This PR pins it down to `ubuntu-18.04` for better compatibility.
2. From https://github.com/labring/sealos/commit/0eb99622295b1f35885c044ddaa95326fdb9f66b, sealctl now needs CGO support, so we should use correct args in goreleaser too. This should fix #2246.
3. Add release checksum.

Pin ubuntu version in Release workflow, use correct goreleaser args for sealctl and add release checksum

---

pkg/ssh/scp.go
pkg/ssh/utils.go

1. add more verbose logging
2. skip error when failed to calculating sha256 for remote file, since error already logging.

debug: more verbose logging for scp

---

pkg/buildah/build.go
pkg/buildah/from.go
pkg/buildah/login.go
pkg/buildah/manifest.go
pkg/buildah/pull.go
pkg/buildah/push.go
pkg/buildah/save.go

since `tls-verify` is default to `false`, so we mark this flag as hidden.

mark tls-verify flag hidden

---

pkg/apply/applydrivers/apply_drivers_default.go
pkg/apply/run.go

related with issue https://github.com/labring/sealos/issues/2140
reproduce the bug
the first apply -f : 
```
root@lin-master:~/tmp/cf# cat Clusterfile
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
name: default
spec:
hosts:
- ips:
- 10.35.128.5:22
roles:
- master
- amd64
image:
- labring/kubernetes:v1.24.0
- labring/calico:v3.22.1
root@lin-master:~/tmp/cf# sealos apply -f Clusterfile
2022-12-22T03:59:26 info Start to create a new cluster: master [10.35.128.5], worker [], registry 10.35.128.5
......
2022-12-22T04:01:28 info succeeded in creating a new cluster, enjoy it!
2022-12-22T04:01:28 info 
___           ___           ___           ___       ___           ___
/\  \         /\  \         /\  \         /\__\     /\  \         /\  \
/::\  \       /::\  \       /::\  \ …
```

bugfix: Apply twice will call initCluster twice that causes kubelet port occupied.

---

cmd/sealos/cmd/root.go
pkg/buildah/build.go
pkg/buildah/buildah.go
pkg/buildah/containers.go
pkg/buildah/from.go
pkg/buildah/images.go
pkg/buildah/inspect.go
pkg/buildah/load.go
pkg/buildah/login.go
pkg/buildah/logout.go
pkg/buildah/manifest.go
pkg/buildah/mount.go
pkg/buildah/pull.go
pkg/buildah/push.go
pkg/buildah/rm.go
pkg/buildah/rmi.go
pkg/buildah/save.go
pkg/buildah/setup.go
pkg/buildah/tag.go
pkg/buildah/umount.go
pkg/buildah/unshare.go

1. more friendly error output when running rootless mode without required packages like `uidmap`/`fuse-overlayfs`
2. use builtin `cobra.Command.CommandPath()` to replace `getFullCmdName`

fix: more friendly error output when running rootless mode 

---

pkg/buildah/common.go
pkg/buildah/inspect.go
pkg/buildah/interface.go
pkg/buildah/manifest.go

set SkipTLSVerify to true for SystemConext when there is a potential remote lookup operation in some subcommands and 
those commands do not provide `--tls-verify` flag.

fix: set SkipTLSVerify to true for SystemConext 

---

docs/4.0/docs/examples/how-to-upgrade-cluster.md
pkg/apply/processor/install.go
pkg/apply/run.go
pkg/constants/data.go
pkg/runtime/defaults/default_kubeadm_config.go
pkg/runtime/runtime.go
pkg/runtime/runtime_getter.go
pkg/runtime/upgrade.go
pkg/types/v1beta1/cluster_args.go
pkg/utils/images/images.go
pkg/utils/versionutil/version.go

solve issue #1944 .
the upgrade process contains :
1. upgrade kubeadm,kubeclt,kubelet.
2. upgrade static pods including api-server, controller-manager,scheduler,etcd.
usage in the docs.

Feature: upgrade the cluster

---

pkg/ssh/connect.go
pkg/ssh/exec.go
pkg/ssh/scp.go
pkg/ssh/ssh.go
pkg/ssh/sshcmd.go

1. fix `connection reset by peer` error during executing sealos exec/scp command, not need to check ssh connections for all nodes;
2. refactor ssh.Connect with backoff retry;
3. rename some function names;

refactor: implement exponential backoff retry for ssh connect

---

pkg/apply/processor/scale.go
pkg/client-go/kubernetes/attribute.go
pkg/runtime/master.go
pkg/runtime/node.go
pkg/runtime/utils.go

bug: Cloud provider will firstly delete instance and then the control-plane will lost connection with the host, which causes deleting node in k8s failed.
solution:  Delete the node in k8s first and then reset the node, this operating order would prevent deleting failure when the nodes to be deleted crashed or not reachable.

fix: modify delete logic to support cloud provider

---

pkg/apply/processor/interface.go
pkg/buildah/constants.go
pkg/buildah/interface.go
pkg/buildah/merge.go

inspect image in local store
```go
.InspectImage("containers-storage://apache/apisix:3.1.0-debian")
.InspectImage("apache/apisix:3.1.0-debian")
.InspectImage("@digestID")
```
inspect remote image
```go
.InspectImage("docker://apache/apisix:3.1.0-debian")
.InspectImage("apache/apisix:3.1.0-debian", "docker")
```
inspect oci-archive, docker-archive
```go
.InspectImage("path/of/oci/tarfile.tar", "oci-archive")
.InspectImage("path/of/docker/tarfile.tar", "docker-archive")
```

feat: refactor buildah's inspect method so we can inspect remote image

---

pkg/runtime/kubeadm.go

fix #2459 #2447 
i also test sealos add node/master, del node/master, is ok

bugfix: kubelet cgroup driver not match containerd

---

controllers/infra/common/common.go
controllers/infra/config/samples/infra_v1_infra.yaml
controllers/infra/controllers/infra_controller.go
controllers/infra/drivers/aws/create_instance.go
controllers/infra/drivers/aws/create_volume.go
controllers/infra/drivers/reconcile.go
docs/4.0/docs/cloud/apps/scp/scp.md
docs/4.0/i18n/zh-Hans/cloud/apps/scp/scp.md

add keypair tag to support keypair gc

feat: keypair garbage collection

---

pkg/buildah/inspect.go

Fix #2524 
Currently, there is an error when executing the run command with a short name:
This PR adds the `localhost` and `docker.io` prefixes to the shortname.
More info about the shortname, please see: https://github.com/containers/buildah/issues/1034

fix: inspect function support resolving shortname

---

pkg/runtime/defaults/default_kubeadm_config.go
pkg/runtime/defaults/v125/default_kubeadm_config.go
pkg/runtime/kubeadm.go
pkg/runtime/kubeadm_config.go

Seems it's already implemented but needs some adjustments. #2562

refactor: adjust the order of merging kubeadm configs

---

pkg/apply/processor/scale.go
pkg/buildah/imagecr.go
pkg/buildah/imagecrbuilder.go
pkg/buildah/imagecrtypes.go
pkg/buildah/push.go

Refactor imagecrbuilder, add cr-option flag.
Default `cr-option` is `auto`, if registry is sealos registry, `auto` will switch to `yes` otherwise `no`.
Add `--cr-option only` flag, apply image cr only without push image.
Add `--cr-option yes` flag, apply cr when push images, will check registry too.
Add `--cr-option no` flag, will not apply cr when push images.

feat: refactor imagecrbuilder, add cr-option flag.

---

pkg/runtime/kubeadm.go
pkg/runtime/master.go
pkg/runtime/node.go
pkg/runtime/runtime.go

Use lock to ensure safe build configuration under goroutine.

---

cmd/sealos/cmd/version.go
go.mod

If the user simply installed SealOS, but Kubectl already had a bound cluster before installation, sealos version will print the Kubectl cluster, which was not launched by SealOS. If this happens, the sealo version command should not obtain the cluster information of kubectl

better sealos version

---

controllers/account/config/default/manager_auth_proxy_patch.yaml

用户没有权限访问自己的account，发现subject.namespace是default，应该是user-system，在环境变量里面加上就行
```
[root@VM-4-13-centos manifests]# kubectl get rolebinding userAccountRoleBinding-ff84005c-4e28-4932-add0-f51ac834e489 -n sealos-system -oyaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
creationTimestamp: "2023-02-27T04:05:52Z"
name: userAccountRoleBinding-ff84005c-4e28-4932-add0-f51ac834e489
namespace: sealos-system
resourceVersion: "124793303"
uid: 03335733-8105-45e1-b091-1bf892692239
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: Role
name: userAccountRole-ff84005c-4e28-4932-add0-f51ac834e489
subjects:
- kind: ServiceAccount
name: ff84005c-4e28-4932-add0-f51ac834e489
namespace: default
```

rolebing.subject.naemspace should set user-system

---

.github/workflows/test_run.yml
cmd/sealos/cmd/run.go
pkg/apply/args.go
pkg/apply/run.go
pkg/clusterfile/clusterfile.go
pkg/clusterfile/clusterfile_test.go
pkg/clusterfile/pre_process.go
pkg/clusterfile/testdata/kubeadmConf.yaml

Every time I run a Single host cluster, I need to manual remove the Taint.
```shell
$ sealos run labring/kubernetes:v1.25.0 labring/helm:v3.8.2 labring/calico:v3.24.1 --single
$ kubectl taint nodes --all node-role.kubernetes.io/master:NoSchedule-
```
I add a patch to do the untaint automatic #2317.

feature: single host should allow scheduling to master

---

controllers/account/api/v1/account_types.go
controllers/account/config/crd/bases/account.sealos.io_accounts.yaml
controllers/account/config/default/manager_auth_proxy_patch.yaml
controllers/account/config/manager/manager.yaml
controllers/account/config/samples/account_v1_account.yaml
controllers/account/config/samples/account_v1_accountbalance.yaml
controllers/account/controllers/account_controller.go
controllers/account/deploy/manifests/deploy.yaml

if user is new,will get 5 RMB to use sealos cloud apps.
test success
```
kubectl apply -f ./config/sample/account_v1_accountyaml   
kubectl apply -f ./config/sample/account_v1_accountbalance.yaml   
kubectl get account  account-sample  -n sealos-system -oyaml
apiVersion: account.sealos.io/v1
kind: Account
metadata:
annotations:
account.sealos.io/new-account: "false" # get annotation success
creationTimestamp: "2023-03-02T07:00:29Z"
generation: 1
name: account-sample
namespace: sealos-system
resourceVersion: "2988085"
uid: 6f6c116f-5225-40fd-806d-73015348daf9
spec: {}
status:
balance: 500. # recharge success
chargeList:
- balance: 500
describe: new account charge
time: "2023-03-02T07:00:29Z"
- accountBalanceName: accountbalance-sample
balance: 100
time: "2023-03-02T07:00:29Z" …
```

add account balance when account is new user

---

pkg/registry/save.go

fix #2061
From the log, the reason for the error is that `manifest.layer.digest` is 0,
Not sure why it's empty.

fix `runtime error: slice bounds out of range [:19] with length 0`

---

.github/workflows/test_run.yml
pkg/runtime/kubeadm_config.go

As describe in #2692, Set Etcd.External cause program failed.
`Etcd.External` or `Etcd.local` only one can be filled.

BUG: setting external ETCD address does not take effect

---

pkg/apply/applydrivers/apply_drivers_default.go

Fix when no app image is specified, run error but the command condition still returns success
fix #2714

Fix when no app image is specified, run error but the command condition still returns success

---

.github/workflows/test_run.yml
pkg/runtime/kubeadm_config.go

custom certSANs should append to the default ClusterConfiguration certSANs

BUG: custom certSANs should append to the default ClusterConfiguration certSANs

---

pkg/clusterfile/clusterfile.go
pkg/clusterfile/pre_process.go
pkg/runtime/kubeadm.go
pkg/runtime/kubeadm_config.go

as PR #2752  add a default mergo option for var `defaultMergeOpts`, when there are some slice type fileds in the kubernetes builtin struct, and this field happens to be nil after marshaling from the clusterfile, the registered default function **might** set default val for those fields, then the appendslice option for mergo may cause problems when initializing the cluster.

fix: avoid invoking default function before complete merging kubeadmconfigs

---

cmd/sealctl/cmd/cri.go
cmd/sealctl/cmd/kube.go
cmd/sealctl/cmd/password.go
cmd/sealctl/cmd/static_pod.go
cmd/sealctl/cmd/token.go
controllers/user/controllers/helper/webhook.md
docs/4.0/docs/cloud/apps/postgres/postgres.md
docs/4.0/i18n/zh-Hans/cloud/apps/postgres/postgres.md
pkg/buildah/create.go
pkg/utils/maps/maps_test.go
pkg/utils/yaml/yaml.go
staging/src/github.com/labring/image-cri-shim/pkg/cri/cri_test.go

1. The print built-in function formats its arguments in an implementation-specific way and writes the result to standard error.
Use `fmt.Println` instead.  fix #2723 
2. change docs: `kubectl get secrets ${UserName}.${CRDName}.credentials.postgresql.acid.zalan.do --template '{{.data.password}}' | base64 -d`

Fix println built-in function output to standard error

---

pkg/ssh/clusterclient.go

Resolves #2807 
To ensure thread safety in `clusterClient` map access, this PR implements a solution that uses a mutex lock to synchronize concurrent reads and writes to the maps. This prevents race conditions and ensures safe access to the maps.

fix concurrent map access in clusterClient

---

fork/github.com/heroku/docker-registry-client/registry/registry.go
pkg/checker/cri_shim_checker.go
staging/src/github.com/labring/image-cri-shim/pkg/server/server.go
staging/src/github.com/labring/image-cri-shim/pkg/server/utils.go
staging/src/github.com/labring/image-cri-shim/pkg/shim/shim.go
staging/src/github.com/labring/image-cri-shim/pkg/types/config.go

as a image shim service, it can register all versions of the `ImageServiceServer` cause it doesn't care what version of the ImageService the CRI had.
and also might fix #2851

feat: register all versions of the ImageServiceServer

---

controllers/cluster/controllers/cluster_controller.go
controllers/cluster/main.go
controllers/pkg/utils/rate_limiter.go
controllers/pkg/utils/retry_create_or_update.go

By setting RateLimiter, the processing rate of the controller can be effectively controlled, avoiding excessive load on the Kubernetes API Server and improving the performance and stability of the controller.I recommend adding RateLimiter to all controllers.

Add rateLimiter for controllers

---

.github/workflows/e2e_metering.yml

The reason why metering e2e ci fail is that just build ghcr.io/labring/sealos-metering-controller:deploy-cluster,but not build newest ghcr.io/labring/sealos-metering-controller:dev.
local repo test is correct.https://github.com/xiao-jay/sealos/actions/runs/4549846850/jobs/8022346983

fix(ci): metering e2e ci error

---

.github/workflows/release.yml
.goreleaser.yml
scripts/release/note.sh

Description:
This pull request updates the auto-release logic to ensure that deb and rpm packages are not published for non-production releases. The updated logic checks the release version format and skips the deployment of deb and rpm packages if the version indicates a non-production release (e.g., v4.1.7-rc1, v4.1.7-alpha1).
By implementing this change, we can reduce the risk of accidentally publishing unstable or untested packages to end-users and better manage our release process.
Changes in this PR include:
- Updated release script to check for non-production version format
- Skipped deb and rpm package deployment for non-production releases
Please review the changes and let me know if any further adjustments are needed.

Title: Update auto-release logic to skip deb and rpm packages for non-production releases

---

pkg/buildah/interface.go
pkg/buildah/runtime.go

fix issues like following:
1. running `sealos run labring/kubernetes:v1.25.0 xxx-helm.tar`, sealos will save the `xxx-helm.tar` as image id in the clusterfile;
2. after rebooting host which running sealos command, it'll failed to run any sealos commands , like `add`/`run` or whatever, cause image id cannot be pulled from docker.io/library/$imageid
---
looks like it's already fix in #2879, but to avoid this, we'd better refactor the `Load` function for good.

fix: return image name if oci archive file has names instead of id

---

pkg/registry/save.go

revert commit https://github.com/labring/go-containerregistry/commit/b574d7cdabb179350d39425a6fcae99610971ae8

fix: use assertion, avoid patching external interface

---

pkg/buildah/diff.go
pkg/buildah/runtime.go

```bash
Examples:
sealos diff labring/kubernetes:v1.25 labring/kubernetes:v1.26
sealos diff -o table oci-archive:/path/of/older.tar oci-archive:/path/of/newer.tar
sealos diff --patch --save -o patch.tar -t labring/kubernetes:patch-from-125-126 labring/kubernetes:v1.25 labring/kubernetes:v1.26
Flags:
--diff-type string   type of object to diff, available options are [container, image, all] (default "image")
-h, --help               help for diff
-o, --output string      change the output format, available options are [json, table] (default "json")
--patch              if enabled then create a named archive file contains changes that we interested
--save               if enabled and --tag flag is specified, diff will save the built image into a oci-archive file with the name of --output
-t, …
```

refactor: add back auto build and auto save abilities in `diff` command

---

pkg/runtime/update_cert.go

```
sealos cert --alt-names xxxx
...
2023-04-06T15:32:44 info delete pod apiserver from crictl
E0406 15:32:46.219015 3681139 remote_runtime.go:269] "StopPodSandbox from runtime service failed" err="rpc error: code = DeadlineExceeded desc = context deadline exceeded" podSandboxID="8f04a0e57f14c"
FATA[0002] stopping the pod sandbox "8f04a0e57f14c": rpc error: code = DeadlineExceeded desc = context deadline exceeded 
Error: failed to generate cert exit status 1
```
#2497

fix stop kube-apiserver pod cause `DeadlineExceeded` when update cert.

---

pkg/registry/registry.go

should use index to get the correct registry.

fix: fix always return the insecure registry

---

pkg/checker/host_checker.go

Support checking cluster's master node number as request in #2829

feature(main): support checking cluster's no-odd number of master node

---

pkg/apply/applydrivers/apply_drivers_default.go
pkg/apply/processor/create.go
pkg/apply/processor/delete.go
pkg/apply/processor/error.go
pkg/apply/processor/scale.go
pkg/checker/host_checker.go
pkg/runtime/kubeadm.go
pkg/runtime/master.go
pkg/runtime/update_cert.go

fix:
fix: #2398 
Get certSANS from kubeadm config after initializing cluster (join master, update cert)
Fix incorrect cluster state saving, skip precheck && preProcess incorrectly save cluster state.

bugfix: the failure to add master after updating the certificate

---

.github/workflows/sync_docs.yml

https://github.com/labring/sealos/actions/runs/4687545323/jobs/8306974772
https://github.com/BetaHuhn/repo-file-sync-action/pull/242
this error has been fixed in 1.17.21

ci(sync-docs): fix sync docs error

---

controllers/infra/drivers/aliyun/aliyun.go
controllers/infra/drivers/aliyun/delete_instance.go
controllers/infra/drivers/driver.go

Fix deleteInstancesByOption.instanceIds length is always greater than 0, resulting in repeated attempts to delete instances
Check aliyun env to return error

fix len(deleteInstancesByOption.instanceIds) always gt 0

---

pkg/apply/apply.go
pkg/apply/utils.go
pkg/types/v1beta1/constants.go

This PR has the following changes:
- fix apply single-mode miss arch role.
- default SSH initialization in single-node mode.
refer to #3051

fix: auto-completion of arch role and default SSH initialization in single-node mode

---

controllers/account/controllers/account_controller.go
controllers/account/controllers/account_controller_test.go

When the user recharges, different amounts are given according to the recharge amount.
[1-298] -> 0%, [299-598] -> 10%, [599-1998] -> 15%
[1999-4998] -> 20%, [4999-19998] -> 25%, [19999+] -> 30%

feature: recharge extra gift amount

---

pkg/cert/kube_certs.go

```bash
$ sealos version --short
4.2.0-f696a621
```
1. generate clusterfile
```bash
sealos gen labring/kubernetes:v1.25.0 \
--masters 10.246.132.125,10.246.132.132,10.246.132.145 \
--nodes 10.246.132.142 \
--user root --passwd password > my.Clusterfile
```
2. modify clusterfile, change ServiceSubnet
```bash
$ vim my.Clusterfile.new
$ diff my.Clusterfile.new my.Clusterfile
137c137
<   ServiceSubnet: 172.6.0.0/13
---
>   ServiceSubnet: 10.96.0.0/22
```
3. sealos apply
```bash
$ sealos apply -f my.Clusterfile.new
```
4. get  "certificate apiserver is invalid"  error 
<br />
<br />
the correct(172.6.0.0/13) first ip is 172.0.0.1

fix(cert sign): not get the correct first svc ip from cidr

---

pkg/utils/versionutil/version.go
pkg/utils/versionutil/version_test.go

fix version comparison issue #3327

fix:fix version comparison issue

---

go.mod
go.sum
go.work.sum

rollback github.com/containers/storage version from v1.46.2 to v1.46.1, as [commit](https://github.com/containers/storage/commit/da0df59a00e0a2cd2880c7cc82322989834e7bf4) no more ignoring unmount error. maybe this is a rootless issue.

fix: error while unmount container mountpoint

---

pkg/buildah/diff.go

restore feature for creating patch image between two cloudimages in diff command, it's useful when user can not connect to the registry directly, so we can use this method to create a relatively smaller cloudimage.

restore easter egg feature in diff command

---

pkg/ssh/scp.go
pkg/ssh/ssh.go
pkg/ssh/sshcmd.go
pkg/ssh/suftp.go

Add sudo support for scp  https://github.com/labring/sealos/issues/3402.
After this, wen can use sudo user to install k8s
```
sudo sealos run labring/kubernetes:v1.26.1 labring/helm:v3.10.3 labring/calico:v3.25.0 --masters 10.29.13.21 --nodes 10.29.13.22 -u sudouser -p xxx
```
TEST scp command

Feature:sudo support for scp

---

docs/4.0/docs/lifecycle-management/operations/build-image/build_run_application_private_registry.md
docs/4.0/docs/lifecycle-management/operations/run-cluster/gen-apply-cluster.md
docs/4.0/docs/lifecycle-management/quick-start/quick-start.md
docs/4.0/docs/lifecycle-management/reference/sealos/commands/gen.md
docs/4.0/i18n/zh-Hans/lifecycle-management/operations/build-image/build_run_application_private_registry.md
docs/4.0/i18n/zh-Hans/lifecycle-management/operations/run-cluster/gen-apply-cluster.md
docs/4.0/i18n/zh-Hans/lifecycle-management/quick-start/quick-start.md
docs/4.0/i18n/zh-Hans/lifecycle-management/reference/sealos/commands/gen.md

this is not a feature or bugfix, it's just an optimization suggestion for doc.
when we run `sealos run` or `sealos gen` command, the order of the image list is important.
if we set the helm behind the calico, nothing will run after the components of k8s installed.

opt: add hints for the order of commands in documentations

---

pkg/cert/kube_certs.go
pkg/utils/iputils/iputils_v2.go

support Dual-stack https://github.com/labring/sealos/issues/2919
k8sversion: 1.26.1
calico: v3.25.0
deployed on 2 nodes:
- lcx-test-ipv6-1 (controller-plane)
- lcx-test-ipv6-2
- Host IP:
lcx-test-ipv6-1
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast state UP group default qlen 1000
link/ether fa:16:3e:8c:91:0a brd ff:ff:ff:ff:ff:ff
inet 192.168.0.10/24 brd 192.168.0.255 scope global dynamic eth0
valid_lft 58574sec preferred_lft 58574sec
inet6 2001:db8::f816:3eff:fe8c:910a/64 scope global noprefixroute dynamic 
valid_lft 86378sec preferred_lft 14378sec
inet6 fe80::f816:3eff:fe8c:910a/64 scope link noprefixroute 
valid_lft forever preferred_lft forever
``` 
lcx-test-ipv6-2
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast state UP group …
```

feat: support dual-stack

---

pkg/ssh/ssh.go

bugfix:If use user root and the “root” user is not specified, sudo should be disabled.

fix: if the root user is not specified,sudo should be disabled.

---

docs/4.0/docs/lifecycle-management/operations/run-cluster/gen-apply-cluster.md
docs/4.0/i18n/zh-Hans/lifecycle-management/operations/run-cluster/gen-apply-cluster.md

`sealos gen labring/kubernetes:v1.25.0 labring/helm:v3.8.2 labring/calico:v3.24.1`
generated Clusterfile should be include labring/helm:v3.8.2

docs: fix sealos gen Clusterfile

---

controllers/node/config/configmap/configmap.yaml
controllers/node/config/configmap/kustomization.yaml
controllers/node/config/default/kustomization.yaml
controllers/node/config/rbac/role.yaml
controllers/node/config/rbac/role_binding.yaml
controllers/node/controllers/gpu_controller.go
controllers/node/deploy/Kubefile
controllers/node/deploy/manifests/deploy.yaml

1. add node-gpu-info configmap & role & rolebinding to deploy.yaml
2. use clientSet to get resources from the API Server, not from Informer's cache

feat: add initGPUInfoCM func

---

pkg/runtime/kubernetes/types/default_kubeadm_config.go

fix BUG #3799 
set 'clusterDomain' in kubelet empty, it will be set the same with 'dnsDomain' in kubeadm,
both of them are set 'cluster.local' as default if you leave them empty.

fix: dnsDomain does not take effect in kubelet

---

pkg/utils/file/file_v2.go

skip cp when the target file is the same

fix: skip same path

---

pkg/apply/applydrivers/apply_drivers_default.go

support https://github.com/labring/sealos/issues/3859

feature: sync .sealos workdir

---

pkg/ssh/scp.go

fix: scp files

---

controllers/account/config/rbac/role.yaml
controllers/account/controllers/namespace_controller.go
controllers/account/deploy/manifests/deploy.yaml.tmpl

update rbac and fix minio user not exist error

---

frontend/desktop/src/components/desktop_content/index.tsx
frontend/providers/cronjob/src/api/platform.ts
frontend/providers/cronjob/src/pages/_app.tsx
frontend/providers/cronjob/src/pages/api/platform/getEnv.ts
frontend/providers/cronjob/src/store/env.ts
frontend/providers/dbprovider/src/api/platform.ts
frontend/providers/dbprovider/src/pages/_app.tsx
frontend/providers/dbprovider/src/pages/api/getEnv.ts
frontend/providers/dbprovider/src/pages/db/detail/components/AppBaseInfo.tsx
frontend/providers/dbprovider/src/pages/db/detail/index.tsx
frontend/providers/dbprovider/src/store/env.ts
frontend/providers/dbprovider/src/store/static.ts
frontend/providers/dbprovider/src/utils/json2Yaml.ts
frontend/providers/template/src/pages/deploy/components/Header.tsx
frontend/providers/template/src/pages/develop/components/YamlList.tsx
frontend/providers/template/src/pages/develop/index.tsx
frontend/providers/template/src/pages/index.tsx
frontend/providers/template/src/pages/instance/components/dbList.tsx
service/license/src/pages/api/cluster/activeCluster.ts

feat:control file migration and template sharing link 

---

frontend/providers/template/src/pages/api/listTemplate.ts
frontend/providers/template/src/pages/deploy/components/ReadMe.tsx
frontend/providers/template/src/utils/tools.ts
service/license/src/pages/api/cluster/activeCluster.ts
service/license/src/services/backend/db/payment.ts

fix template readme  img src

---

controllers/license/internal/controller/license_controller.go

fix: activator logic.

---

frontend/desktop/src/hooks/useDriver.tsx
frontend/providers/template/src/pages/api/updateRepo.ts
service/license/src/pages/api/payment/create.ts
service/license/src/pages/cluster/components/Recharge.tsx
service/license/src/pages/pricing/components/Product.tsx
service/license/src/types/payment.ts

fix:desktop usedriver & tempalte yml

---

deploy/cloud/manifests/tls-secret.yaml
scripts/cloud/install.sh

chore: fix pull image.

---

frontend/providers/applaunchpad/src/components/Table/index.tsx
frontend/providers/applaunchpad/src/pages/_app.tsx
frontend/providers/applaunchpad/src/pages/apps/components/empty.tsx
frontend/providers/applaunchpad/src/services/backend/response.ts
frontend/providers/cronjob/src/pages/jobs/components/empty.tsx
frontend/providers/dbprovider/src/components/Menu/index.tsx
frontend/providers/dbprovider/src/components/RangeDate/index.tsx
frontend/providers/dbprovider/src/components/Table/index.tsx
frontend/providers/dbprovider/src/constants/theme.ts
frontend/providers/dbprovider/src/pages/_app.tsx
frontend/providers/dbprovider/src/pages/db/detail/components/Header.tsx
frontend/providers/dbprovider/src/pages/db/detail/index.tsx
frontend/providers/dbprovider/src/pages/db/edit/components/Form.tsx
frontend/providers/dbprovider/src/pages/dbs/components/dbList.tsx
frontend/providers/dbprovider/src/pages/dbs/components/empty.tsx
frontend/providers/dbprovider/src/store/env.ts
frontend/providers/template/src/pages/develop/index.tsx
frontend/providers/template/src/services/backend/response.ts

fix:db auth & template develop

---

frontend/desktop/src/pages/api/auth/phone/sms.ts
frontend/desktop/src/services/backend/db/verifyCode.ts

fix(desktop):fix verification code restriction

---

controllers/account/controllers/account_controller.go
controllers/pkg/resources/resources.go

adapt ephemeral storage limit range

---

scripts/cloud/install.sh

fix install cli with proxy

---

service/account/Makefile
service/account/api/api.go
service/account/dao/init.go
service/account/dao/interface.go
service/account/dao/interface_test.go
service/account/docs/docs.go
service/account/docs/swagger.json
service/account/docs/swagger.yaml
service/account/helper/common.go
service/account/helper/request.go
service/account/main.go
service/account/router/router.go

add cost service swagger 

---

controllers/admission/api/v1/ingress_webhook.go
controllers/admission/api/v1/types.go
controllers/admission/cmd/main.go
controllers/admission/deploy/Kubefile
controllers/admission/deploy/manifests/deploy.yaml.tmpl

feat: support multi domains for ingress webhooks.

---

frontend/providers/template/deploy/manifests/deploy.yaml.tmpl

chore: template add init container.

---

frontend/providers/dbprovider/public/locales/en/common.json
frontend/providers/dbprovider/public/locales/zh/common.json
frontend/providers/dbprovider/src/constants/backup.ts
frontend/providers/dbprovider/src/constants/db.ts
frontend/providers/dbprovider/src/pages/api/backup/create.ts
frontend/providers/dbprovider/src/pages/api/getSecretByName.ts
frontend/providers/dbprovider/src/pages/api/getStatefulSetByName.ts
frontend/providers/dbprovider/src/pages/api/platform/getVersion.ts
frontend/providers/dbprovider/src/pages/api/pod/getPodsByDBName.ts
frontend/providers/dbprovider/src/pages/db/detail/components/AppBaseInfo.tsx
frontend/providers/dbprovider/src/pages/db/detail/components/BackupTable.tsx
frontend/providers/dbprovider/src/pages/db/detail/components/RestoreModal.tsx
frontend/providers/dbprovider/src/pages/db/detail/index.tsx
frontend/providers/dbprovider/src/pages/dbs/index.tsx
frontend/providers/dbprovider/src/store/static.ts
frontend/providers/dbprovider/src/types/db.d.ts
frontend/providers/dbprovider/src/utils/adapt.ts
frontend/providers/dbprovider/src/utils/json2Yaml.ts
frontend/providers/dbprovider/src/utils/user.ts

feat:db provider adapted to 0.8.1

---

frontend/providers/dbprovider/public/locales/zh/common.json
frontend/providers/dbprovider/src/pages/db/edit/components/Form.tsx

Follow guidance, add a small notification to users when they select one replicas in database page.

small feat: add database tips one user select 1 replicas

---

frontend/providers/applaunchpad/next.config.js
frontend/providers/cronjob/next.config.js
frontend/providers/dbprovider/deploy/manifests/rbac.yaml
frontend/providers/dbprovider/next.config.js
frontend/providers/dbprovider/src/pages/api/backup/updatePolicy.ts
frontend/providers/dbprovider/src/pages/db/detail/components/AppBaseInfo.tsx
frontend/providers/dbprovider/src/pages/db/detail/components/BackupModal.tsx
frontend/providers/dbprovider/src/services/backend/kubernetes.ts
frontend/providers/dbprovider/src/types/backup.d.ts
frontend/providers/dbprovider/src/types/cluster.d.ts
frontend/providers/dbprovider/src/utils/json2Yaml.ts
frontend/providers/license/next.config.js
frontend/providers/template/next.config.js

fix:dbprovider auto backup

---

deploy/objectstorage/scripts/minio.sh

Previously prone to timeouts when connecting to minio, the process has been optimized and the number of connection retries has been changed from countless to 100 (once per second).

optimize init minio sh

---

pkg/apply/applydrivers/apply_drivers_default.go
pkg/apply/processor/interface.go

fix: issue #4536

---

deploy/objectstorage/Kubefile

change admin to username

---

deploy/objectstorage/init.sh
deploy/objectstorage/scripts/minio.sh

add pull file func

---

frontend/providers/costcenter/src/components/billing/InOutTabPanel.tsx
frontend/providers/costcenter/src/components/billing/RechargeTabPanel.tsx
frontend/providers/costcenter/src/components/billing/selectDateRange.tsx
frontend/providers/costcenter/src/pages/_app.tsx
frontend/providers/costcenter/src/pages/billing/index.tsx

fix(costcenter):fix rerender when select date

---

frontend/desktop/src/components/desktop_content/index.tsx
frontend/desktop/src/components/more_apps/index.tsx

Disable desktop app draggable.

---

frontend/providers/cronjob/public/locales/en/common.json

This pull request is to address the UI bug for inconsistent translation in CronJob "Deploy" button. The detailed description for this UI bug is in issue #4568 .

fix: Add "Deploy" translation key to English locale

---

frontend/desktop/package.json
frontend/desktop/src/components/signin/auth/useSms.tsx
frontend/desktop/src/components/signin/index.tsx
frontend/desktop/src/pages/api/auth/phone/sms.ts
frontend/desktop/src/pages/api/platform/getEnv.ts
frontend/desktop/src/stores/global.ts
frontend/desktop/src/types/system.ts
frontend/pnpm-lock.yaml

fix(desktop):add cloudflare turnstile

---

frontend/pnpm-lock.yaml
frontend/providers/template/next.config.js
frontend/providers/template/package.json
frontend/providers/template/src/components/Banner/index.tsx
frontend/providers/template/src/components/YamlCode/hljs.ts
frontend/providers/template/src/components/YamlCode/index.module.scss
frontend/providers/template/src/components/YamlCode/index.tsx
frontend/providers/template/src/components/layout/sidebar.tsx
frontend/providers/template/src/pages/_app.tsx
frontend/providers/template/src/pages/deploy/components/Yaml.tsx
frontend/providers/template/src/pages/deploy/index.tsx
frontend/providers/template/src/pages/develop/components/YamlList.tsx
frontend/providers/template/src/pages/index.tsx
frontend/providers/template/src/services/backend/kubernetes.ts
frontend/providers/template/src/store/session.ts

feat:Improve App Store rendering speed

---

controllers/account/deploy/manifests/deploy.yaml.tmpl
controllers/admission/deploy/manifests/deploy.yaml.tmpl
controllers/app/deploy/manifests/deploy.yaml
controllers/db/adminer/deploy/manifests/deploy.yaml.tmpl
controllers/objectstorage/deploy/manifests/deploy.yaml.tmpl
controllers/terminal/deploy/manifests/deploy.yaml.tmpl
controllers/user/deploy/manifests/deploy.yaml.tmpl
frontend/desktop/deploy/manifests/deploy.yaml.tmpl
frontend/providers/adminer/deploy/manifests/deploy.yaml
frontend/providers/applaunchpad/deploy/manifests/deploy.yaml.tmpl
frontend/providers/costcenter/deploy/manifests/deploy.yaml.tmpl
frontend/providers/cronjob/deploy/manifests/deploy.yaml.tmpl
frontend/providers/dbprovider/deploy/manifests/deploy.yaml.tmpl
frontend/providers/kubepanel/deploy/manifests/deploy.yaml.tmpl
frontend/providers/license/deploy/manifests/deploy.yaml.tmpl
frontend/providers/objectstorage/deploy/manifests/deploy.yaml.tmpl
frontend/providers/template/deploy/manifests/deploy.yaml.tmpl
frontend/providers/terminal/deploy/manifests/deploy.yaml.tmpl

chore: add podAntiAffinity for desktop and some providers.

---

controllers/job/init/internal/util/database/user.go
controllers/pkg/database/cockroach/accountv2.go
controllers/pkg/types/global.go

The init job waits for the user table to be created before execution.

---

controllers/account/api/v1/debt_webhook.go
controllers/account/controllers/debt_controller.go
controllers/job/init/internal/util/database/types.go
controllers/job/init/internal/util/database/user.go
controllers/pkg/database/cockroach/accountv2.go
controllers/pkg/database/interface.go
controllers/pkg/types/global.go

add init job

---

deploy/cloud/scripts/init.sh
scripts/cloud/build-offline-tar.sh
scripts/cloud/install.sh

chore: update other component version in sealos cloud.

---

controllers/account/controllers/account_controller.go
controllers/account/controllers/account_controller_test.go
controllers/account/main.go
controllers/pkg/database/cockroach/accountv2.go
controllers/pkg/database/interface.go
controllers/pkg/database/mongo/account.go
controllers/pkg/database/mongo/cvm.go
controllers/pkg/resources/resources.go
controllers/pkg/types/cvm.go
controllers/pkg/utils/env/env.go

Feat: Cloud Virtual Machine Billing

---

controllers/pkg/objectstorage/metric_parser.go
controllers/pkg/objectstorage/objectstorage.go
controllers/pkg/objectstorage/objectstorage_test.go
controllers/resources/controllers/monitor_controller.go
controllers/resources/main.go

fix object storage monitor

---

pkg/checker/host_checker.go

Check whether the containerd is installed. fix #4738

fix:add check containerd

---

pkg/checker/cluster_checker.go

fix control-plane component status checker.
```
....
Error: failed to run checker: pods "kube-apiserver-test2.novalocal" not found
```

fix control-plane component status

---

docs/4.0/docs/guides/objectstorage/install.md
docs/4.0/docs/guides/objectstorage/uninstall.md
docs/4.0/i18n/zh-Hans/guides/objectstorage/install.md
docs/4.0/i18n/zh-Hans/guides/objectstorage/uninstall.md

doc: add a doc for deploying Object Storage

---

frontend/providers/template/src/pages/api/updateRepo.ts
frontend/providers/template/src/pages/deploy/components/Form.tsx

fix:template frontend leaves zombie git processes

---

.goreleaser.yml

[deprecated rlcp](https://github.com/goreleaser/goreleaser/blob/main/www/docs/deprecations.md#archivesrlcp)
Fix:
```
error=yaml: unmarshal errors:
line 245: field rlcp not found in type config.Archive
```

Fix: remove deprecated rlcp options

---

pkg/apply/processor/create.go
pkg/apply/processor/scale.go
pkg/checker/host_checker.go

bugfix scale node error #4809 ;

fix: scaledown processor checker error

---

controllers/resources/controllers/monitor_controller.go
controllers/resources/main.go

feat: optimize resource monitoring logic, performance and fix nil pointer issue
This commit introduces several optimizations to the resource monitoring logic, improves its overall performance, and addresses a potential nil pointer issue with `ObjStorageClient`.
**Code Structure Improvements:**
- Refactored resource usage monitoring logic into dedicated functions for Pods, PVCs, backups, and Services, enhancing code readability and maintainability.
**Performance Enhancements:**
- Implemented `FieldSelector` in `monitorPodResourceUsage`, `monitorPVCResourceUsage`, and `monitorServiceResourceUsage` to filter resources efficiently, minimizing API request overhead.
- Introduced a `gpuMutex` to safeguard the `NvidiaGpu` map, preventing concurrent read-write issues and potential race conditions. …

feat: optimize resource monitoring logic, performance and fix nil pointer issue

---

docs/website/src/pages/self-hosting/advantage/index.tsx

This commit enhances the animation smoothness of the Akkordion component by using `max-height` instead of `height` for transitions and adding `overflow: hidden` to the content panel.
This ensures that the height of the expanding and collapsing sections changes smoothly without abrupt jumps, resulting in a more visually appealing user experience.
https://github.com/labring/sealos/assets/84728412/aa428907-757b-4aff-afbb-e30c8c20ca7b

feat: improve animation smoothness for expanding and collapsing sections

---

pkg/runtime/kubernetes/kubeadm.go
pkg/runtime/kubernetes/master.go
pkg/runtime/kubernetes/upgrade.go

fix: sealos 5 cannot upgrade k8s from v1.27.x to v1.28.y

---

frontend/providers/costcenter/public/locales/en/applist.json
frontend/providers/costcenter/public/locales/en/common.json
frontend/providers/costcenter/public/locales/zh/applist.json
frontend/providers/costcenter/public/locales/zh/common.json
frontend/providers/costcenter/src/components/billing/AppMenu.tsx
frontend/providers/costcenter/src/components/billing/SwitchPage.tsx
frontend/providers/costcenter/src/components/billing/TransferTabPnel.tsx
frontend/providers/costcenter/src/components/billing/TypeMenu.tsx
frontend/providers/costcenter/src/components/billing/billingTable.tsx
frontend/providers/costcenter/src/constants/billing.ts
frontend/providers/costcenter/src/layout/index.tsx
frontend/providers/costcenter/src/pages/api/account/transfer.ts
frontend/providers/costcenter/src/pages/api/billing/index.ts
frontend/providers/costcenter/src/pages/api/billing/transfer.ts
frontend/providers/costcenter/src/pages/billing/index.tsx
frontend/providers/costcenter/src/types/billing.ts

fix:fix transfer billing

---

pkg/runtime/kubernetes/upgrade.go

Fix #4113 
Test k8s-v1.26.8 upgrad to k8s-v1.27.11
Before upgrading
```
kubectl get nodes
NAME                   STATUS   ROLES           AGE    VERSION
test-1.novalocal   Ready    control-plane   2m5s   v1.26.8
test2.novalocal    Ready    control-plane   62s    v1.26.8
[root@lcx-test-1 ~]# kubeadm certs check-expiration
[check-expiration] Reading configuration from the cluster...
[check-expiration] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
W0710 18:10:37.225578   20471 utils.go:69] The recommended value for "healthzBindAddress" in "KubeletConfiguration" is: 127.0.0.1; the provided value is: 0.0.0.0
CERTIFICATE                EXPIRES                  RESIDUAL TIME   CERTIFICATE AUTHORITY   EXTERNALLY MANAGED
admin.conf …
```

fix: the certificate validity period changed from 99 years to 1 year after the cluster is upgraded

---

controllers/account/Makefile
controllers/job/init/Makefile
controllers/license/Makefile
controllers/objectstorage/Makefile
controllers/resources/Makefile
service/account/Makefile

fix: `flag provided but not defined: -w-X`

fix: concat ldflags str

---

frontend/desktop/public/locales/en/common.json
frontend/desktop/src/components/notification/index.tsx
frontend/providers/applaunchpad/src/pages/api/guide/getAccount.ts
frontend/providers/applaunchpad/src/pages/api/guide/getBonus.ts
frontend/providers/applaunchpad/src/pages/api/guide/updateGuide.ts
frontend/providers/dbprovider/public/locales/en/common.json
frontend/providers/dbprovider/public/locales/zh/common.json
frontend/providers/workorder/src/pages/api/cronjob/init.ts
frontend/providers/workorder/src/pages/api/workorder/check.ts

update:dbprovider Pause Hint message

---

.gitignore
frontend/.gitignore
frontend/i18n.md

feat: Update .gitignore file and i18n.md doc

---

controllers/objectstorage/config/crd/bases/objectstorage.sealos.io_objectstoragebuckets.yaml
controllers/objectstorage/config/crd/bases/objectstorage.sealos.io_objectstorageusers.yaml
controllers/objectstorage/config/rbac/role.yaml
controllers/objectstorage/controllers/objectstoragebucket_controller.go
controllers/objectstorage/controllers/objectstorageuser_controller.go
controllers/pkg/resources/resources.go

feat: resource quota add object storage size

---

controllers/account/controllers/utils/email.go
controllers/account/go.mod
controllers/account/go.sum

rollback email package

---

frontend/providers/applaunchpad/src/pages/app/edit/index.tsx
frontend/providers/applaunchpad/src/types/app.d.ts
frontend/providers/applaunchpad/src/utils/adapt.ts
frontend/providers/applaunchpad/src/utils/tools.ts

Fix: Resolve bug introduced by launchpad JSON patching

---

scripts/cloud/install.sh

add function to check  control plane count of master IPs in scripts/cloud/install.sh

fix: check control plane count of master IPs in install.sh

---

docs/website/src/hooks/useWindow.ts
docs/website/src/pages/components/Capability/index.tsx
docs/website/src/pages/components/Header/index.tsx
docs/website/src/pages/index.tsx
docs/website/src/pages/self-hosting/header/index.tsx
docs/website/src/pages/self-hosting/index.tsx
docs/website/src/pages/self-hosting/product/index.tsx

feat(docs): add SEM keywords parameter

---

frontend/desktop/src/api/platform.ts
frontend/desktop/src/components/signin/index.tsx
frontend/desktop/src/pages/api/platform/getAuthConfig.ts
frontend/desktop/src/pages/index.tsx
frontend/desktop/src/types/system.ts
frontend/desktop/src/utils/sessionConfig.ts
frontend/providers/applaunchpad/src/pages/_app.tsx
frontend/providers/applaunchpad/src/pages/app/edit/index.tsx
frontend/providers/applaunchpad/src/types/app.d.ts

feat: add support for launching creation page in launchpad

---

frontend/desktop/src/components/AppDock/index.tsx
frontend/desktop/src/stores/app.ts
frontend/desktop/src/stores/desktopConfig.ts
frontend/providers/dbprovider/src/pages/db/edit/components/Form.tsx

feat(desktop): Implement smart dock behavior

---

controllers/devbox/internal/controller/devbox_controller.go
controllers/devbox/internal/controller/helper/devbox.go

add logs for CheckPodConsistency.

---

controllers/devbox/api/v1alpha1/devbox_types.go
controllers/devbox/config/crd/bases/devbox.sealos.io_devboxes.yaml
controllers/devbox/deploy/manifests/deploy.yaml.tmpl
controllers/devbox/internal/controller/devbox_controller.go

add devbox node and containerId

---

controllers/devbox/api/v1alpha1/devboxrelease_types.go
controllers/devbox/config/crd/bases/devbox.sealos.io_devboxreleases.yaml
controllers/devbox/deploy/manifests/deploy.yaml.tmpl
controllers/devbox/internal/controller/devboxrelease_controller.go

add release old tag

---

controllers/account/api/v1/debt_webhook.go
controllers/account/controllers/billing_controller.go

fix webhook

---

frontend/providers/applaunchpad/src/api/platform.ts
frontend/providers/applaunchpad/src/pages/api/platform/checkPermission.ts
frontend/providers/applaunchpad/src/pages/app/edit/index.tsx

fix:launchpad resource update in checkPermission API

---

frontend/Dockerfile
frontend/providers/applaunchpad/src/constants/editApp.ts
frontend/providers/applaunchpad/src/mock/apps.ts
frontend/providers/applaunchpad/src/pages/_app.tsx
frontend/providers/applaunchpad/src/pages/app/edit/components/Form.tsx
frontend/providers/applaunchpad/src/pages/app/edit/index.tsx
frontend/providers/applaunchpad/src/types/app.d.ts

feat: launchpad implement URL query to form data conversion

---

go.mod
pkg/utils/confirm/confirm.go

chore: add hostname for reset confirm.

---

pkg/apply/applydrivers/apply_drivers_default.go

fix #4869 
when delete node via `seaos apply -f Clusterfile`, the target node will not exist in the Clusterfile, in that case, if the node has a different passwd with other nodes, the scale down process will failed.
my solution is passing the 'current' clusterfile when `NewScaleProcessor`, it will not affect the `sealos add` and `sealos delete` because the `add` and `delete` processes pass current clusterfile originally. It will only affect the `sealos apply` when it comes scale process.

fix: failed to delete node by apply

---

frontend/desktop/public/locales/en/common.json
frontend/desktop/public/locales/zh/common.json
frontend/desktop/src/components/account/AccountCenter/AuthModifyList.tsx
frontend/desktop/src/components/account/AccountCenter/index.tsx
frontend/desktop/src/components/signin/auth/AuthList.tsx
frontend/desktop/src/components/signin/auth/useProtocol.tsx
frontend/desktop/src/components/signin/index.tsx
frontend/desktop/src/pages/api/auth/email/bind/verify.ts
frontend/desktop/src/pages/api/auth/email/changeBinding/newSms.ts
frontend/desktop/src/pages/api/auth/email/changeBinding/oldSms.ts
frontend/desktop/src/pages/api/auth/email/changeBinding/verifyNew.ts
frontend/desktop/src/pages/api/auth/email/changeBinding/verifyOld.ts
frontend/desktop/src/pages/api/auth/email/unbind/sms.ts
frontend/desktop/src/pages/api/auth/email/unbind/verify.ts
frontend/desktop/src/pages/api/auth/info.ts
frontend/desktop/src/pages/api/auth/phone/bind/sms.ts
frontend/desktop/src/pages/api/auth/phone/bind/verify.ts
frontend/desktop/src/pages/api/auth/phone/changeBinding/newSms.ts
frontend/desktop/src/pages/api/auth/phone/changeBinding/oldSms.ts
frontend/desktop/src/pages/api/auth/phone/changeBinding/verifyNew.ts
frontend/desktop/src/pages/api/auth/phone/changeBinding/verifyOld.ts
frontend/desktop/src/pages/api/auth/phone/sms.ts
frontend/desktop/src/pages/api/auth/phone/unbind/sms.ts
frontend/desktop/src/pages/api/auth/phone/unbind/verify.ts
frontend/desktop/src/pages/api/auth/phone/verify.ts
frontend/desktop/src/pages/api/platform/getAuthConfig.ts
frontend/desktop/src/services/enable.ts
frontend/desktop/src/types/system.ts

fix invaild

---

.github/workflows/cloud-release.yml

 ci: cloud release add skip releases.

---

docs/5.0/docs/developer-guide/lifecycle-management/lifecycle-management.md
docs/5.0/docs/developer-guide/lifecycle-management/quick-start/deploy-kubernetes.md
docs/5.0/docs/developer-guide/lifecycle-management/reference/sealos/commands/apply.md
docs/5.0/docs/developer-guide/lifecycle-management/reference/sealos/commands/build.md
docs/5.0/docs/developer-guide/lifecycle-management/reference/sealos/commands/commands.md
docs/5.0/docs/developer-guide/lifecycle-management/reference/sealos/commands/gen.md
docs/5.0/docs/developer-guide/lifecycle-management/reference/sealos/commands/manifest.md
docs/5.0/docs/developer-guide/lifecycle-management/reference/sealos/commands/run.md
docs/5.0/docs/developer-guide/lifecycle-management/reference/sealos/sealos.md
docs/5.0/docs/developer-guide/sealos/installation.md
docs/5.0/i18n/zh-Hans/developer-guide/lifecycle-management/lifecycle-management.md
docs/5.0/i18n/zh-Hans/developer-guide/lifecycle-management/quick-start/deploy-kubernetes.md
docs/5.0/i18n/zh-Hans/developer-guide/lifecycle-management/quick-start/install-cli.md
docs/5.0/i18n/zh-Hans/developer-guide/lifecycle-management/reference/sealos/commands/apply.md
docs/5.0/i18n/zh-Hans/developer-guide/lifecycle-management/reference/sealos/commands/build.md
docs/5.0/i18n/zh-Hans/developer-guide/lifecycle-management/reference/sealos/commands/commands.md
docs/5.0/i18n/zh-Hans/developer-guide/lifecycle-management/reference/sealos/commands/gen.md
docs/5.0/i18n/zh-Hans/developer-guide/lifecycle-management/reference/sealos/commands/manifest.md
docs/5.0/i18n/zh-Hans/developer-guide/lifecycle-management/reference/sealos/commands/run.md
docs/5.0/i18n/zh-Hans/developer-guide/lifecycle-management/reference/sealos/sealos.md
docs/5.0/i18n/zh-Hans/developer-guide/sealos/installation.md

5.0文档目录self-hosting改为了developer-guide，更新一下文档内跳转链接。

docs: update links

---

frontend/providers/dbprovider/src/pages/api/platform/resourcePrice.ts
frontend/providers/dbprovider/src/types/user.d.ts

Modify the dbprovider cost estimate obtained through the account service

---

controllers/account/controllers/payment_controller.go

fix the payment controller start error

---

controllers/account/config/rbac/role.yaml
controllers/account/controllers/account_controller.go
controllers/account/deploy/manifests/deploy.yaml

fix the init job to create user permissions

---

cmd/sealos/cmd/reset.go
pkg/apply/args.go
pkg/apply/args_test.go
pkg/apply/reset.go
pkg/apply/reset_test.go

Remove --masters and --nodes options for command `sealos reset`.
There is no need to provide the masters and nodes options to the `reset` command, because even if you specify master or node, the `reset` command will still reset all hosts in the entire cluster.
At the same time, it is necessary to force a check on whether the Clusterfile exists. When it does not exist, an error is reported and the  process exits.

opt: remove --masters and --nodes options for reset

---

controllers/devbox/cmd/main.go
controllers/devbox/internal/controller/devbox_controller.go
controllers/devbox/internal/controller/helper/devbox.go

Update devbox controller, add support init request ephemeral storage.

---

frontend/providers/template/src/pages/api/resource/delJob.ts
frontend/providers/workorder/public/locales/en/common.json
frontend/providers/workorder/public/locales/zh/common.json
frontend/providers/workorder/src/pages/workorder/detail/components/AppBaseInfo.tsx
frontend/providers/workorder/src/pages/workorder/detail/components/AppMainInfo.tsx
frontend/providers/workorder/src/pages/workorder/detail/components/Header.tsx
frontend/providers/workorder/src/pages/workorder/detail/index.tsx
frontend/providers/workorder/src/pages/workorders/index.tsx

fix:workorder overflow issue

---

controllers/user/Makefile
controllers/user/api/v1/deleterequest_types.go
controllers/user/api/v1/operationrequest_types.go
controllers/user/config/crd/bases/user.sealos.io_deleterequests.yaml
controllers/user/config/crd/bases/user.sealos.io_operationrequests.yaml
controllers/user/config/crd/bases/user.sealos.io_users.yaml
controllers/user/config/rbac/role.yaml
controllers/user/config/webhook/manifests.yaml
controllers/user/controllers/operationrequest_controller.go
controllers/user/deploy/manifests/deploy.yaml.tmpl
controllers/user/main.go

operationrequest cr change to the user-system

---

service/account/api/api.go

fix GetRealNameInfoReq

---

docs/website/docusaurus.config.js
docs/website/src/pages/index.tsx

docs: Update docs scripts

---

controllers/devbox/internal/controller/devbox_controller.go
controllers/devbox/internal/controller/helper/devbox.go

feat: change devbox to stop if exceeded quota

---

controllers/account/go.mod
controllers/job/init/go.mod
controllers/license/go.mod
controllers/objectstorage/controllers/objectstorageuser_controller.go
controllers/pkg/go.mod
controllers/pkg/go.sum
controllers/resources/go.mod
service/account/go.mod

Optimize the unit display of resourcequota of used.objectstorage/size

---

controllers/devbox/cmd/main.go
controllers/devbox/internal/controller/devbox_controller.go
controllers/devbox/internal/controller/helper/devbox.go

Update controller, allow set different cpu/memory request rate.

---

pkg/runtime/kubernetes/kubeadm.go

使用部署时指定的主机地址作为集群internal IP，可以避免在多网卡的环境中，自动识别到错误的网卡。
#2465
#2594

feat: specify the host IP as the k8s internal IP

---

frontend/providers/costcenter/src/components/RechargeModal.tsx
frontend/providers/costcenter/src/components/billing/BillingLineChart.tsx
frontend/providers/costcenter/src/components/cost_overview/components/barChart.tsx
frontend/providers/costcenter/src/components/cost_overview/components/lineChart.tsx
frontend/providers/costcenter/src/pages/api/billing/costs.ts
frontend/providers/costcenter/src/pages/valuation/index.tsx

fix(costcenter):low version can use

---

frontend/desktop/public/locales/en/common.json
frontend/desktop/public/locales/zh/common.json
frontend/desktop/src/components/desktop_content/index.tsx
frontend/desktop/src/components/desktop_content/serviceButton.tsx
frontend/desktop/src/components/task/useDriver.tsx
frontend/desktop/src/pages/WorkspaceInvite.tsx
frontend/desktop/src/stores/desktopConfig.ts
frontend/desktop/src/types/system.ts
frontend/providers/applaunchpad/public/locales/en/common.json
frontend/providers/applaunchpad/public/locales/zh/common.json
frontend/providers/applaunchpad/src/hooks/useDetailDriver.tsx
frontend/providers/applaunchpad/src/hooks/useDriver.tsx
frontend/providers/applaunchpad/src/pages/api/guide/getTasks.ts
frontend/providers/dbprovider/public/locales/zh/common.json
frontend/providers/dbprovider/src/hooks/useDetailDriver.tsx
frontend/providers/dbprovider/src/hooks/useDriver.tsx
frontend/providers/dbprovider/src/pages/db/edit/index.tsx
frontend/providers/template/src/utils/json-yaml.ts

feat: optimize user task and support customer service config

---

service/exceptionmonitor/helper/monitor/database_monitor.go

filter repeat alarm

---

frontend/providers/applaunchpad/src/api/app.ts
frontend/providers/applaunchpad/src/pages/api/getAppPodsByAppName.ts
frontend/providers/applaunchpad/src/pages/app/edit/index.tsx
frontend/providers/dbprovider/public/locales/en/common.json
frontend/providers/dbprovider/public/locales/zh/common.json
frontend/providers/dbprovider/src/api/backup.ts
frontend/providers/dbprovider/src/api/db.ts
frontend/providers/dbprovider/src/pages/api/createDB.ts
frontend/providers/dbprovider/src/pages/api/getStatefulSetByName.ts
frontend/providers/dbprovider/src/pages/api/pauseDBByName.ts
frontend/providers/dbprovider/src/pages/api/pod/getPodsByDBName.ts
frontend/providers/dbprovider/src/pages/api/startDBByName.ts
frontend/providers/dbprovider/src/pages/db/detail/components/AppBaseInfo.tsx
frontend/providers/dbprovider/src/pages/db/edit/components/Form.tsx
frontend/providers/dbprovider/src/pages/db/edit/index.tsx
frontend/providers/dbprovider/src/utils/json2Yaml.ts

feat: optimize database pause and backup handling

---

frontend/desktop/next-i18next.config.js
frontend/providers/applaunchpad/src/constants/editApp.ts
frontend/providers/applaunchpad/src/mock/apps.ts
frontend/providers/applaunchpad/src/pages/_app.tsx
frontend/providers/applaunchpad/src/pages/app/edit/components/Header.tsx
frontend/providers/applaunchpad/src/pages/app/edit/index.tsx
frontend/providers/applaunchpad/src/pages/redirect.tsx
frontend/providers/applaunchpad/src/types/app.d.ts
frontend/providers/applaunchpad/src/utils/adapt.ts
frontend/providers/applaunchpad/src/utils/deployYaml2Json.ts

feat:optimize launchpad unify redirect handling

---

.github/workflows/ci-patch-image.yml
.github/workflows/cloud-release.yml
.github/workflows/cloud.yml
.github/workflows/controllers.yml
.github/workflows/e2e_k3s_multi_node.yml
.github/workflows/e2e_k8s_multi_node.yml
.github/workflows/e2e_test_core.yml
.github/workflows/e2e_test_core_k3s.yml
.github/workflows/e2e_test_image_cri_shim.yml
.github/workflows/frontend.yml
.github/workflows/import-patch-image.yml
.github/workflows/import-save-sealos.yml
.github/workflows/objectstorage.yaml
.github/workflows/services.yml

v3 of `actions/upload-artifact` and `actions/download-artifact` will be fully deprecated by **30 January 2025**. Jobs that are scheduled to run during the brownout periods will also fail. See:
1. https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
2. https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/

ci: update `upload-artifact` and `download-artifact` actions to v4

---

frontend/providers/devbox/app/[lang]/(platform)/(home)/components/DevboxList.tsx
frontend/providers/devbox/app/[lang]/(platform)/devbox/detail/[name]/components/BasicInfo.tsx
frontend/providers/devbox/app/[lang]/(platform)/devbox/detail/[name]/components/Header.tsx
frontend/providers/devbox/app/[lang]/(platform)/devbox/detail/[name]/components/Version.tsx
frontend/providers/devbox/components/modals/DelModal.tsx

fix: version refresh bug

---

controllers/objectstorage/deploy/manifests/deploy.yaml.tmpl

fix: update clusterrole

---

extensions/ide/vscode/devbox/CHANGELOG.md
extensions/ide/vscode/devbox/package.json
extensions/ide/vscode/devbox/src/utils/file.ts

fix: some users everyone authority bug

---

frontend/providers/costcenter/src/components/table/PriceTable.tsx
frontend/providers/costcenter/src/components/valuation/PriceTablePanel.tsx
frontend/providers/costcenter/src/pages/valuation/index.tsx
frontend/providers/costcenter/src/types/valuation.ts

fix(costcneter):fix gpu price alias

---

frontend/providers/cronjob/src/api/app.ts
frontend/providers/cronjob/src/constants/job.ts
frontend/providers/cronjob/src/pages/api/launchpad/getApps.ts
frontend/providers/cronjob/src/pages/job/detail/components/AppMainInfo.tsx
frontend/providers/cronjob/src/pages/job/edit/components/Form.tsx
frontend/providers/cronjob/src/types/app.d.ts
frontend/providers/cronjob/src/types/job.d.ts
frontend/providers/cronjob/src/utils/adapt.ts
frontend/providers/cronjob/src/utils/json2Yaml.ts
frontend/providers/template/src/pages/deploy/components/ReadMe.tsx
frontend/providers/template/src/pages/deploy/index.tsx

feat: cronjob sts && template readme

---

controllers/devbox/api/v1alpha1/devbox_types.go
controllers/devbox/api/v1alpha1/zz_generated.deepcopy.go
controllers/devbox/config/crd/bases/devbox.sealos.io_devboxes.yaml
controllers/devbox/internal/controller/devbox_controller.go
controllers/devbox/internal/controller/helper/devbox.go

step1: copy runtime config to devbox crd, add template id.

---

controllers/pkg/database/cockroach/accountv2.go
controllers/pkg/types/global.go
service/account/api/api.go
service/account/dao/init.go
service/account/dao/interface.go
service/account/dao/interface_test.go

chore(account-service): add enterprise real name info inquiry

---

frontend/desktop/src/pages/api/account/enterpriseRealName.ts
frontend/desktop/src/pages/api/account/faceIdRealNameAuthCallback.ts

feat(desktop): Add real-name restrictions

---

frontend/desktop/package.json
frontend/desktop/src/components/signin/Captcha/index.tsx
frontend/desktop/src/components/signin/auth/useSms.tsx
frontend/desktop/src/components/signin/index.tsx
frontend/desktop/src/pages/api/auth/phone/sms.ts
frontend/desktop/src/pages/api/platform/getAppConfig.ts
frontend/desktop/src/pages/api/platform/getAuthConfig.ts
frontend/desktop/src/pages/signin.tsx
frontend/desktop/src/services/backend/middleware/sms.ts
frontend/desktop/src/services/backend/sms.ts
frontend/desktop/src/services/backend/svc/sms.ts
frontend/desktop/src/stores/script.ts
frontend/desktop/src/types/system.ts
frontend/pnpm-lock.yaml

feat:add captcha

---

deploy/admin/Kubefile
deploy/admin/init.sh
deploy/admin/scripts/init.sh
deploy/cloud/manifests/sealos-config.yaml
deploy/cloud/scripts/init.sh

feat: add a config when deploy sealos cloud in sealos-system

---

.github/labeler.yml

Due to the move of the lifecycle directory, the CI labeler needs to be updated.

Fix the CI labeler to correctly tag PRs

---

docs/4.0/docs/self-hosting/lifecycle-management/advanced-guide/image-build-standardized.md
docs/4.0/i18n/zh-Hans/self-hosting/lifecycle-management/advanced-guide/image-build-standardized.md
docs/5.0/docs/developer-guide/lifecycle-management/advanced-guide/image-build-standardized.md
docs/5.0/i18n/zh-Hans/developer-guide/lifecycle-management/advanced-guide/image-build-standardized.md

文档中registryPort字段应为：“默认镜像仓库的端口”，不应该是“默认镜像仓库的密码”

fix: 文档字段描述有误

---

.github/workflows/e2e_test_core.yml
lifecycle/pkg/runtime/kubernetes/master.go
lifecycle/test/e2e/k8s_129_test.go
lifecycle/test/e2e/k8s_130_test.go
lifecycle/test/e2e/k8s_131_test.go
lifecycle/test/e2e/k8s_132_test.go
lifecycle/test/e2e/k8s_docker_129_test.go
lifecycle/test/e2e/k8s_docker_130_test.go
lifecycle/test/e2e/k8s_docker_131_test.go
lifecycle/test/e2e/k8s_docker_132_test.go

This pull request introduces updates to the `sealos` project, including enhancements to Kubernetes image pulling logic, the addition of new E2E test cases for Kubernetes versions, and improvements to code structure. Below is a summary of the most important changes:
* Refactored the `imagePull` method in `lifecycle/pkg/runtime/kubernetes/master.go` to dynamically fetch and modify Kubernetes image lists before pulling them. This includes parsing image lists in JSON format, replacing registry domains, and using `crictl` for pulling images.
* Introduced new imports for handling JSON parsing and registry domain management, such as `k8s.io/apimachinery/pkg/util/json` and `github.com/labring/sreg/pkg/registry/crane`.
* Added E2E test cases for Kubernetes versions `v1.29.0`, `v1.30.0`, `v1.31.0`, …

fix(main): validate kubeadm config files before pulling images

---

.github/workflows/cloud-release.yml
.github/workflows/cloud.yml
.github/workflows/controllers.yml
.github/workflows/frontend.yml
.github/workflows/release.yml
.github/workflows/services.yml
scripts/resolve-tag-image.sh

What Changes:
1. Added `GHCR_TOKEN` secret to enable personal repository CI to run properly. This secret should be set to a [pat](https://github.com/settings/tokens) with `write:package` permission. Note that this PAT should only be configured in the personal fork of the sealos repository, not in the organization, to avoid PAT leakage. Furthermore, this PAT is only used for logging into ghcr.io within the workflow and will not be used elsewhere, minimizing the risk of leakage
2. Fixed the issue where a fixed PR reviewer in `peter-evans/create-pull-request@v5` caused CI to fail in forked repositories 
3. Added ACR image push support for `sealos cloud`, `controller`, `service`, and `frontend`
4. Fixed `resolve-tag-image.sh` defaulting to using sha instead of latest
5. sha tag add `sha-` …

feat: push image to acr

---

lifecycle/scripts/make-rules/license.mk
lifecycle/staging/src/github.com/labring/image-cri-shim/.github/workflows/close-pr.yml
lifecycle/staging/src/github.com/labring/image-cri-shim/README.md
lifecycle/staging/src/github.com/labring/lvscare/.github/workflows/close-pr.yml
lifecycle/staging/src/github.com/labring/lvscare/README.md

This pull request introduces changes to enforce a strict no-contributions policy across multiple repositories (`image-cri-shim` and `lvscare`). It includes both workflow automation to close pull requests and updates to documentation to clarify the policy.
* Added a GitHub Actions workflow (`close-pr.yml`) in both `image-cri-shim` and `lvscare` repositories to automatically close any pull requests with a predefined comment stating that contributions are not accepted. [[1]](diffhunk://#diff-7f817f350a37ad638d0fb2918511b0e5586154556ec5ebb9095c2c10c4408a4fR1-R20) [[2]](diffhunk://#diff-7f817f350a37ad638d0fb2918511b0e5586154556ec5ebb9095c2c10c4408a4fR1-R20)
* Updated `README.md` files in `image-cri-shim` and `lvscare` repositories to include a "Contribution Policy" section. This section …

docs: update contribution policy and guidelines in README

---

.github/workflows/ci-patch-image.yml

This pull request updates the `.github/workflows/ci-patch-image.yml` file to improve flexibility by introducing a `PROJECT_PATH` environment variable. This change centralizes the project directory path, reducing hardcoded values and improving maintainability.
* Added a new `PROJECT_PATH` environment variable (`./lifecycle`) to the workflow's environment configuration, enabling dynamic path management. (`[.github/workflows/ci-patch-image.ymlR7](diffhunk://#diff-32e7e1062e41bfef162eb5aa471d42365df677ace95527c7ce0cdf492a4a40faR7)`)
* Updated artifact download paths to use the `PROJECT_PATH` variable, replacing hardcoded paths for `sealos-amd64` and `sealos-arm64` binaries. (`[.github/workflows/ci-patch-image.ymlL76-R90](diffhunk://#diff-32e7e1062e41bfef162eb5aa471d42365df677ace95527c7ce0cdf49 …

fix(ci): update paths to use PROJECT_PATH variable in ci-patch-image.yml

---

.github/workflows/ci-patch-image.yml

This pull request updates the `.github/workflows/ci-patch-image.yml` file to enhance permissions and fix a script path issue. The key changes focus on ensuring proper access for GitHub Actions and resolving a relative path inconsistency in a script call.
* Added `contents: write` and `packages: write` permissions to the `container-sealos` job.
* Added `contents: write` and `packages: write` permissions to another job requiring these access levels.
* Added `contents: write` and `packages: write` permissions to the `save-sealos` job.
* Updated the script path in the `manifest-cluster-images.sh` command to use a relative path (`./scripts/manifest-cluster-images.sh`) instead of an environment variable-based path.

fix(ci): update permissions and script path in ci-patch-image.yml

---

frontend/providers/applaunchpad/src/store/app.ts

Now: show error state when all pods are terminated.

fix(launchpad): app error state not correctly shown

---

.github/sync_code.yml

This pull request updates the `.github/sync_code.yml` configuration to use `LICENSE.md` files instead of `LICENSE` for both the `labring/lvscare` and `labring/image-cri-shim` repositories.
Configuration updates:
* Changed the license file references from `LICENSE` to `LICENSE.md` for both `labring/lvscare` and `labring/image-cri-shim` in `.github/sync_code.yml`.

fix(sync): update LICENSE file references to LICENSE.md in sync_code.yml

---

.github/workflows/new_version_dispatch.yml

This pull request introduces a new GitHub Actions workflow that automates the process of updating the `tagpr` configuration for releases. The workflow allows triggering a configuration update via the GitHub UI, generates a new `.tagpr.json` file based on input versions, and creates a pull request with the changes.
**New automated release workflow:**
* Added `.github/workflows/new_version_dispatch.yml` to enable manual triggering of a workflow that updates the `.tagpr.json` file with new release version information and automates the creation of a corresponding pull request.

feat(ci): add automated workflow for updating tagpr configuration

---

.github/workflows/new_version_dispatch.yml
.github/workflows/tagpr.yml

This pull request updates the configuration for the TagPR GitHub workflow to use a new bot identity and authentication tokens. The changes improve security and attribution by switching from the default GitHub Actions bot to a custom bot and using more flexible token options.
Authentication and bot identity updates:
* [`.github/workflows/tagpr.yml`](diffhunk://#diff-ffc7eb13f2d4fb8a7c238f2f81c30c7b932ba8582616312295a6b4c15a6ad83eL58-R60): Changed the authentication token from `GITHUB_TOKEN` to use either `GHCR_TOKEN` or `GH_CI_PAT`, and updated the `committer` and `author` fields to use the `sealos-ci-robot` identity instead of `github-actions[bot]`.

fix(ci): update GitHub Actions token and committer information in tagpr.yml

---

.github/workflows/tagpr.yml

This pull request makes a minor update to the GitHub Actions workflow configuration. The main change is enabling tag fetching during the repository checkout step, which can help workflows that rely on git tags.
* Workflow configuration: Added `fetch-tags: true` to the `actions/checkout@v4` step in `.github/workflows/tagpr.yml` to ensure all tags are fetched during CI runs.

fix(ci): enable fetching tags in GitHub Actions workflow for changelog generation

---

.github/workflows/check-pr-title-lint-semantic.yml
.github/workflows/new_version_dispatch.yml
.github/workflows/tagpr.yml

This pull request introduces a new GitHub Actions workflow to enforce semantic pull request titles. The workflow checks that PR titles follow a conventional commit format and ensures consistency across contributions.
Continuous integration and linting:
* Added a `.github/workflows/pr-lint-semantic.yml` workflow that uses the `amannn/action-semantic-pull-request` GitHub Action to validate that pull request titles follow semantic conventions, including commit type and subject formatting.

feat(pr-lint): add workflow for linting pull request titles

---

.github/workflows/check-pr-title-lint-semantic.yml

This pull request updates the GitHub Actions workflow for semantic PR title checks, improving both validation and user feedback. The changes modernize the workflow configuration, enhance error messaging for contributors, and ensure that outdated error comments are removed automatically.
**Workflow configuration improvements:**
* Renamed the workflow from `'Lint PR title semantic'` to `'Check PR title semantic'` for clarity and updated the job name to `'Validate PR title'`. The runner was changed from `ubuntu-22.04` to `ubuntu-latest`, and the permissions now include `statuses: write` for better status reporting.
* Refactored the workflow to use the latest recommended configuration for `amannn/action-semantic-pull-request@v5`, including moving the `id` to the step, and reorganizing …

feat(pr-lint): update workflow to validate pull request titles against semantic rules

---

.github/workflows/cloud-release.yml
.github/workflows/controllers.yml
.github/workflows/frontends.yml
.github/workflows/release.yml
.github/workflows/services.yml
.github/workflows/tagpr.yml
deploy/cloud/init.sh

This pull request updates several GitHub Actions workflow files and a deployment script to improve workflow triggering, permissions, and reliability. The main focus is on simplifying workflow calls by replacing `workflow_call` triggers with explicit dispatches via `github-script`, standardizing permissions, and making the image pull process in deployment more robust.
**GitHub Actions workflow improvements:**
* Replaced `workflow_call` triggers with explicit `workflow_dispatch` and now use `actions/github-script` to programmatically trigger dependent workflows (`cloud-release.yml`, `controllers.yml`, `frontends.yml`, `services.yml`) with the correct input parameters and tags. This change improves workflow traceability and flexibility. …

fix(ci): fix cloud release version

---

frontend/providers/dbprovider/src/api/platform.ts
frontend/providers/dbprovider/src/pages/api/minio/upload.ts
frontend/providers/dbprovider/src/pages/db/detail/components/DumpImport/index.tsx

When database migration fails, the error modal displays "have_error" instead of specific error details. The root cause is a 400 Bad Request error when trying to fetch logs due to incorrect container name being used.
1. **Added Pod Information Retrieval**: Implemented `getPodStatusByName` API call to fetch complete Pod information including container details
2. **Container Name Extraction**: Added logic to extract the correct container name from Pod spec
3. **Fixed Log Fetching**: Updated `getLogByNameAndContainerName` to use the actual container name instead of migration task name
4. **Enhanced Error Handling**: Improved error display with debugging information when logs cannot be retrieved
- **Added imports**: `getPodStatusByName` and `useMemo`
- **New query**: `getFullPodInfo` to fetch …

fix(dbprovider): resolve migration failure error display issue

---

.github/workflows/release.yml
scripts/changelog.sh

This pull request updates the release workflow to improve how release notes are managed and referenced. The main change is that the release process now uses the latest changelog file as release notes, and the changelog script ensures this file is always up to date.
**Release workflow improvements:**
* Updated the GoReleaser step in `.github/workflows/release.yml` to use `CHANGELOG/CHANGELOG-latest.md` for release notes instead of custom header and footer templates.
**Changelog management:**
* Modified `scripts/changelog.sh` to copy the changelog for the current tag to `CHANGELOG/CHANGELOG-latest.md`, ensuring the latest release notes are always available for the workflow.

fix(changelog): update release notes path in CI configuration and copy latest changelog

---

lifecycle/pkg/runtime/kubernetes/types/default_kubeadm_config.go

This pull request updates the default Kubernetes kubelet configuration in `default_kubeadm_config.go` to optimize performance and resource handling. The most significant changes are increased request and burst limits for events, API, and registry pulls, a lowered image GC threshold, and a change to parallelize image pulls.
**Performance and scaling improvements:**
* Increased `eventBurst` and `eventRecordQPS` values from 10/5 to 100/50 to allow higher event throughput.
* Increased `kubeAPIBurst` and `kubeAPIQPS` values from 10/5 to 100/50 for improved API request capacity.
* Increased `registryBurst` and `registryPullQPS` from 10/5 to 100/50 to support more concurrent image pulls.
**Resource management changes:**
* Lowered `imageGCHighThresholdPercent` from 85% to 80%, triggering garbage …

feat(kubeadm): increase event burst and QPS limits, adjust image GC thresholds

---

lifecycle/pkg/apply/applydrivers/apply_drivers_default.go
lifecycle/pkg/types/v1beta1/utils.go

This pull request introduces a small update to the cluster application driver logic, specifically targeting the handling of runtime components based on distribution type. The change ensures that components are only written back when the distribution is `k3s`, improving correctness for multi-distribution support.
Distribution-specific handling:
* Added import of the `k3s` distribution identifier from `github.com/labring/sealos/pkg/runtime/k3s` to enable distribution checks.
* Updated the `getWriteBackObjects` method in `apply_drivers_default.go` to append runtime components only if the cluster distribution is `k3s`, preventing unintended writes for other distributions.

feat(apply): conditionally append components based on distribution type

---

frontend/providers/devbox/deploy/manifests/deploy.yaml.tmpl
frontend/providers/devbox/deploy/manifests/job.yaml.tmpl

This pull request refactors how database migrations are handled during deployment for the devbox frontend. The main change is moving the migration logic from an init container within the deployment to a dedicated Kubernetes Job, improving separation of concerns and reliability.
**Deployment manifest changes:**
* Removed the `devbox-frontend-init` init container from the deployment manifest, which previously ran database initialization and migrations using a shell script.
**Database migration handling:**
* Added a new `prisma-migrate-deploy` Kubernetes Job manifest to run Prisma migrations separately, using the latest devbox frontend image and the provided `DATABASE_URL` environment variable.

fix(devbox): remove init container and add migration job for database deployment

---

frontend/providers/applaunchpad/deploy/manifests/deploy.yaml.tmpl
frontend/providers/devbox/deploy/manifests/deploy.yaml.tmpl

This pull request introduces a new environment variable configuration to the deployment manifests for both the `applaunchpad-frontend` and `devbox-frontend` containers. The change allows the value of `NODE_TLS_REJECT_UNAUTHORIZED` to be set via Helm templating, enabling more flexible control over Node.js TLS behavior in different deployment environments.
Environment variable configuration:
* Added support for setting the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable in the `applaunchpad-frontend` deployment manifest using a Helm template value.
* Added support for setting the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable in the `devbox-frontend` deployment manifest using a Helm template value.

feat(deploy): add NODE_TLS_REJECT_UNAUTHORIZED environment variable to frontend containers

---

service/hubble/deploy/manifests/deploy.yaml

fix(deploy): add namespace to cluster role binding in deploy manifest

---

lifecycle/pkg/env/env.go

sealos panics because of ****concurrent map read and map write*** when running multi applications.
Avoid map data races for env cache when getHostEnvInCache.

fix(lifecycle): Avoid map data races for env cache when getHostEnvInCache
