labring/sealos

- controllers/metering/config/rbac/role.yaml
- controllers/metering/controllers/metering_controller.go
- controllers/metering/deploy/manifests/deploy.yaml
- controllers/metering/testdata/e2e/metering_test.go
bug1:should update CR status instead of update CR spec
bug2:should create accountbalance CR once and none update ,but use CreateorUpdate  func will update accountbalance 
bug3: initMetering should exec once
> fix: Metering fix bug

- pkg/runtime/upgrade.go
close #2475 
Signed-off-by: mond77 <1208119827@qq.com>
> bugfix: nodename should be lower case

- desktop/frontend/README.md
- desktop/frontend/src/components/app_icon/index.tsx
- desktop/frontend/src/components/app_window/index.tsx
- desktop/frontend/src/components/desktop_content/index.module.scss
- desktop/frontend/src/components/desktop_content/index.tsx
- desktop/frontend/src/mock/installedApps.ts
- desktop/frontend/src/pages/_app.tsx
- desktop/frontend/src/stores/app.ts
- desktop/frontend/src/styles/mixin.scss
Now, you can drag the desktop icons to an blank space, the position of the icons is stored in localStorage.
Optimize the situation of window dragging to the boundary.
> Add desktio UX

- controllers/cluster/controllers/cluster_controller.go
- controllers/infra/common/common.go
- controllers/infra/testdata/api/cluster.go
- controllers/infra/testdata/api/infra.go
fix issue: https://github.com/labring/sealos/issues/2471
> fix: configure default clustername

- docs/4.0/docs/cloud/Intro.md
> update sealos cloud intro

- test/testdata/api/kubernetes.go
#2488 
fix go mod tidy error
@zzjin
> fix:go mod tidy error

- CHANGELOG/CHANGELOG-4.1.5-alpha1.md
- CHANGELOG/CHANGELOG-4.1.5-alpha2.md
> feature(main): add changelog for sealos

- docs/4.0/docs/cloud/Intro.md
- docs/4.0/docs/cloud/apps/appstore/appstore.md
- docs/4.0/docs/cloud/apps/appstore/use-sealos-registry.md
- docs/4.0/docs/cloud/apps/postgres/postgres.md
- docs/4.0/docs/cloud/apps/scp/scp.md
- docs/4.0/docs/cloud/apps/terminal/terminal.md
- docs/4.0/docs/cloud/apps/terminal/use-sealos-cloud-hello-world.md
- docs/4.0/docs/cloud/examples/use-cname-for-custom-host.md
- docs/4.0/docs/cloud/getting-started/index.md
Signed-off-by: shuaoz <shuaoz@umich.edu>
> docs: fix mistakes in the English version of cloud docs

- docs/4.0/docs/cloud/Intro.md
Signed-off-by: 中弈 <fanux@sealos.io>
> add a period at the end of each line

- desktop/frontend/README.md
- desktop/frontend/src/components/desktop_content/index.module.scss
- desktop/frontend/src/stores/app.ts
Signed-off-by: Archer <545436317@qq.com>
> fix(desktop): drag icon, first login fail

- pkg/apply/applydrivers/apply_drivers_default.go
- pkg/types/v1beta1/cluster.go
fix issue [2496](https://github.com/labring/sealos/issues/2496)
> bug. fix cluster status.

- desktop/frontend/src/components/app_window/index.tsx
- desktop/frontend/src/components/desktop_content/index.module.scss
- desktop/frontend/src/components/desktop_content/index.tsx
- desktop/frontend/src/mock/installedApps.ts
- desktop/frontend/src/stores/app.ts
Add UX. use can double click icon to open APP
> feat(desktop): double click, open app

- controllers/cluster/README.md
- controllers/cluster/controllers/cluster_controller.go
- controllers/infra/README.md
- controllers/infra/common/common.go
- controllers/infra/controllers/infra_controller.go
- controllers/infra/deploy/configMap/infra_ami_config.yaml
- controllers/infra/deploy/rbac/rbac.yaml
- controllers/infra/testdata/api/cluster.go
- docs/4.0/docs/cloud/apps/scp/scp.md
- docs/4.0/i18n/zh-Hans/cloud/apps/scp/scp.md
fix issue: https://github.com/labring/sealos/issues/2515
> feat: add ami ConfigMap && allow changable sealos version

- go.work.sum
- pkg/apply/processor/create.go
- pkg/apply/processor/delete.go
- pkg/apply/processor/install.go
- pkg/apply/processor/interface.go
1. remount container's mount point after reboot;
2. remove some unnecessary code;
> apply process optimization

- controllers/account/Makefile
ci job：https://github.com/labring/sealos/actions/runs/4112734806/jobs/7100978465
> fix: account image build ci

- docs/4.0/docs/cloud/examples/pull-private-image.md
- docs/4.0/i18n/zh-Hans/cloud/examples/pull-private-image.md
> docs:add english pull private image in sealos cloud docs

- cmd/sealos/cmd/root.go
> fix: reduce error output

- desktop/frontend/src/applications/infra/add_page.module.scss
- desktop/frontend/src/applications/infra/add_page.tsx
- desktop/frontend/src/applications/infra/detail_page.module.scss
- desktop/frontend/src/applications/infra/detail_page.tsx
- desktop/frontend/src/applications/infra/infra_share.ts
- desktop/frontend/src/applications/infra/select_node.tsx
- desktop/frontend/src/applications/pgsql/add_page.tsx
- desktop/frontend/src/applications/pgsql/components/controlled_fluent.tsx
- desktop/frontend/src/components/app_window/index.tsx
- desktop/frontend/src/components/desktop_content/index.tsx
- desktop/frontend/src/mock/infra.ts
- desktop/frontend/src/pages/api/infra/awsApply.ts
- desktop/frontend/src/pages/api/infra/getConfigMap.ts
> feat scp add mirror selection and validation

- pkg/apply/applydrivers/apply_drivers_default.go
- pkg/apply/applydrivers/errors.go
- pkg/apply/processor/errors.go
- pkg/apply/processor/install.go
- pkg/buildah/buildah.go
optimize 
- save write back file: fix codes
- install new image: add log and fix image pull error does not return
> bug: optimize installApp

- controllers/infra/controllers/infra_controller.go
> fix: secret name bug

- controllers/cluster/controllers/cluster_controller.go
- controllers/infra/config/rbac/role.yaml
> fix: sealos download

- cmd/sealos/cmd/version.go
fix sealos version error return bug
> fix sealos version err return bug

- controllers/cluster/config/rbac/role.yaml
- controllers/cluster/controllers/cluster_controller.go
- controllers/infra/common/common.go
- controllers/infra/drivers/aws/get_instance.go
- controllers/infra/how to update infra controller_zh .md
- controllers/infra/testdata/api/cluster.go
- controllers/infra/testdata/api/infra.go
- docs/4.0/docs/cloud/apps/scp/scp.md
- docs/4.0/i18n/zh-Hans/cloud/apps/scp/scp.md
> feat: support arm arch && new version cmd

- pkg/constants/data.go
- pkg/guest/guest.go
should fix: #2364
see: https://github.com/labring/sealos/issues/2364#issuecomment-1425386766
> make `getGuestCmd` handle RootfsImage

- controllers/cluster/controllers/cluster_controller.go
- controllers/infra/api/v1/infra_types.go
- controllers/infra/config/crd/bases/infra.sealos.io_infras.yaml
- controllers/infra/controllers/infra_controller.go
- controllers/infra/deploy/manifests/deploy.yaml
- controllers/infra/drivers/aliyun/aliyun.go
- controllers/infra/drivers/aliyun/get_instance.go
- controllers/infra/drivers/create_instance_test.go
- controllers/infra/drivers/create_volume_test.go
- controllers/infra/drivers/delete_instance_test.go
- controllers/infra/drivers/delete_volume_test.go
- controllers/infra/drivers/driver.go
- controllers/infra/drivers/get_instance_test.go
- controllers/infra/drivers/modify_volume_test.go
- controllers/infra/drivers/reconcile.go
- controllers/infra/drivers/reconcile_test.go
- controllers/infra/drivers/stop_instance_test.go
> feat: add compatible Aliyun interface

- pkg/registry/save.go
Signed-off-by: huiwq1990 <huiwq1990@163.com>
Fix duplicate scene.
```
2023-02-02T01:07:45 debug search images  platform: linux,amd64, , dir: /root/cloud-images/hello/registry, image list: [docker.io/library/nginx:1.23.1 nginx:1.23.1]
Pulling image: docker.io/library/nginx:1.23.1
Pulling image: docker.io/library/nginx:1.23.1
```
> remove duplicate pull image

- README.md
> docs(main): add action and images to link

- DEVELOPGUIDE.md
Signed-off-by: Bird <aflybird0@gmail.com>
1. fix some typo and terms
2. add more scripts to make it easier to develop
> docs: update develop guide

- README.md
> Add roadmap link in readme

- CHANGELOG/CHANGELOG-4.1.5-rc1.md
- CHANGELOG/CHANGELOG.md
> docs(main) add changelog

- .github/workflows/check-license.yml
- .github/workflows/ci.yml
- .github/workflows/controllers.yml
- .github/workflows/coverage.yml
- .github/workflows/e2e_metering.yml
- .github/workflows/format-code.yml
- .github/workflows/services.yml
- .github/workflows/webhooks.yml
- scripts/resolve-modules.sh
> ci(main): fix pr controllers build

- .github/workflows/check-license.yml
- .github/workflows/coverage.yml
- .github/workflows/e2e_metering.yml
- .github/workflows/format-code.yml
> ci(main): fix lic,converage,format-code ci

- .github/workflows/test_inspect.yml
> ci(main): fix test ci for inspect

- pkg/buildah/inspect.go
Fix: #2577
When the user specifies the image as `xxx.tar` format, the previous code logic is run. This code references:
https://github.com/labring/sealos/blob/6ab3a669682579ab1dc8852708cc8997e8af0d92/cmd/sealos/cmd/run.go#L116
> fix: error in inspect function when the image is in format "docker-archive:./xxx.tar"

- pkg/buildah/buildah.go
> fix: mark buildah's flags as hidden to prevent incorrect use

- docs/4.0/docs/build-cloud-image/build-cloudImage-with-env.md
> docs image tag error

- controllers/cluster/api/v1/cluster_types.go
- controllers/cluster/config/crd/bases/cluster.sealos.io_clusters.yaml
- controllers/cluster/controllers/cluster_controller.go
- controllers/infra/controllers/infra_controller.go
- controllers/infra/drivers/aws/create_instance.go
- controllers/infra/testdata/api/cluster.go
> feat: add Failed status for cloud provider

- pkg/apply/applydrivers/apply_drivers_default.go
- pkg/types/v1beta1/cluster.go
- pkg/types/v1beta1/helper.go
add a command conditions in cluster status, maybe call events is batter?
> Feat: add command conditions in cluster status.

- controllers/cluster/controllers/cluster_controller.go
- controllers/cluster/main.go
> add cluster concurrent reconciles opts

- README.md
> feat(main): fix docker calico image

- README.md
> docs(main): add docker pulls

- .github/workflows/ci.yml
- .github/workflows/controllers.yml
- .github/workflows/services.yml
- .github/workflows/test_inspect.yml
- .github/workflows/test_run.yml
- .github/workflows/webhooks.yml
- docs/4.0/docs/getting-started/customize-cluster-buildimage.md
- pkg/runtime/kubeadm.go
- pkg/runtime/kubeadm_config.go
- scripts/resolve-modules.sh
> feat(main): fix merge for cri and socket

- CHANGELOG/CHANGELOG-4.1.5-rc2.md
- CHANGELOG/CHANGELOG.md
> feat(main): add changelog

- .github/workflows/test_run.yml
- pkg/apply/processor/interface.go
- pkg/remote/util.go
> feat(main): add logger for registry and remote shell

- go.mod
- go.sum
- pkg/auth/utils/config.go
- service/auth/scripts/migrate.go
> fix(auth): replace user id with nanoId

- pkg/buildah/build.go
- pkg/buildah/common.go
- pkg/buildah/from.go
- pkg/buildah/imagesaver.go
- pkg/buildah/pull.go
- pkg/runtime/kubeadm.go
buildah sdk will pull image even if image is found in local containers storage as we changed `—platform` flag
> Fix image pull policy

- .github/workflows/test_registry.yml
- fork/github.com/heroku/docker-registry-client/registry/manifest.go
- pkg/registry/cmd/flags.go
- pkg/registry/cmd/get.go
- pkg/registry/cmd/registry.go
- pkg/registry/get.go
- pkg/registry/interface.go
- pkg/registry/list.go
> feat(main): add registry imageID

- .github/workflows/semgrep.yml
> Drop semgrep lint text/template for use.

- .github/workflows/semgrep.yml
> Drop semgrep 2 lint for common usage. (#2626)

- controllers/user/controllers/usergroupuserbinding_controller.go
should fix: https://github.com/labring/sealos/issues/2602
ref: https://github.com/labring/sealos/issues/2602
> remove "list namespace" privileges from clusterroles created by the user controller

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .goreleaser.yml
- Makefile
- scripts/make-rules/golang.mk
- scripts/make-rules/tools.mk
> feat(main): delete upx ci

- scripts/release/note.sh
> ci(main): fix note using sealos.io

- pkg/apply/utils.go
- pkg/buildah/inspect.go
> fix: inspect with id #2635

- .github/workflows/test_images.yml
- .github/workflows/test_inspect.yml
- .github/workflows/test_run.yml
- pkg/ssh/exec.go
> ci(main): fix scp error

- .github/workflows/test_images.yml
- pkg/buildah/merge.go
> ci(main): fix merge error

- service/hub/Dockerfile
> Update false semgrep of `missing-user`

- desktop/frontend/src/applications/app_store/app_store_common.ts
- desktop/frontend/src/applications/app_store/detail_page.tsx
- desktop/frontend/src/applications/infra/add_page.tsx
- desktop/frontend/src/layout/index.tsx
- desktop/frontend/src/pages/api/desktop/getInstalledApps.ts
- desktop/frontend/src/services/backend/kubernetes.ts
- desktop/frontend/src/stores/app.ts
> feat desktop supports app install

- CHANGELOG/CHANGELOG-4.1.5-rc3.md
- CHANGELOG/CHANGELOG.md
> ci(main): add changelog

- service/hub/Dockerfile
> Fix ENTRYPOINT using exec form

- docs/4.0/docs/design/private-registry.md
- docs/4.0/i18n/zh-Hans/design/private-registry.md
Signed-off-by: Carson Yang <yangchuansheng33@gmail.com>
> Fix image command error

- controllers/infra/api/v1/infra_types.go
- controllers/infra/common/common.go
- controllers/infra/go.mod
- controllers/infra/go.sum
Wait for #2658 to be merged first.
> Remove not used package

- pkg/apply/processor/install.go
- pkg/apply/processor/interface.go
- pkg/buildah/create.go
> fix: same issue #2623 again

- cmd/sealos/cmd/version.go
- pkg/constants/contants.go
> fix version typo

- docs/4.0/docs/design/private-registry.md
> update pravite registry docs

- pkg/buildah/build.go
- pkg/buildah/common.go
- pkg/buildah/interface.go
- pkg/buildah/load.go
- pkg/buildah/login.go
- pkg/buildah/manifest.go
- pkg/buildah/merge.go
- pkg/buildah/pull.go
- pkg/buildah/push.go
- pkg/buildimage/merge.go
- pkg/utils/maps/maps.go
> fix(main): fix merge and hidden flags

- CHANGELOG/CHANGELOG-4.1.5.md
- CHANGELOG/CHANGELOG.md
> fix(main): add changelog

- controllers/cluster/controllers/cluster_controller.go
> Fix double reconcile by status updates

- .github/workflows/ci.yml
- .github/workflows/controllers.yml
- .github/workflows/services.yml
- .github/workflows/webhooks.yml
Add select form to force push images when manual trigger ci.
> Add actions inputs

- service/hub/auth/authorize.go
> fix. authz logic.

- frontend/desktop/README.md
- frontend/desktop/pnpm-lock.yaml
- frontend/desktop/scripts/pre-commit
- frontend/desktop/src/layout/index.tsx
- frontend/desktop/src/mock/installedApps.ts
- frontend/desktop/src/mock/user.ts
- frontend/desktop/src/pages/api/kubernetes/account/get_amount.ts
> modify the account and add the iframe imagehub

- pkg/buildah/create.go
> fix(main): set short for create feature

- controllers/terminal/config/manager/manager.yaml
- controllers/terminal/controllers/ingress.go
- controllers/terminal/controllers/terminal_controller.go
- controllers/terminal/deploy/manifests/deploy.yaml
> get terminal domain from env

- controllers/user/config/rbac/role.yaml
- controllers/user/controllers/user_controller.go
- controllers/user/deploy/manifests/deploy.yaml
user should have create clusterrole rbac
> user add clusterrole rbac

- pkg/apply/processor/interface.go
- pkg/bootstrap/applier.go
- pkg/bootstrap/bootstrap.go
- pkg/bootstrap/context.go
- pkg/bootstrap/image_shim.go
- pkg/constants/bash.go
- pkg/env/env.go
- pkg/env/env_test.go
- pkg/remote/util.go
- pkg/runtime/runtime_getter.go
- pkg/ssh/scp.go
- pkg/ssh/sshcmd.go
- pkg/types/v1beta1/cluster.go
- pkg/utils/strings/strings.go
> fix(main): shell Wrapper from env

- pkg/runtime/reset.go
> fix(main): delete ipvs ip link

- cmd/sealos/cmd/cert.go
> fix(main): alt-names empty check

- frontend/desktop/src/mock/installedApps.ts
> Add Temp pre-installed deploy-manager

- pkg/constants/bash.go
- pkg/utils/maps/maps.go
sometimes not only builtin bash needs to be wrapped. So we provide a common way to do this.
> fix: provide a common way to wrap bash

- controllers/infra/drivers/aliyun/create_instance.go
- controllers/infra/drivers/aliyun/delete_instance.go
According to Aliyun hostname limit:
> fix: hostname too long

- .github/sync_docs.yml
- README.md
- docs/4.0/docs/ai-applications/athenaserving.md
- docs/4.0/i18n/zh-Hans/ai-applications/athenaserving.md
> Fix Readme assets, using absolute path.

- README.md
> Fix readme typo.

- pkg/apply/processor/create.go
- pkg/apply/processor/scale.go
- pkg/bootstrap/applier.go
- pkg/bootstrap/bootstrap.go
- pkg/bootstrap/context.go
- pkg/bootstrap/registry.go
- pkg/constants/bash.go
- pkg/filesystem/registry/registry.go
- pkg/runtime/registry.go
- pkg/runtime/reset.go
- pkg/runtime/runtime.go
- pkg/runtime/runtime_getter.go
> fix(main): bootstrap registry before all step

- .github/workflows/ci.yml
> Ignore frontend changes from ci docker

- pkg/runtime/node.go
> fix(main): delete node not exec clean.sh

- frontend/desktop/src/mock/hub/terminal.ts
> Change terminal image to self-host hub

- .github/workflows/cherry-pick.yml
- .github/workflows/rebase.yml
> ci(main): add rebase

- .github/workflows/cherry-pick.yml
- .github/workflows/ci.yml
- .github/workflows/controllers.yml
- .github/workflows/e2e_metering.yml
- .github/workflows/rebase.yml
- .github/workflows/release.yml
- .github/workflows/services.yml
- .github/workflows/webhooks.yml
> ci(main): replace GH_TOKEN,GITHUB_TOKEN to GH_PAT

- .github/workflows/cherry-pick.yml
- .github/workflows/rebase.yml
> ci(main): add github.event.comment.author_association

- .github/labels.yml
> ci(main): add labels size to .github

- .github/workflows/cherry-pick.yml
- .github/workflows/debug.yml
> ci(main): add debug.yml

- pkg/buildah/build.go
- pkg/buildah/imagesaver.go
- pkg/registry/cmd/flags.go
- pkg/registry/cmd/get.go
- pkg/registry/cmd/list.go
- pkg/registry/cmd/rmi.go
- pkg/registry/cmd/status.go
- pkg/registry/util.go
- pkg/registry/util_test.go
get auth infos from `--authfile` flag.
> fix: share the same systemContext in build command

- .github/mergeable.settings.yml
- .github/mergeable.yml
- .github/no-response.yml
- .github/stale.yml
> ci(main): add ci for merge

- frontend/desktop/src/components/app_window/index.tsx
- frontend/desktop/src/components/desktop_content/iframe_app.tsx
- frontend/desktop/src/mock/installedApps.ts
- frontend/desktop/src/pages/api/desktop/getInstalledApps.ts
- frontend/desktop/src/stores/app.ts
- frontend/providers/imagehub/package.json
- frontend/providers/imagehub/pnpm-lock.yaml
- frontend/providers/imagehub/src/layout/index.tsx
> feat Obtain desktop applications through app crd

- CHANGELOG/CHANGELOG-4.1.7.md
- CHANGELOG/CHANGELOG.md
> doc(main): add CHANGELOG-4.1.7.md

- controllers/infra/controllers/infra_controller.go
- controllers/infra/drivers/aliyun/delete_instance.go
- controllers/infra/go.mod
- controllers/infra/go.sum
- controllers/infra/main.go
> feat: add infra concurrent opts & optimize delete instances

- cmd/sealos/cmd/config.go
- cmd/sealos/cmd/root.go
- go.mod
- pkg/buildah/common.go
- pkg/constants/data.go
- pkg/system/config.go
- pkg/system/config_cmd.go
- pkg/system/config_example.go
- pkg/system/config_example_test.go
- pkg/template/template.go
- pkg/utils/confirm/confirm.go
> feature(main): add system config to sealos

- frontend/desktop/Makefile
- frontend/desktop/src/components/desktop_content/iframe_app.tsx
- frontend/providers/imagehub/src/interfaces/imagehub.ts
> Fix iframe copy issue

- pkg/types/v1beta1/cluster_args.go
> fix `GetRootfsImage` function cause panic

- pkg/buildah/common.go
- pkg/buildah/merge.go
- staging/src/github.com/labring/image-cri-shim/pkg/cri/cri.go
close #2803 
1. fixed crio cgroup support
2. merge --platform error
> feature(main): add cri cgroup-driver

- pkg/ssh/scp.go
- pkg/system/config.go
> feature(main): check scp md5sum to config cmd

- README.md
- docs/4.0/i18n/zh-Hans/Intro.md
> update zh readme

- pkg/registry/cmd/list.go
- pkg/registry/list.go
> feature(main): registry list repo fix

- pkg/runtime/utils.go
> feature(main): delete node if failed

- pkg/types/v1beta1/cluster.go
> fix: json tag of ssh field

- frontend/desktop/src/components/start_menu/charge_button.tsx
- frontend/desktop/src/pages/api/kubernetes/account/get_amount.ts
- frontend/desktop/src/pages/api/kubernetes/account/payment/[name].ts
- frontend/desktop/src/pages/api/kubernetes/account/payment/index.ts
- frontend/desktop/src/utils/format.ts
> Payment change 1 RMB equals 10000

- frontend/providers/imagehub/Makefile
- frontend/providers/imagehub/src/pages/detail.tsx
- frontend/providers/imagehub/src/pages/store.tsx
> Request failed to switch config

- frontend/desktop/src/services/request.ts
> fix the request header problem

- frontend/desktop/src/applications/pgsql/components/events_dialog.tsx
- frontend/desktop/src/applications/pgsql/pgsql_status.tsx
> fix pgsql create default state

- pkg/env/env.go
- pkg/filesystem/rootfs/rootfs_default.go
Render the template files only once.
> fix: avoid rendering template repeatedly

- docs/4.0/docs/design/image-cri-shim.md
- docs/4.0/i18n/zh-Hans/design/image-cri-shim.md
> docs(main): add image-cri-shim docs

- pkg/buildah/merge.go
> docs(main): add debug for merge logger

- frontend/desktop/src/components/notification/index.module.scss
- frontend/desktop/src/components/notification/index.tsx
- frontend/desktop/src/components/taskbar/index.tsx
> fix notification refetch

- controllers/account/config/default/manager_auth_proxy_patch.yaml
- controllers/account/config/manager/manager.yaml
- controllers/account/deploy/manifests/deploy.yaml
two envfrom in two yaml file  will lead to cover
```
envFrom:
- secretRef:
name: payment-secret
```
> fix: make pre-deploy error

- .github/workflows/sync_code.yml
- .github/workflows/sync_docs.yml
> docs(main): sync code user and email

- .github/workflows/e2e_metering.yml
https://github.com/xiao-jay/sealos/actions/runs/4596413259/jobs/8117931895
I have tested in local repo,it work well.
> fix(ci): fix metering e2e install account error

- docs/4.0/docs/design/user.md
- docs/4.0/i18n/zh-Hans/design/user.md
> docs(main): add docs for user

- controllers/account/api/v1/debt_webhook.go
- controllers/account/config/webhook/manifests.yaml
- controllers/account/deploy/manifests/deploy.yaml
- controllers/account/main.go
account webhook name error, delete useless code
> format(account): format webhook name

- pkg/runtime/defaults/v127/default_kubeadm_config.go
- pkg/runtime/kubeadm.go
- pkg/runtime/utils.go
> docs(main): support v1.27 k8s

- .github/workflows/test_images.yml
- pkg/buildah/pull.go
> feature: support pulling multiple images at the same time

- docs/4.0/docs/getting-started/kuberentes-support.md
> docs(main): support v1.27 docs

- frontend/desktop/src/applications/pgsql/pgsql_status.tsx
> fix pgsql status null

- pkg/runtime/kubeadm.go
- pkg/runtime/master.go
- pkg/runtime/node.go
- pkg/runtime/update_cert.go
Fix the failure of join master after changing the serviceCIDR.
fix #2854
> bugfix the failure of join master after changing the serviceCIDR

- pkg/runtime/master.go
- pkg/runtime/node.go
- pkg/runtime/reset.go
- pkg/runtime/utils.go
optimize reset node `ip link delete` command.
> optimize reset node `ip link delete` command.

- .github/workflows/e2e.yml
- docs/4.0/docs/Development-Guidelines/e2e-example.md
- docs/4.0/i18n/zh-Hans/Development-Guidelines/e2e-example.md
docs about how to write e2e test and how to witre github-action about e2e.
local e2e run normal.https://github.com/xiao-jay/sealos/actions/runs/4674946844
> ci，docs: add account e2e test and docs

- controllers/infra/drivers/aliyun/create_instance.go
Modified the creating logic to avoid bugs
> fix: check sg & vswitch existence

- test/e2e/suites/apply/apply.go
> fix multi infra apply

- pkg/apply/run.go
I encountered an warning error when using sealos gen CMD generate ClusterFile,the function getHostArch did not use the "--port" args, it used the default port 22。
> fix the warning error when executing run gen CMD

- frontend/providers/applaunchpad/src/pages/api/restartApp.ts
- frontend/providers/applaunchpad/src/pages/api/updateApp.ts
- frontend/providers/applaunchpad/src/pages/app/edit/components/Form.tsx
- frontend/providers/applaunchpad/src/pages/app/edit/components/Header.tsx
- frontend/providers/applaunchpad/src/pages/app/edit/index.tsx
- frontend/providers/applaunchpad/src/utils/deployYaml2Json.ts
1. update export yaml file name
2. focus restart app;
3. ingress conf
> perf: export yaml name;focus restart app;

- frontend/providers/applaunchpad/src/pages/app/edit/components/Form.tsx
- frontend/providers/applaunchpad/src/pages/app/edit/index.tsx
- frontend/providers/applaunchpad/src/utils/adapt.ts
- frontend/providers/applaunchpad/src/utils/deployYaml2Json.ts
use blank to split cmd or params
> feat: cmd and params input way

- pkg/ssh/clusterclient.go
- pkg/ssh/ssh.go
- pkg/ssh/sshcmd.go
- pkg/utils/exec/cmd.go
with `*WithContext` function, now we can cancel remote commands.
> feat: add withcontext functions in ssh interface

- README.md
Added Hyperlink for twitter in Readme file and added message
> Added Hyperlink for twitter in  README.md

- docs/4.0/docs/examples/low-code-platform/install-appsmith.md
- docs/4.0/docs/examples/low-code-platform/install-pageplug.md
> add low-code-platform

- docs/4.0/i18n/zh-Hans/examples/low-code-platform/install-appsmith.md
- docs/4.0/i18n/zh-Hans/examples/low-code-platform/install-pageplug.md
> optimize the title

- docs/4.0/docs/examples/wordpress-with-sealos.md
- docs/4.0/docs/platform-components/bytebase/bytebase.md
- docs/4.0/i18n/zh-Hans/platform-components/bytebase/bytebase.md
> correct the title

- frontend/client-sdk/package.json
- frontend/desktop/package.json
- frontend/desktop/pnpm-lock.yaml
- frontend/providers/adminer/src/interfaces/zalando.ts
- frontend/providers/applaunchpad/package.json
- frontend/providers/applaunchpad/src/components/AppStatusTag/index.tsx
- frontend/providers/applaunchpad/src/components/PodLineChart/index.tsx
- frontend/providers/applaunchpad/src/constants/theme.ts
- frontend/providers/applaunchpad/src/pages/api/delApp.ts
- frontend/providers/applaunchpad/src/pages/app/detail/components/AppBaseInfo.tsx
- frontend/providers/applaunchpad/src/pages/app/detail/components/AppMainInfo.tsx
- frontend/providers/applaunchpad/src/pages/app/detail/components/Header.tsx
- frontend/providers/applaunchpad/src/pages/app/detail/components/LogsModal.tsx
- frontend/providers/applaunchpad/src/pages/app/detail/components/PodDetailModal.tsx
- frontend/providers/applaunchpad/src/pages/app/detail/components/Pods.tsx
- frontend/providers/applaunchpad/src/pages/app/detail/index.module.scss
- frontend/providers/applaunchpad/src/pages/app/detail/index.tsx
- frontend/providers/applaunchpad/src/pages/app/edit/components/EditEnvs.tsx
- frontend/providers/applaunchpad/src/pages/app/edit/components/Form.tsx
- frontend/providers/applaunchpad/src/pages/app/edit/components/index.module.scss
- frontend/providers/applaunchpad/src/pages/app/edit/index.module.scss
- frontend/providers/applaunchpad/src/pages/app/edit/index.tsx
- frontend/providers/applaunchpad/src/pages/apps/components/appList.tsx
- frontend/providers/applaunchpad/src/pages/apps/components/empty.tsx
- frontend/providers/applaunchpad/src/utils/deployYaml2Json.ts
fix: statefuleSet request cpu and memory
fix: ws config
feat: sdk version
perf-launchpad: ui,chart,env show
> Frontend perf

- deploy/cloud/init.sh
- deploy/cloud/scripts/init.sh
- frontend/READMD.md
- frontend/providers/dbprovider/deploy/manifests/appcr.yaml.tmpl
- frontend/providers/dbprovider/src/api/db.ts
- frontend/providers/dbprovider/src/constants/db.ts
- frontend/providers/dbprovider/src/constants/editApp.ts
- frontend/providers/dbprovider/src/pages/db/edit/components/Form.tsx
- frontend/providers/dbprovider/src/pages/db/edit/index.tsx
- frontend/providers/dbprovider/src/services/backend/kubernetes.ts
- frontend/providers/dbprovider/src/utils/json2Yaml.ts
feat: apply limitrange;
perf: db min cpu and memory;
docs: new app configuration;
> dbprovider 0.3.1

- deploy/registry/README.md
- docs/4.0/i18n/zh-Hans/examples/ai-applications/athenaserving.md
- docs/4.0/i18n/zh-Hans/lifecycle-management/operations/build-image/build-image-with-kubeadm-run-cluster.md
- docs/4.0/i18n/zh-Hans/lifecycle-management/operations/run-cluster/gen-apply-cluster.md
Mainly fixed the link failure of doc 4.0.
#3266
> docs: fix part of the link failure

- controllers/account/controllers/account_controller.go
- controllers/account/controllers/account_controller_test.go
> bugfix: fix the wrong unit

- pkg/runtime/upgrade.go
> fix: upgrade k8s version failed on non default ssh port (issue #3069)

- pkg/client-go/kubernetes/expansion.go
associate issue #3445 
sealos checks kubelet configmap when it runing upgrade k8s verison.
> support old version of kubelet-config

- docs/4.0/docs/lifecycle-management/advanced-guide/dual-stack-cluster.md
- docs/4.0/i18n/zh-Hans/lifecycle-management/advanced-guide/dual-stack-cluster.md
> docs: add dual-stack docs

- pkg/apply/processor/create.go
- pkg/checker/host_checker.go
fix issue #3527 
add ip list to check hostname
> fix: check hostname unique in creating new cluster

- pkg/apply/applydrivers/apply_drivers_default.go
- pkg/apply/processor/create.go
- pkg/apply/processor/errors.go
fix issue https://github.com/labring/sealos/issues/3428
> fix cluster status

- .github/workflows/e2e_test_apply.yml
https://github.com/labring/sealos/pull/3691#issuecomment-1685971487
> fix e2e apply test issue

- controllers/node/controllers/gpu_controller.go
> Count pods that not in succeeded & watch gpu changes on nodes

- docs/4.0/i18n/zh-Hans/lifecycle-management/reference/sealos/commands/logout.md
sealos logout cmd  documentation error
> docs: sealos logout cmd  documentation error

- pkg/apply/applydrivers/apply_drivers_default.go
> fix: sync sealos work dir

- pkg/runtime/kubernetes/certs.go
fix for #3891 ,  it will fail  when using non default port
> fix: sync cert failed on non default port

- controllers/job/heartbeat/deploy/manifests/deploy.yaml
> chore: fix heartbeat job rbac

- controllers/license/cmd/manager/main.go
- controllers/license/internal/util/clusterid/cluster_id.go
> chore: fix license controller get kube-system.

- frontend/providers/template/src/pages/api/getTemplateSource.ts
- frontend/providers/template/src/pages/api/listTemplate.ts
> fix:tempalte detail api add cdn

- controllers/pkg/resources/resources.go
> change nodeport default price

- deploy/cloud/manifests/tls-secret.yaml
- scripts/cloud/install.sh
> chore: add monitor for database and kubernetes.

- deploy/cloud/manifests/tls-secret.yaml
- frontend/providers/dbprovider/deploy/Kubefile
- scripts/cloud/build-offline-tar.sh
- scripts/cloud/install.sh
- service/database/deploy/manifests/deploy.yaml
> chore: fix database monitor.

- docs/4.0/i18n/zh-Hans/examples/programming-languages/Quick installation of Vue Apps.md
> Update Quick installation of Vue Apps.md

- docs/blog/zh-Hans/2023/k8s-multi-tenancy.md
- docs/blog/zh-Hans/2023/what-is-sealos.md
> chore: fix docs link.

- docs/4.0/docs/self-hosting/lifecycle-management/quick-start/deploy-kubernetes.md
- docs/4.0/i18n/zh-Hans/self-hosting/lifecycle-management/quick-start/deploy-kubernetes.md
> k3s support version doc

- frontend/providers/template/deploy/manifests/deploy.yaml.tmpl
- frontend/providers/template/src/pages/app/components/list.tsx
- frontend/providers/template/src/pages/app/index.tsx
> feat:template deploy add template-static

- frontend/providers/dbprovider/src/pages/db/edit/components/Form.tsx
- frontend/providers/template/src/pages/api/updateRepo.ts
> fix:dbprovider maximum storage

- scripts/cloud/install.sh
> chore: add extra value for cilium.

- frontend/desktop/src/pages/index.tsx
- frontend/desktop/src/pages/signin.tsx
- frontend/providers/dbprovider/src/constants/db.ts
- frontend/providers/dbprovider/src/pages/api/minio/upload.ts
- frontend/providers/template/.dockerignore
- frontend/providers/template/.gitignore
- frontend/providers/template/deploy/manifests/deploy.yaml.tmpl
- frontend/providers/template/src/pages/api/getTemplateSource.ts
- frontend/providers/template/src/pages/api/listTemplate.ts
- frontend/providers/template/src/pages/api/updateRepo.ts
- frontend/providers/template/src/pages/api/v1alpha/listTemplate.ts
- frontend/providers/template/src/pages/develop/index.tsx
- frontend/providers/template/src/pages/index.tsx
> fix:template redirection problem

- frontend/packages/ui/src/components/icons/SortPolygonDownIcon.tsx
- frontend/packages/ui/src/components/icons/SortPolygonUpIcon.tsx
- frontend/packages/ui/src/components/index.ts
- frontend/pnpm-lock.yaml
- frontend/providers/objectstorage/package.json
- frontend/providers/objectstorage/public/locales/en/file.json
- frontend/providers/objectstorage/public/locales/zh/file.json
- frontend/providers/objectstorage/src/components/BucketContainer/FileManager.tsx
- frontend/providers/objectstorage/src/components/BucketContainer/Monitor.tsx
- frontend/providers/objectstorage/src/components/BucketContainer/PathLink.tsx
- frontend/providers/objectstorage/src/components/common/modal/UploadModal/index.tsx
- frontend/providers/objectstorage/src/pages/_app.tsx
> feat(object-storage):add sort feature

- docs/4.0/docs/self-hosting/sealos/QA.md
- docs/4.0/i18n/zh-Hans/self-hosting/sealos/QA.md
> user registration switch

- frontend/providers/costcenter/src/components/billing/NamespaceMenu.tsx
- frontend/providers/costcenter/src/components/cost_overview/buget.tsx
- frontend/providers/costcenter/src/components/cost_overview/components/lineChart.tsx
- frontend/providers/costcenter/src/components/cost_overview/components/pieChart.tsx
- frontend/providers/costcenter/src/components/cost_overview/cost.tsx
- frontend/providers/costcenter/src/components/cost_overview/trend.tsx
- frontend/providers/costcenter/src/pages/_app.tsx
- frontend/providers/costcenter/src/pages/api/billing/buget.ts
- frontend/providers/costcenter/src/pages/api/billing/costs.ts
- frontend/providers/costcenter/src/pages/api/billing/propertiesUsedAmount.ts
- frontend/providers/costcenter/src/pages/api/properties.ts
- frontend/providers/costcenter/src/pages/billing/index.tsx
- frontend/providers/costcenter/src/pages/cost_overview/index.tsx
- frontend/providers/costcenter/src/pages/valuation/index.tsx
- frontend/providers/costcenter/src/types/billing.ts
- frontend/providers/costcenter/src/types/valuation.ts
> refactor(costcenter): service api

- pkg/runtime/kubernetes/types/default_kubeadm_config.go
- scripts/cloud/build-offline-tar.sh
fix build cloud offline image.
> optimize default kube runtime config;

- controllers/admission/api/v1/ingress_webhook.go
- controllers/admission/cmd/main.go
> chore: fix validator setup.

- lychee.toml
> docs: update lychee config

- frontend/providers/applaunchpad/src/components/Table/index.tsx
- frontend/providers/applaunchpad/src/constants/theme.ts
- frontend/providers/template/public/locales/en/common.json
- frontend/providers/template/public/locales/zh/common.json
- frontend/providers/template/src/api/delete.ts
- frontend/providers/template/src/components/Banner/index.tsx
- frontend/providers/template/src/pages/api/app/listOtherByName.ts
- frontend/providers/template/src/pages/api/resource/delService.ts
- frontend/providers/template/src/pages/index.tsx
- frontend/providers/template/src/pages/instance/components/otherList.tsx
- frontend/providers/template/src/store/resource.ts
- frontend/providers/template/src/types/resource.ts
- frontend/providers/template/src/utils/adapt.ts
> feat:template obtains service resources

- frontend/providers/template/src/pages/api/resource/delDBByName.ts
- frontend/providers/template/src/pages/instance/components/otherList.tsx
> fix:template service nodeport

- frontend/providers/template/deploy/manifests/deploy.yaml.tmpl
> chore: fix template typos.

- frontend/desktop/package.json
- frontend/desktop/public/locales/en/common.json
- frontend/desktop/public/locales/zh/common.json
- frontend/desktop/src/api/platform.ts
- frontend/desktop/src/components/signin/auth/useWechat.tsx
- frontend/desktop/src/components/signin/index.tsx
- frontend/desktop/src/pages/api/auth/publicWechat/getWechatQR.ts
- frontend/desktop/src/pages/api/auth/publicWechat/getWechatResult.ts
- frontend/desktop/src/pages/api/auth/publicWechat/handleWechat.ts
- frontend/desktop/src/services/backend/db/wechatCode.ts
- frontend/desktop/src/types/index.ts
- frontend/desktop/src/types/login.ts
- frontend/desktop/src/types/user.ts
- frontend/pnpm-lock.yaml
> feat:desktop support wechat public account login 

- frontend/desktop/deploy/manifests/rbac.yaml
- frontend/desktop/src/api/platform.ts
- frontend/desktop/src/components/desktop_content/index.tsx
- frontend/desktop/src/components/notification/index.tsx
- frontend/desktop/src/pages/api/notification/global.ts
- frontend/desktop/src/types/crd.ts
- frontend/providers/template/src/components/Icon/index.tsx
- frontend/providers/template/src/components/Select/index.tsx
- frontend/providers/template/src/pages/deploy/components/Form.tsx
- frontend/providers/template/src/pages/develop/components/Form.tsx
- frontend/providers/template/src/pages/develop/index.tsx
- frontend/providers/template/src/types/app.ts
- frontend/providers/template/src/utils/json-yaml.ts
> feat:template support parsing option lists

- .github/workflows/objectstorage.yaml
> fix object storage workflow error

- frontend/desktop/deploy/manifests/secret.yaml
- frontend/desktop/deploy/scripts/init.sh
fix desktop secret error in some k8s version.
> chore: fix desktop secret error.

- frontend/plugins/kubepanel/src/components/chart/pie-chart.tsx
- frontend/plugins/kubepanel/src/components/common/action/action-button.tsx
- frontend/plugins/kubepanel/src/components/common/action/create-resource-modal.tsx
- frontend/plugins/kubepanel/src/components/common/section/section.tsx
- frontend/plugins/kubepanel/src/components/common/sidebar/sidebar.tsx
- frontend/plugins/kubepanel/src/pages/kubepanel/index.tsx
- frontend/plugins/kubepanel/src/pages/kubepanel/kube-object/workload/overview/overview.tsx
- frontend/plugins/kubepanel/src/pages/kubepanel/layout.tsx
- frontend/plugins/kubepanel/src/styles/globals.css
> style(kubepanel): adjust style

- frontend/desktop/deploy/manifests/deploy.yaml.tmpl
- scripts/cloud/install.sh
> chore: fix desktop deployment error and update cert-manager version.

- .github/workflows/frontend.yml
- frontend/plugins/kubepanel/deploy/menifests/deploy.yaml.tmpl
> chore: enable build kubepanel image.

- .github/workflows/frontend.yml
- frontend/plugins/kubepanel/deploy/menifests/deploy.yaml.tmpl
> Build kubepanel

- controllers/objectstorage/deploy/manifests/deploy.yaml.tmpl
- controllers/terminal/deploy/manifests/deploy.yaml.tmpl
- controllers/user/deploy/manifests/deploy.yaml.tmpl
- frontend/desktop/deploy/manifests/deploy.yaml.tmpl
- frontend/providers/adminer/deploy/manifests/deploy.yaml
- frontend/providers/applaunchpad/deploy/manifests/deploy.yaml.tmpl
- frontend/providers/costcenter/deploy/manifests/deploy.yaml.tmpl
- frontend/providers/dbprovider/deploy/manifests/deploy.yaml.tmpl
- frontend/providers/objectstorage/deploy/manifests/deploy.yaml.tmpl
- frontend/providers/template/deploy/manifests/deploy.yaml.tmpl
- frontend/providers/terminal/deploy/manifests/deploy.yaml.tmpl
> chore: change sealos cloud component resource limit.

- deploy/objectstorage/scripts/minio.sh
> fix minio init error

- docs/website/docusaurus.config.js
- docs/website/src/components/SaleBanner/index.scss
- docs/website/src/components/SaleBanner/index.tsx
- docs/website/src/pages/components/Header/index.scss
- docs/website/src/pages/index.tsx
> feat:docs sale banner

- frontend/desktop/src/__tests__/api/e2e/namespace/invite.test.ts
- frontend/desktop/src/api/auth.ts
- frontend/desktop/src/api/namespace.ts
- frontend/desktop/src/components/account/index.tsx
- frontend/desktop/src/components/signin/auth/usePassword.tsx
- frontend/desktop/src/components/signin/auth/useSms.tsx
- frontend/desktop/src/pages/api/auth/namespace/switch.ts
- frontend/desktop/src/pages/callback.tsx
- frontend/desktop/src/pages/switchRegion.tsx
- frontend/desktop/src/services/backend/auth.ts
- frontend/desktop/src/services/backend/regionAuth.ts
- frontend/desktop/src/utils/sessionConfig.ts
- frontend/packages/client-sdk/src/master.ts
- frontend/packages/client-sdk/src/types/user.d.ts
- frontend/providers/adminer/src/stores/session.ts
> feat(desktop): add appToken for providers & fix ssr error

- docs/website/docusaurus.config.js
- docs/website/src/pages/components/Header/index.scss
- docs/website/src/pages/index.tsx
- docs/website/static/global.js
- service/license/src/pages/cluster/components/ConfigForm.tsx
> docs:offline recharge promotions

- frontend/desktop/deploy/manifests/deploy.yaml.tmpl
- frontend/desktop/deploy/manifests/secret.yaml
> addEnv to deploy desktop

- frontend/Dockerfile
- frontend/desktop/.dockerignore
- frontend/desktop/package.json
- frontend/package.json
- frontend/pnpm-lock.yaml
> chore(frontend): add prisma cli into prod image

- frontend/desktop/deploy/manifests/deploy.yaml.tmpl
- frontend/desktop/deploy/manifests/secret.yaml
> chore(frontend): add jwt-secret-app env

- controllers/user/controllers/user_controller.go
> fix user change ns annotations

- controllers/account/controllers/accountv2_test.go
- controllers/account/controllers/debt_controller.go
- controllers/account/main.go
- controllers/pkg/database/cockroach/accountv2.go
- controllers/pkg/database/interface.go
- controllers/pkg/database/mongo/user.go
- controllers/pkg/database/mongo/user_test.go
- controllers/pkg/types/User.go
- controllers/pkg/types/dbquery.go
- controllers/pkg/types/global.go
- service/account/api/api.go
- service/account/dao/interface.go
- service/account/docs/docs.go
- service/account/docs/swagger.json
- service/account/docs/swagger.yaml
- service/account/helper/common.go
- service/account/helper/request.go
- service/account/router/router.go
> Transfer service

- controllers/db/adminer/controllers/adminer_controller.go
- controllers/terminal/controllers/terminal_controller.go
> Fix controller ingress label override.

- frontend/providers/template/src/components/layout/index.tsx
- frontend/providers/template/src/components/layout/sidebar.tsx
- frontend/providers/template/src/pages/404.tsx
- frontend/providers/template/src/pages/index.tsx
- frontend/providers/template/src/store/config.ts
> feat:optimize app store loading

- scripts/cloud/install.sh
> chore: fix typo.

- scripts/cloud/install.sh
> Revised version

- frontend/packages/client-sdk/src/app.ts
Description:
When open frontend project in local, page will auto fall into online site due to mock data empty.
> fix: local page auto fall into online site.

- deploy/cloud/scripts/init.sh
> fix gen region uid

- service/account/deploy/manifests/deploy.yaml.tmpl
> fix job/init env

- frontend/providers/dbprovider/src/utils/json2Yaml.ts
> fix:db external network connection

- frontend/desktop/src/components/account/index.tsx
- frontend/desktop/src/components/signin/auth/AuthList.tsx
- frontend/desktop/src/components/signin/auth/usePassword.tsx
- frontend/desktop/src/components/signin/auth/useSms.tsx
- frontend/desktop/src/components/signin/index.tsx
- frontend/desktop/src/hooks/useDriver.tsx
- frontend/desktop/src/pages/_app.tsx
- frontend/desktop/src/pages/api/account/getAmount.ts
- frontend/desktop/src/pages/api/auth/oauth/github/index.ts
- frontend/desktop/src/pages/api/auth/oauth/google/index.ts
- frontend/desktop/src/pages/api/auth/oauth/wechat/index.ts
- frontend/desktop/src/pages/api/auth/password/index.ts
- frontend/desktop/src/pages/api/auth/phone/verify.ts
- frontend/desktop/src/pages/callback.tsx
- frontend/desktop/src/pages/index.tsx
- frontend/desktop/src/pages/signin.tsx
- frontend/desktop/src/services/backend/globalAuth.ts
- frontend/desktop/src/services/backend/kubernetes/user.ts
- frontend/desktop/src/stores/global.ts
- frontend/desktop/src/utils/sessionConfig.ts
- frontend/providers/dbprovider/src/pages/db/detail/components/AppBaseInfo.tsx
- frontend/providers/dbprovider/src/services/backend/kubernetes.ts
- frontend/providers/dbprovider/src/utils/json2Yaml.ts
> feat:desktop supports invitations 

- controllers/objectstorage/deploy/manifests/deploy.yaml.tmpl
> fix: fix env name error

- frontend/pnpm-lock.yaml
- frontend/providers/template/package.json
- frontend/providers/template/src/pages/api/listTemplate.ts
- frontend/providers/template/src/utils/json-yaml.ts
> feat:template support base64 

- frontend/desktop/src/components/region/RegionToggle.tsx
> fix:desktop region info

- controllers/job/init/internal/util/database/user.go
- controllers/pkg/database/cockroach/accountv2.go
- controllers/pkg/types/global.go
> fix create region description

- scripts/cloud/install.sh
> chore: fix ingress-nginx allow-snippet-annotations.

- deploy/cloud/scripts/init.sh
> chore: run sealos desktop to init database.

- controllers/job/init/Makefile
- controllers/job/init/internal/util/database/user.go
- controllers/pkg/database/cockroach/accountv2.go
> Fix waiting for table creation

- controllers/objectstorage/controllers/objectstorageuser_controller.go
Add a secret for each object storage user to store the key(accessKey, secretKey, internal, external).
> feat: add object storage key secret

- frontend/desktop/src/components/region/RegionToggle.tsx
- frontend/desktop/src/pages/api/auth/password/exist.ts
- frontend/packages/client-sdk/src/utils/kubernetes.ts
- frontend/providers/applaunchpad/src/pages/app/edit/components/Form.tsx
- frontend/providers/applaunchpad/src/pages/app/edit/index.tsx
- frontend/providers/applaunchpad/src/services/backend/kubernetes.ts
- frontend/providers/dbprovider/src/pages/db/edit/index.tsx
- frontend/providers/objectstorage/src/components/BucketContainer/HostStatus.tsx
- frontend/providers/objectstorage/src/pages/api/site/openHost.ts
- frontend/providers/objectstorage/src/pages/api/site/status.ts
> fix:desktop password login and static host

- controllers/job/init/internal/util/database/user.go
- scripts/cloud/install.sh
> Fix init admin account & kbcli addon enable snapshot-controller

- docs/website/src/pages/self-hosting/product/index.tsx
- frontend/desktop/src/components/account/index.tsx
- frontend/desktop/src/components/region/RegionToggle.tsx
- frontend/desktop/src/pages/switchRegion.tsx
- frontend/desktop/src/stores/session.ts
> fix:desktop keep last workspace state

- scripts/cloud/build-offline-tar.sh
- scripts/cloud/install.sh
> chore: fix offline build script.

- frontend/providers/applaunchpad/deploy/Kubefile
- frontend/providers/applaunchpad/deploy/manifests/deploy.yaml.tmpl
> chore: fix applaunchpad deploy file typo.

- service/minio/deploy/manifests/deploy.yaml.tmpl
> add limits to monitor service

- deploy/cloud/init.sh
- deploy/cloud/scripts/init.sh
- scripts/cloud/install.sh
> chore: add launchpad monitor service.

- service/launchpad/request/req.go
> Fix service/launchpad typo.

- helm/sealos/charts/applaunchpad/values.yaml
- helm/sealos/charts/desktop/values.yaml
> chore: remove repetitive words

- deploy/cloud/scripts/init.sh
> chore: fix script.

- README_zh.md
fix link 404 error and change top cluster to hzh cluster.
> fix link 404

- README.md
> fix link 404 err0r

- docs/4.0/i18n/zh-Hans/quick-start/use-app-launchpad.md
- docs/4.0/i18n/zh-Hans/quick-start/use-database.md
- docs/4.0/i18n/zh-Hans/quick-start/use-template.md
- docs/4.0/i18n/zh-Hans/quick-start/use-terminal.md
- docs/website/src/hooks/useWindow.ts
- docs/website/src/pages/index.tsx
- docs/website/static/global.js
> fix:docs link address

- frontend/desktop/prisma/global/schema.prisma
- frontend/desktop/src/__tests__/api/e2e/namespace/invite.test.ts
- frontend/desktop/src/components/signin/auth/AuthList.tsx
- frontend/desktop/src/pages/api/auth/namespace/invite.ts
- frontend/desktop/src/pages/api/auth/oauth/oauth2/index.ts
- frontend/desktop/src/pages/api/platform/getEnv.ts
- frontend/desktop/src/pages/callback.tsx
- frontend/desktop/src/services/backend/globalAuth.ts
- frontend/desktop/src/services/enable.ts
- frontend/desktop/src/stores/global.ts
- frontend/desktop/src/types/api.ts
- frontend/desktop/src/types/system.ts
- frontend/desktop/src/types/user.ts
- frontend/providers/applaunchpad/README.md
- frontend/providers/costcenter/src/components/billing/TypeMenu.tsx
> feat:Desktop add standard OAuth2 login support 

- frontend/providers/costcenter/deploy/manifests/deploy.yaml.tmpl
> chore: fix cost center BILLING_URI.

- controllers/pkg/objectstorage/objectstorage.go
- controllers/pkg/objectstorage/objectstorage_test.go
- controllers/resources/controllers/monitor_controller.go
> query traffic at a specified time

- scripts/cloud/install.sh
- service/database/deploy/manifests/deploy.yaml
> chore: fix database monitor, use vm.

- pkg/utils/iputils/iputils_v2.go
> :bug: fix net interface sort

- lychee.toml
> chore: fix link.

- deploy/cloud/manifests/cockroachdb.yaml
- scripts/cloud/install.sh
> release: update sealos version in install.sh.

- docs/4.0/docs/self-hosting/sealos/installation.md
- docs/4.0/i18n/zh-Hans/self-hosting/sealos/installation.md
> docs: Update sealos version in self-hosting docs

- frontend/Dockerfile
- frontend/desktop/README.md
- frontend/packages/driver/package.json
- frontend/packages/ui/package.json
- frontend/pnpm-lock.yaml
- frontend/providers/applaunchpad/src/pages/app/detail/components/Pods.tsx
- frontend/providers/applaunchpad/src/pages/apps/components/appList.tsx
> style: launchpad displays monitoring values

- controllers/pkg/objectstorage/objectstorage.go
- controllers/pkg/utils/env/env.go
- controllers/resources/controllers/monitor_controller.go
- controllers/resources/main.go
> optimize query object storage metric

- frontend/desktop/src/stores/app.ts
- frontend/desktop/src/types/app.ts
> feat: desktop support controlling the size of the evoked window

- frontend/providers/dbprovider/src/utils/json2Yaml.ts
> fix:db podAntiAffinity Preferred

- scripts/cloud/install.sh
> chore: change mongo 4.0 to 4.4

- pkg/client-go/kubernetes/client.go
> fix: Delete unnecessary logs

- frontend/providers/applaunchpad/src/api/platform.ts
- frontend/providers/applaunchpad/src/hooks/useDetailDriver.tsx
- frontend/providers/applaunchpad/src/hooks/useDriver.tsx
- frontend/providers/applaunchpad/src/pages/_app.tsx
- frontend/providers/applaunchpad/src/pages/api/guide/getAccount.ts
- frontend/providers/applaunchpad/src/pages/api/platform/getEnv.ts
- frontend/providers/applaunchpad/src/pages/api/platform/getInitData.ts
- frontend/providers/applaunchpad/src/store/static.ts
- frontend/providers/applaunchpad/src/types/index.d.ts
> fix:launchpad config yaml boolean

- controllers/objectstorage/controllers/objectstoragebucket_controller.go
- controllers/objectstorage/controllers/objectstorageuser_controller.go
> add a key for a bucket

- frontend/providers/kubepanel/README.md
> chore(kubepanel):update README.md

- frontend/packages/client-sdk/src/app.ts
- frontend/providers/applaunchpad/next.config.js
- frontend/providers/applaunchpad/src/store/global.ts
- frontend/providers/cloudserver/next-i18next.config.js
- frontend/providers/cloudserver/next.config.js
- frontend/providers/cloudserver/tsconfig.json
- frontend/providers/costcenter/src/utils/tools.ts
- frontend/providers/invite/next.config.js
- frontend/providers/template/next.config.js
> fix(costcenter): remove bank account regex

- frontend/providers/objectstorage/deploy/manifests/deploy.yaml.tmpl
> fix objectstorage frontend deploy.yaml format error

- controllers/account/controllers/account_controller.go
- controllers/resources/controllers/monitor_controller.go
> monitor svc multi nodePort

- deploy/objectstorage/scripts/init.sh
- service/minio/deploy/manifests/deploy.yaml.tmpl
> Change object storage monitor service from prometheus to vm

- frontend/providers/cloudserver/public/locales/en/common.json
- frontend/providers/cloudserver/public/locales/zh/common.json
- frontend/providers/cloudserver/src/components/MyTable/index.tsx
- frontend/providers/cloudserver/src/pages/_app.tsx
- frontend/providers/cloudserver/src/pages/cloudserver/create/components/Form.tsx
- frontend/providers/cloudserver/src/pages/cloudserver/create/components/Header.tsx
- frontend/providers/cloudserver/src/pages/cloudserver/create/index.tsx
- frontend/providers/cloudserver/src/pages/cloudservers/components/List.tsx
- frontend/providers/cloudserver/src/types/cloudserver.ts
> fix:cloudserver bandwidth price display 

- frontend/providers/costcenter/src/components/billing/AmountDisplay.tsx
- frontend/providers/costcenter/src/components/billing/AppMenu.tsx
- frontend/providers/costcenter/src/components/billing/InOutTabPanel.tsx
- frontend/providers/costcenter/src/components/billing/NamespaceMenu.tsx
- frontend/providers/costcenter/src/components/billing/RechargeTabPanel.tsx
- frontend/providers/costcenter/src/components/billing/TransferTabPnel.tsx
- frontend/providers/costcenter/src/components/cost_overview/components/pieChart.tsx
- frontend/providers/costcenter/src/pages/api/billing/buget.ts
- frontend/providers/costcenter/src/pages/api/billing/getAppList.ts
- frontend/providers/costcenter/src/pages/api/billing/index.ts
- frontend/providers/costcenter/src/pages/billing/index.tsx
- frontend/providers/costcenter/src/stores/billing.ts
- frontend/providers/costcenter/src/types/billing.ts
- frontend/providers/workorder/next-i18next.config.js
- frontend/providers/workorder/next.config.js
- frontend/providers/workorder/tsconfig.json
> fix(costcenter): update amount by the query

- controllers/app/deploy/appexample/cr.yaml
- frontend/providers/adminer/deploy/manifests/appcr.yaml.tmpl
- frontend/providers/applaunchpad/deploy/manifests/appcr.yaml.tmpl
- frontend/providers/cloudserver/deploy/manifests/appcr.yaml.tmpl
- frontend/providers/costcenter/deploy/manifests/appcr.yaml.tmpl
- frontend/providers/cronjob/deploy/manifests/appcr.yaml.tmpl
- frontend/providers/dbprovider/deploy/manifests/appcr.yaml.tmpl
- frontend/providers/invite/deploy/manifests/appcr.yaml.tmpl
- frontend/providers/kubepanel/deploy/manifests/appcr.yaml.tmpl
- frontend/providers/license/deploy/manifests/appcr.yaml.tmpl
- frontend/providers/objectstorage/deploy/manifests/deploy.yaml.tmpl
- frontend/providers/terminal/deploy/manifests/appcr.yaml.tmpl
- frontend/providers/workorder/deploy/manifests/appcr.yaml.tmpl
- helm/sealos/charts/costcenter/templates/app.yaml
> chore: update app cr.

- controllers/account/controllers/debt_controller.go
- controllers/account/controllers/namespace_controller.go
- controllers/pkg/database/cockroach/accountv2.go
- controllers/pkg/database/interface.go
- controllers/resources/controllers/monitor_controller.go
> fix set account create region id

- README.md
> Add sealos framework

- frontend/.dockerignore
- frontend/desktop/src/services/enable.ts
- frontend/providers/applaunchpad/src/components/AppStatusTag/index.tsx
- frontend/providers/applaunchpad/src/pages/app/detail/components/ConfigMapDetailModal.tsx
- frontend/providers/applaunchpad/src/pages/app/detail/components/DelModal.tsx
- frontend/providers/applaunchpad/src/pages/app/detail/components/LogsModal.tsx
- frontend/providers/applaunchpad/src/pages/app/detail/components/MonitorModal.tsx
- frontend/providers/applaunchpad/src/pages/app/detail/components/PodDetailModal.tsx
- frontend/providers/applaunchpad/src/pages/app/detail/components/PodFileModal.tsx
- frontend/providers/applaunchpad/src/pages/app/edit/components/ConfigmapModal.tsx
- frontend/providers/applaunchpad/src/pages/app/edit/components/CustomAccessModal.tsx
- frontend/providers/applaunchpad/src/pages/app/edit/components/EditEnvs.tsx
- frontend/providers/applaunchpad/src/pages/app/edit/components/ErrorModal.tsx
- frontend/providers/applaunchpad/src/pages/app/edit/components/StoreModal.tsx
- frontend/providers/template/src/pages/deploy/index.tsx
- frontend/providers/workorder/public/locales/en/common.json
- frontend/providers/workorder/public/locales/zh/common.json
- frontend/providers/workorder/src/constants/workorder.ts
- frontend/providers/workorder/src/pages/api/ai/fastgpt.ts
- frontend/providers/workorder/src/pages/api/platform/feishu.ts
- frontend/providers/workorder/src/pages/workorder/detail/components/AppBaseInfo.tsx
> styles: launchpad AppStatusTag & workorder appendixs

- frontend/providers/costcenter/deploy/manifests/configmap.yaml.tmpl
- frontend/providers/costcenter/deploy/manifests/deploy.yaml.tmpl
> fix cost center frontend manifests

- deploy/cloud/manifests/mock-cert.yaml.tmpl
> change cert duration.

- frontend/providers/applaunchpad/src/pages/api/platform/getInitData.ts
- frontend/providers/applaunchpad/src/store/static.ts
- frontend/providers/workorder/src/api/user.ts
- frontend/providers/workorder/src/pages/api/auth/findById.ts
- frontend/providers/workorder/src/pages/workorder/detail/components/AppBaseInfo.tsx
- frontend/providers/workorder/src/pages/workorders/components/List.tsx
> fix: applaunchpad unhandledRejection promise

- scripts/cloud/install.sh
> fix pull cert-manager image in install.sh

- docs/4.0/docs/examples/baas/install-fireboom.md
- docs/4.0/i18n/zh-Hans/examples/baas/install-fireboom.md
> Update doc fireboom homepage link.

- docs/website/docusaurus.config.js
- docs/website/src/components/SaleBanner/index.scss
- docs/website/src/components/SaleBanner/index.tsx
- docs/website/src/hooks/useWindow.ts
- docs/website/src/pages/components/Header/index.phone.scss
- docs/website/src/pages/components/Header/index.scss
- docs/website/src/pages/index.tsx
> feat:docs add recharge event

- frontend/providers/applaunchpad/deploy/Kubefile
- frontend/providers/applaunchpad/deploy/manifests/deploy.yaml.tmpl
> chore: fix launchpad default config

- frontend/providers/workorder/src/pages/api/v1/migrate.ts
- frontend/providers/workorder/src/services/backend/auth.ts
- frontend/providers/workorder/src/services/db/workorder.ts
> feat: support workorder migrate

- docs/website/docusaurus.config.js
- docs/website/src/pages/components/Header/index.phone.scss
- docs/website/src/pages/components/Header/index.scss
- docs/website/src/pages/index.tsx
> revert: remove recharge event

- frontend/desktop/src/components/notification/index.tsx
- frontend/desktop/src/pages/api/desktop/getInstalledApps.ts
- frontend/desktop/src/pages/api/desktop/getResource.ts
- frontend/desktop/src/pages/api/notification/read.ts
- frontend/desktop/src/types/app.ts
> fix: desktop notifications forbidden error

- scripts/cloud/install.sh
> chore: remove kubeproxy.

- controllers/account/controllers/account_controller.go
- controllers/go.work.sum
- controllers/pkg/database/mongo/cvm.go
- controllers/pkg/types/cvm.go
> update cvm interface

- docs/blog/zh-Hans/2023/vm-sealos-create.md
> Replace 404 doc to official link.

- controllers/license/config/manager/manager.yaml
- controllers/license/deploy/manifests/deploy.yaml
> fix: license deploy

- controllers/account/controllers/debt_controller.go
- controllers/go.work.sum
> add email debt notification

- controllers/objectstorage/controllers/objectstorageuser_controller.go
> add quotaEnabled and defaultQuota env

- deploy/cloud/manifests/default_apps.yaml
- deploy/cloud/scripts/init.sh
> Add default install desktop apps.

- frontend/pnpm-lock.yaml
- frontend/providers/cronjob/next.config.js
- frontend/providers/cronjob/package.json
- frontend/providers/cronjob/src/pages/job/edit/components/Form.tsx
- frontend/providers/cronjob/src/pages/job/edit/components/index.module.scss
- frontend/providers/cronjob/src/styles/global.scss
- frontend/providers/cronjob/src/styles/reset.scss
> feat: impl cronjob show envs

- controllers/pkg/database/cockroach/accountv2.go
- controllers/pkg/database/interface.go
- controllers/pkg/types/dbquery.go
- controllers/pkg/types/global.go
- service/account/api/api.go
- service/account/common/account.go
- service/account/dao/interface.go
- service/account/dao/interface_test.go
- service/account/docs/docs.go
- service/account/docs/swagger.json
- service/account/docs/swagger.yaml
- service/account/helper/common.go
- service/account/helper/request.go
- service/account/router/router.go
- service/pkg/auth/authenticate.go
> feat: app cost svc

- controllers/license/internal/controller/license_controller.go
- controllers/license/internal/util/license/validate.go
> chore: fix license check.

- frontend/desktop/src/pages/_document.tsx
- frontend/desktop/src/pages/index.tsx
- frontend/desktop/src/pages/signin.tsx
> feat: desktop support configurable favicon

- pkg/runtime/kubernetes/upgrade.go
> fix: upgrade from k8s v1.26.x to v1.27.y, kubelet restart failed

- frontend/desktop/src/components/desktop_content/index.tsx
- frontend/desktop/src/constants/account.ts
- frontend/desktop/src/types/crd.ts
- service/license/src/services/backend/db/license.ts
> fix: ensure license issuance fields are of number type

- frontend/providers/dbprovider/public/locales/en/common.json
- frontend/providers/dbprovider/public/locales/zh/common.json
- frontend/providers/dbprovider/src/components/QuotaBox/index.tsx
> fix: db resource quota i18n

- docs/4.0/code.json
- docs/website/src/pages/components/Header/index.tsx
> docs: update header for landing page

- docs/website/src/pages/index.tsx
> docs: remove component showing product users 

- scripts/cloud/build-offline-tar.sh
- scripts/cloud/install.sh
> release: v5.0.0 release, update sealos version in install.sh. 

- .github/gh-bot.yml
> chore: add gh bot allowOps.

- frontend/providers/workorder/src/pages/api/cronjob/init.ts
- frontend/providers/workorder/src/pages/api/workorder/check.ts
- service/license/src/pages/cluster/components/ConfigForm.tsx
> update: Set default k8sVersion in license-system

- controllers/account/Makefile
- controllers/app/Makefile
- controllers/db/adminer/Makefile
- controllers/job/heartbeat/Makefile
- controllers/job/init/Makefile
- controllers/license/Makefile
- controllers/node/Makefile
- controllers/objectstorage/Makefile
- controllers/resources/Makefile
- controllers/terminal/Makefile
- controllers/user/Makefile
- service/account/Makefile
- webhooks/admission/Makefile
The size of sealos-cloud has been reduced from 1.5G to 1.4G.
> feat: strip bin and trimpath

- frontend/desktop/src/components/desktop_content/index.tsx
The file format is now [svg](https://github.com/labring/sealos/blob/main/frontend/desktop/public/images/bg-blue.svg).
> fix: bg file ext

- frontend/desktop/deploy/README.md
- frontend/desktop/deploy/manifests/configmap.yaml.tmpl
link: [frontend/desktop/data/config.yaml:26](https://github.com/labring/sealos/blob/main/frontend/desktop/data/config.yaml#L26)
> opt: desktop default config

- frontend/providers/workorder/src/pages/api/workorder/check.ts
- frontend/providers/workorder/src/services/db/workorder.ts
> fix: update work order status to pending

- docs/website/docusaurus.config.js
- docs/website/src/pages/index.tsx
> update:docs announcementBar

- controllers/terminal/controllers/terminal_controller.go
> Forward compatibility terminal label.

- docs/website/docusaurus.config.js
- docs/website/src/pages/index.tsx
> docs:update scripts

- frontend/desktop/src/pages/signin.tsx
- frontend/providers/workorder/src/pages/api/workorder/check.ts
- frontend/providers/workorder/src/pages/api/workorder/update.ts
- frontend/providers/workorder/src/types/workorder.ts
> update:desktop add scripts & workorder closedBy

- controllers/account/controllers/debt_controller.go
> fix read notice cause panic

- docs/website/src/pages/self-hosting/index.tsx
- frontend/desktop/src/api/platform.ts
- frontend/desktop/src/components/AppDock/index.module.css
- frontend/desktop/src/pages/index.tsx
- frontend/desktop/src/types/i18next.d.ts
- frontend/desktop/src/utils/i18n.ts
> fix: desktop right-click menu issue

- frontend/providers/applaunchpad/src/utils/adapt.ts
> fix: load env before fetching app details in launchpad

- docs/website/src/pages/self-hosting/header/index.tsx
- docs/website/src/pages/self-hosting/product/index.tsx
> feat:docs add 's' parameter for user source tracking

- docs/website/src/pages/self-hosting/header/index.tsx
> fix(docs):header title translation

- controllers/account/main.go
- controllers/pkg/resources/named.go
- controllers/pkg/resources/resources.go
- controllers/resources/controllers/monitor_controller.go
- controllers/resources/deploy/manifests/deploy.yaml
- controllers/resources/main.go
> DB backup monitoring

- frontend/providers/applaunchpad/src/pages/api/kubeFileSystem/upload.ts
- frontend/providers/applaunchpad/src/utils/kubeFileSystem.ts
> fix(launchpad): file upload in Kubernetes pods

- scripts/cloud/install.sh
add return in PROMPTS_EN/PROMPTS_CN
> fix: add return in PROMPTS_EN/PROMPTS_CN

- frontend/desktop/src/api/auth.ts
- frontend/desktop/src/components/signin/auth/usePassword.tsx
- frontend/desktop/src/components/signin/auth/useSms.tsx
- frontend/desktop/src/pages/api/auth/oauth/github/index.ts
- frontend/desktop/src/pages/api/auth/oauth/google/index.ts
- frontend/desktop/src/pages/api/auth/oauth/oauth2/index.ts
- frontend/desktop/src/pages/api/auth/oauth/wechat/index.ts
- frontend/desktop/src/pages/api/auth/password/index.ts
- frontend/desktop/src/pages/api/auth/phone/verify.ts
- frontend/desktop/src/pages/callback.tsx
- frontend/desktop/src/pages/index.tsx
- frontend/desktop/src/services/backend/globalAuth.ts
- frontend/desktop/src/services/backend/middleware/oauth.ts
- frontend/desktop/src/services/backend/middleware/sms.ts
- frontend/desktop/src/services/backend/svc/access.ts
- frontend/desktop/src/types/sem.ts
- frontend/desktop/src/utils/sessionConfig.ts
> feat(desktop): signup user sem data add keyword data

- controllers/pkg/database/interface.go
- controllers/pkg/database/mongo/account.go
- controllers/pkg/database/mongo/account_test.go
- controllers/pkg/objectstorage/metric_parser.go
- controllers/pkg/objectstorage/objectstorage.go
- controllers/pkg/objectstorage/objectstorage_test.go
- controllers/pkg/types/traffic.go
- controllers/resources/controllers/monitor_controller.go
- controllers/resources/main.go
> feat: get os traffic from minio

- scripts/cloud/install.sh
> Add backrepo

- service/exceptionmonitor/helper/monitor/database_backup_monitor.go
> add backuprepo

- frontend/providers/template/src/pages/api/getTemplateSource.ts
- frontend/providers/template/src/pages/api/updateRepo.ts
- frontend/providers/template/src/types/app.ts
- frontend/providers/template/src/utils/json-yaml.ts
fix defaults and inputs maybe empty and format code
> fix: defaults and inputs maybe empty

- docs/4.0/docs/self-hosting/sealos/QA.md
- docs/4.0/i18n/zh-Hans/self-hosting/sealos/QA.md
> add dify installation QA

- frontend/desktop/src/api/auth.ts
- frontend/desktop/src/api/platform.ts
- frontend/desktop/src/components/account/cost.tsx
- frontend/desktop/src/components/account/index.tsx
- frontend/desktop/src/components/account/trigger.tsx
- frontend/desktop/src/components/desktop_content/index.tsx
- frontend/desktop/src/components/signin/auth/usePassword.tsx
- frontend/desktop/src/components/signin/auth/useSms.tsx
- frontend/desktop/src/components/signin/index.tsx
- frontend/desktop/src/pages/api/auth/oauth/github/index.ts
- frontend/desktop/src/pages/api/auth/oauth/google/index.ts
- frontend/desktop/src/pages/api/auth/oauth/oauth2/index.ts
- frontend/desktop/src/pages/api/auth/oauth/wechat/index.ts
- frontend/desktop/src/pages/api/auth/password/index.ts
- frontend/desktop/src/pages/api/auth/phone/verify.ts
- frontend/desktop/src/pages/api/platform/uploadData.ts
- frontend/desktop/src/pages/callback.tsx
- frontend/desktop/src/services/backend/globalAuth.ts
- frontend/desktop/src/services/backend/middleware/oauth.ts
- frontend/desktop/src/services/backend/middleware/sms.ts
- frontend/desktop/src/services/backend/svc/access.ts
- frontend/providers/cronjob/src/services/backend/kubernetes.ts
> feat:desktop update sem

- frontend/providers/template/src/utils/json-yaml.ts
- frontend/providers/template/src/utils/template.ts
> fix: template undefined value

- controllers/devbox/internal/controller/devbox_controller.go
- controllers/go.work.sum
> fix: set AutomountServiceAccountToken to false

- frontend/Dockerfile
> fix(desktop):fix init database error

- service/account/api/api.go
- service/account/dao/interface.go
> optimize get app cost with index(owner+order_id)

- service/launchpad/request/req.go
- service/pkg/api/req.go
> update cpu/mem usage

- controllers/devbox/internal/controller/devbox_controller.go
- controllers/devbox/internal/controller/helper/devbox.go
> add generate public and private key

- controllers/devbox/internal/controller/devbox_controller.go
> add devbox pod hostname set to devbox name

- service/launchpad/request/req.go
> update launchpad cpu/mem usage

- controllers/pkg/database/cockroach/accountv2.go
- controllers/pkg/types/global.go
- service/account/api/api.go
- service/account/dao/interface.go
- service/account/dao/interface_test.go
- service/account/docs/docs.go
- service/account/docs/swagger.json
- service/account/docs/swagger.yaml
- service/account/helper/common.go
- service/account/helper/request.go
- service/account/router/router.go
> feat(account-service): add use giftcode

- controllers/devbox/internal/controller/devbox_controller.go
> update devbox to add delete resource.

- controllers/devbox/config/manager/manager.yaml
- controllers/devbox/config/rbac/role.yaml
- controllers/devbox/deploy/manifests/deploy.yaml.tmpl
- controllers/devbox/internal/controller/devbox_controller.go
>  add default rbac rules for devbox runtime and runtime class.

- controllers/devbox/api/v1alpha1/devbox_types.go
- controllers/devbox/config/crd/bases/devbox.sealos.io_devboxes.yaml
- controllers/devbox/config/rbac/role.yaml
- controllers/devbox/deploy/manifests/deploy.yaml.tmpl
- controllers/devbox/internal/controller/devbox_controller.go
> add additionalPrinterColumns for devbox.

- controllers/devbox/internal/controller/devbox_controller.go
> change label location

- frontend/desktop/src/components/signin/index.tsx
- frontend/desktop/src/pages/api/desktop/getResource.ts
> fix: resolve desktop monitoring issue

- controllers/devbox/api/v1alpha1/devbox_types.go
- controllers/devbox/cmd/main.go
- controllers/devbox/internal/controller/devbox_controller.go
> add extraEnv toleration affinity,ephemeral-storage limit

- frontend/pnpm-lock.yaml
- frontend/providers/applaunchpad/package.json
- frontend/providers/applaunchpad/public/locales/en/common.json
- frontend/providers/applaunchpad/public/locales/zh/common.json
- frontend/providers/applaunchpad/src/api/platform.ts
- frontend/providers/applaunchpad/src/pages/api/platform/getQuota.ts
- frontend/providers/applaunchpad/src/pages/api/platform/resourcePrice.ts
- frontend/providers/applaunchpad/src/pages/app/edit/index.tsx
- frontend/providers/applaunchpad/src/services/backend/kubernetes.ts
- frontend/providers/applaunchpad/src/store/user.ts
- frontend/providers/applaunchpad/src/utils/deployYaml2Json.ts
> refactor:Fetch Launchpad pricing from service API

- controllers/devbox/config/rbac/role.yaml
- controllers/devbox/deploy/manifests/rbac.yaml
- controllers/devbox/internal/controller/devbox_controller.go
> add devbox controller rbac.

- controllers/devbox/api/v1alpha1/devbox_types.go
- controllers/devbox/api/v1alpha1/devboxrelease_types.go
- controllers/devbox/config/crd/bases/devbox.sealos.io_devboxes.yaml
- controllers/devbox/config/crd/bases/devbox.sealos.io_runtimes.yaml
- controllers/devbox/config/rbac/role.yaml
- controllers/devbox/config/samples/devbox_v1alpha1_runtime.yaml
- controllers/devbox/config/samples/devbox_v1alpha1_runtimeclass.yaml
- controllers/devbox/deploy/manifests/deploy.yaml.tmpl
- controllers/devbox/internal/controller/devbox_controller.go
> fix devbox get runtime.

- controllers/devbox/api/v1alpha1/devbox_types.go
- controllers/devbox/config/crd/bases/devbox.sealos.io_devboxes.yaml
- controllers/devbox/config/samples/devbox_v1alpha1_devbox.yaml
- controllers/devbox/deploy/manifests/deploy.yaml.tmpl
- controllers/devbox/internal/controller/devbox_controller.go
- controllers/devbox/internal/controller/helper/devbox.go
> add devbox default runtime ref namespace to devbox-system.

- controllers/devbox/internal/controller/helper/devbox.go
> fix ssh volume bug

- frontend/providers/applaunchpad/src/pages/api/monitor/getMonitorData.ts
- frontend/providers/applaunchpad/src/pages/api/platform/getInitData.ts
- frontend/providers/applaunchpad/src/pages/api/platform/getQuota.ts
- frontend/providers/applaunchpad/src/pages/api/platform/resourcePrice.ts
- frontend/providers/applaunchpad/src/pages/app/edit/components/Form.tsx
- frontend/providers/applaunchpad/src/services/backend/kubernetes.ts
- frontend/providers/applaunchpad/src/types/index.d.ts
- frontend/providers/template/src/components/Select/index.tsx
- frontend/providers/template/src/pages/deploy/components/Form.tsx
> fix: adjust GPU quota for launchpad

- controllers/devbox/internal/controller/devbox_controller.go
> add devbox image random

- service/launchpad/request/req.go
> update launchpad test

- controllers/devbox/internal/controller/devbox_controller.go
> add service port

- controllers/devbox/internal/controller/utils/registry/client.go
> fix  release bug

- service/launchpad/request/req.go
> update launchpad single

- controllers/devbox/go.mod
- controllers/devbox/internal/controller/devbox_controller.go
> remove pod finalizer

- .github/workflows/check-format-code.yml
> bump format go version

- frontend/providers/dbprovider/src/pages/api/getSecretByName.ts
- frontend/providers/dbprovider/src/pages/api/platform/resourcePrice.ts
- frontend/providers/dbprovider/src/pages/db/detail/components/AppBaseInfo.tsx
- frontend/providers/dbprovider/src/services/backend/response.ts
> feat: add Kafka and Milvus connection string support

- controllers/devbox/Makefile
- controllers/devbox/deploy/manifests/deploy.yaml.tmpl
- controllers/devbox/go.mod
- controllers/devbox/internal/controller/devbox_controller.go
- controllers/devbox/internal/controller/helper/devbox.go
- controllers/go.work
> Fix devbox podPhase logic and license in deploy.yaml.tmpl

- frontend/desktop/src/pages/api/desktop/getBilling.ts
- frontend/providers/applaunchpad/src/api/platform.ts
- frontend/providers/applaunchpad/src/pages/api/platform/checkPermission.ts
- frontend/providers/applaunchpad/src/pages/api/platform/getInitData.ts
- frontend/providers/applaunchpad/src/pages/api/platform/getQuota.ts
- frontend/providers/applaunchpad/src/pages/api/platform/resourcePrice.ts
- frontend/providers/applaunchpad/src/pages/app/edit/index.tsx
- frontend/providers/applaunchpad/src/store/user.ts
- frontend/providers/applaunchpad/src/types/index.d.ts
> fix:permission change check for launchpad

- scripts/cloud/install.sh
> WIP: Replace `ingress-nginx` with `higress`.

- frontend/providers/objectstorage/src/pages/api/site/openHost.ts
> fix(objectstorage): Fix site hosting errors for domains

- controllers/pkg/resources/named.go
- controllers/pkg/resources/resources.go
> add devbox monitor

- pkg/filesystem/rootfs/rootfs_default.go
fix : https://github.com/labring/sealos/issues/5065
https://github.com/labring/sealos/issues/4962
https://github.com/labring/sealos/issues/4942
> fix: `etc/sealos/.env: line 1: syntax error near unexpected token `newline'`

- frontend/providers/applaunchpad/src/pages/app/detail/components/DelModal.tsx
- frontend/providers/applaunchpad/src/utils/kubeFileSystem.ts
> fix: improve timezone handling in Kubernetes pods

- deploy/objectstorage/Kubefile
- deploy/objectstorage/README.md
- deploy/objectstorage/etc/minio/policy/kubeblocks.json
- deploy/objectstorage/manifests/minio/deploy.yaml.tmpl
- deploy/objectstorage/scripts/minio.sh
> Update objectstorage cloud image

- frontend/desktop/src/pages/api/desktop/getBilling.ts
- frontend/desktop/src/services/backend/auth.ts
- frontend/desktop/src/types/system.ts
> chrome(desktop):update token

- frontend/providers/applaunchpad/data/config.yaml
- frontend/providers/applaunchpad/src/constants/editApp.ts
- frontend/providers/applaunchpad/src/pages/_app.tsx
- frontend/providers/applaunchpad/src/pages/api/platform/getInitData.ts
- frontend/providers/applaunchpad/src/store/static.ts
- frontend/providers/applaunchpad/src/types/index.d.ts
- frontend/providers/dbprovider/deploy/manifests/deploy.yaml.tmpl
- frontend/providers/dbprovider/src/pages/_app.tsx
- frontend/providers/dbprovider/src/pages/api/getEnv.ts
- frontend/providers/dbprovider/src/store/env.ts
> fix:launchpad domain for internal app call listener

- staging/src/github.com/labring/image-cri-shim/pkg/server/utils.go
miss  https://github.com/labring/sealos/pull/2834/files for images @sha256 process.
> :bug: fix image sha256

- controllers/devbox/api/v1alpha1/runtime_types.go
- controllers/devbox/api/v1alpha1/zz_generated.deepcopy.go
- controllers/devbox/config/crd/bases/devbox.sealos.io_runtimes.yaml
- controllers/devbox/config/manager/manager.yaml
- controllers/devbox/config/samples/devbox_v1alpha1_runtime.yaml
- controllers/devbox/deploy/manifests/deploy.yaml.tmpl
- controllers/devbox/deploy/manifests/rbac.yaml
- controllers/devbox/internal/controller/devbox_controller.go
> add devbox runtime app port.

- controllers/job/init/internal/util/database/user.go
> fix init user

- service/account/common/account.go
> fix get default property

- controllers/devbox/internal/controller/devbox_controller.go
> devbox pod ignore extra ports.

- deploy/cloud/scripts/init.sh
- frontend/desktop/deploy/manifests/configmap.yaml.tmpl
- frontend/desktop/deploy/manifests/rbac.yaml
- frontend/providers/costcenter/deploy/Kubefile
- frontend/providers/costcenter/deploy/manifests/configmap.yaml.tmpl
> fix desktop and costcenter configs.

- controllers/objectstorage/controllers/objectstorageuser_controller.go
> feat: sync resourcequota objectstorage/size status used

- deploy/cloud/scripts/init.sh
> fix scripts: init account jwt secret

- controllers/devbox/.gitignore
- controllers/devbox/api/v1alpha1/devbox_types.go
- controllers/devbox/config/crd/bases/devbox.sealos.io_devboxes.yaml
- controllers/devbox/deploy/manifests/deploy.yaml.tmpl
- controllers/devbox/internal/controller/devbox_controller.go
- controllers/devbox/internal/controller/helper/devbox.go
> fix devbox phase generate.

- frontend/desktop/src/components/account/AccountCenter/mergeUser/NeedToMergeModal.tsx
- frontend/desktop/src/services/backend/cronjob/mergeUserCr.ts
> fix(desktop):fix merge user

- controllers/devbox/cmd/main.go
> devbox cache improve.

- .github/workflows/cloud-release.yml
- scripts/cloud/build-offline-tar.sh
> fix build offline scripts and ci.

- docs/4.0/docs/self-hosting/sealos/installation.md
- docs/5.0/docs/developer-guide/sealos/installation.md
- scripts/cloud/install.sh
> v5.0.1 docs.

- .github/workflows/cloud-release.yml
> ci: cloud release add self hosted runner.

- .github/workflows/cloud-release.yml
> fix cloud release ci.

- scripts/cloud/install.sh
fix higress-ca-root-cert appearing in other namespaces
> fix: upgrade higress to 2.0.1

- frontend/providers/devbox/deploy/manifests/appcr.yaml.tmpl
> Unify devbox app-cr name.

- pkg/bootstrap/context.go
#5007 
command `sealos reset` will panic if set --masters or --nodes
> fix: sealos reset panic

- frontend/desktop/src/components/account/RealNameModal.tsx
> feat(desktop): hidden enterprise auth

- deploy/objectstorage/Kubefile
- deploy/objectstorage/README.md
> fix minioKubeblocksPassword env error

- frontend/providers/dbprovider/src/pages/api/platform/resourcePrice.ts
- frontend/providers/dbprovider/src/pages/db/detail/components/AppBaseInfo.tsx
> fix: add dbType to getDBSecret query parameters

- frontend/desktop/public/locales/en/common.json
- frontend/desktop/public/locales/zh/common.json
- frontend/desktop/src/components/team/DissolveTeam.tsx
- frontend/desktop/src/components/team/ModifyRole.tsx
- frontend/desktop/src/constants/account.ts
- frontend/desktop/src/pages/WorkspaceInvite.tsx
- frontend/desktop/src/pages/api/auth/namespace/abdicate.ts
- frontend/desktop/src/services/backend/svc/mergeUser.ts
- frontend/desktop/src/types/team.ts
- frontend/providers/costcenter/public/locales/en/applist.json
- frontend/providers/costcenter/public/locales/zh/applist.json
> fix(desktop): fix operationRequest 

- .github/workflows/cloud-release.yml
> fix: semgrep ci.

- docs/5.0/i18n/zh-Hans/developer-guide/sealos/installation.md
> docs: add v5.0.1 zh-hans docs.

- controllers/devbox/api/v1alpha1/runtime_types.go
- controllers/devbox/config/crd/bases/devbox.sealos.io_runtimes.yaml
- controllers/devbox/deploy/manifests/deploy.yaml.tmpl
- controllers/devbox/internal/controller/devbox_controller.go
> feat:  add runtime version and state.

- controllers/objectstorage/api/v1/objectstorageuser_types.go
- controllers/objectstorage/config/crd/bases/objectstorage.sealos.io_objectstoragebuckets.yaml
- controllers/objectstorage/config/crd/bases/objectstorage.sealos.io_objectstorageusers.yaml
- controllers/objectstorage/config/rbac/role.yaml
- controllers/objectstorage/controllers/objectstorageuser_controller.go
> feat: reset object storage secret key

- docs/website/docusaurus.config.js
- docs/website/src/components/SaleBanner/index.tsx
- docs/website/src/pages/components/Header/index.scss
- docs/website/src/pages/index.tsx
> feat: add 1024 activity banner

- controllers/objectstorage/config/crd/bases/objectstorage.sealos.io_objectstoragebuckets.yaml
- controllers/objectstorage/config/crd/bases/objectstorage.sealos.io_objectstorageusers.yaml
- controllers/objectstorage/config/rbac/role.yaml
> fix: add license to objectstorage yaml config

- frontend/providers/costcenter/src/components/RechargeModal.tsx
> style(costcenter): fix ratio

- frontend/desktop/src/pages/api/auth/email/bind/verify.ts
- frontend/desktop/src/pages/api/auth/email/changeBinding/newSms.ts
- frontend/desktop/src/pages/api/auth/email/changeBinding/oldSms.ts
- frontend/desktop/src/pages/api/auth/email/changeBinding/verifyNew.ts
- frontend/desktop/src/pages/api/auth/email/changeBinding/verifyOld.ts
- frontend/desktop/src/pages/api/auth/email/unbind/sms.ts
- frontend/desktop/src/pages/api/auth/email/unbind/verify.ts
- frontend/desktop/src/pages/api/auth/info.ts
- frontend/desktop/src/services/enable.ts
> fix(desktop):fix email binding

- frontend/providers/applaunchpad/src/constants/editApp.ts
- frontend/providers/template/src/components/layout/appmenu.tsx
> Fix: hide language switch button in template

- frontend/desktop/src/api/platform.ts
- frontend/providers/workorder/src/constants/workorder.ts
- frontend/providers/workorder/src/types/workorder.ts
> feat: add two types in workorder

- docs/website/docusaurus.config.js
> docs:update google script

- controllers/devbox/internal/controller/devbox_controller.go
- controllers/devbox/internal/controller/helper/devbox.go
> fix: change ssh key mode, mount key by subpath.

- frontend/desktop/src/components/desktop_content/index.tsx
- frontend/desktop/src/pages/index.tsx
- frontend/providers/applaunchpad/src/pages/_app.tsx
- frontend/providers/template/src/api/platform.ts
- frontend/providers/template/src/pages/_app.tsx
- frontend/providers/template/src/pages/api/listTemplate.ts
- frontend/providers/template/src/pages/deploy/components/Header.tsx
- frontend/providers/template/src/pages/deploy/components/ReadMe.tsx
- frontend/providers/template/src/pages/index.tsx
- frontend/providers/template/src/store/config.ts
- frontend/providers/template/src/types/app.ts
- frontend/providers/template/src/utils/json-yaml.ts
> feat:support template i18n

- controllers/objectstorage/config/rbac/role.yaml
- controllers/objectstorage/controllers/objectstorageuser_controller.go
> update object storage role

- controllers/devbox/internal/controller/helper/devbox.go
> fix: use container status to set commit status.

- service/pkg/auth/authenticate.go
> monitor server check auth with `get` verb

- extensions/ide/vscode/devbox/package-lock.json
- extensions/ide/vscode/devbox/package.json
- extensions/ide/vscode/devbox/src/commands/remoteConnector.ts
> feat: to add simple backup for vscode plugin

- docs/website/docusaurus.config.js
> Docs: update blog url

- frontend/providers/devbox/app/[lang]/(platform)/devbox/create/page.tsx
> fix:  a bug of creating devbox form not show runtimeVersion and network

- docs/5.0/i18n/zh-Hans/developer-guide/system-design/system-application.md
> fix: 文档错别字错误

- .github/workflows/ci-patch-image.yml
- .github/workflows/cloud-release.yml
- .github/workflows/cloud.yml
- .github/workflows/controllers.yml
- .github/workflows/frontend.yml
- .github/workflows/import-save-sealos.yml
- .github/workflows/objectstorage.yaml
- .github/workflows/services.yml
https://github.com/actions/upload-artifact/issues/506#issuecomment-2093302327
> fix: actions upload artifactv4 name

- extensions/ide/vscode/devbox/CHANGELOG.md
- extensions/ide/vscode/devbox/package.json
- extensions/ide/vscode/devbox/src/commands/remoteConnector.ts
- extensions/ide/vscode/devbox/src/providers/DevboxListViewProvider.ts
- extensions/ide/vscode/devbox/src/utils/remoteSSHConfig.ts
> fix: devboxList not found “devbox_config” cause plugin activating error

- extensions/ide/vscode/devbox/l10n/bundle.l10n.zh-CN.json
- extensions/ide/vscode/devbox/src/utils/handleUri.ts
> fix: plugin i18n bug

- scripts/cloud/install.sh
> update sealos mongo version to 6.0

- frontend/providers/devbox/stores/ide.ts
> fix: IDE button not show bug

- docs/5.0/i18n/zh-Hans/quick-start/examples/programming-languages/Quick installation of Java Apps.md
> Update Quick installation of Java Apps.md（修复一个微小的 bug）

- controllers/account/controllers/account_controller.go
- controllers/pkg/resources/resources.go
> support custom limitrange

- extensions/ide/vscode/devbox/l10n/bundle.l10n.zh-CN.json
- extensions/ide/vscode/devbox/src/providers/DevboxListViewProvider.ts
> fix: devbox plugin refresh performance bug

- frontend/providers/applaunchpad/data/config.yaml
- frontend/providers/applaunchpad/src/pages/api/platform/getInitData.ts
- frontend/providers/applaunchpad/src/pages/app/edit/components/Form.tsx
- frontend/providers/applaunchpad/src/store/static.ts
- frontend/providers/applaunchpad/src/types/app.d.ts
- frontend/providers/applaunchpad/src/utils/adapt.ts
- frontend/providers/applaunchpad/src/utils/deployYaml2Json.ts
> feat: add GPU horizontal pod autoscaling for launchpad

- frontend/providers/devbox/app/[lang]/(platform)/devbox/detail/[name]/components/Header.tsx
- frontend/providers/devbox/stores/ide.ts
> fix: devbox detail icon show bug

- frontend/desktop/src/pages/api/account/faceIdRealNameAuthCallback.ts
> fix: reward for real name authentication

- frontend/providers/costcenter/src/components/CurrencySymbol.tsx
- frontend/providers/costcenter/src/components/RechargeModal.tsx
> feat:support ratio 0

- deploy/objectstorage/README.md
> fix: update clusterrole

- .github/workflows/objectstorage.yaml
> fix: update cloud objectstorage workflow

- frontend/providers/costcenter/public/locales/en/common.json
- frontend/providers/costcenter/public/locales/zh/common.json
- frontend/providers/costcenter/src/components/CurrencySymbol.tsx
- frontend/providers/costcenter/src/components/RechargeModal.tsx
- frontend/providers/costcenter/src/components/outerLink.tsx
- frontend/providers/costcenter/src/styles/chakraTheme.ts
> fix(costcenter):price icon

- frontend/providers/devbox/components/modals/AppSelectModal.tsx
> fix: devbox update samename bug

- .github/workflows/deploy-docs-preview.yml
- .github/workflows/deploy-docs-site.yml
- docs/website/vercel.json
> Docs: add vercel.json

- docs/website/docusaurus.config.js
- docs/website/package-lock.json
- docs/website/yarn.lock
> docs(website): Update announcement bar with dynamic content

- docs/website/docusaurus.config.js
> refactor(docs): simplify announcement bar configuration

- controllers/account/controllers/payment_controller.go
> payment support custom describe

- frontend/providers/applaunchpad/src/pages/api/pauseApp.ts
- frontend/providers/applaunchpad/src/pages/api/startApp.ts
> fix: launchpad ingress

- frontend/providers/devbox/app/[lang]/(platform)/devbox/create/components/form/BasicConfiguration/TemplateRepositorySelector/index.tsx
- frontend/providers/devbox/app/[lang]/(platform)/template/updateTemplate/EditTemplateModal.tsx
- frontend/providers/devbox/app/api/auth/init/route.ts
- frontend/providers/devbox/app/api/templateRepository/delete/route.ts
- frontend/providers/devbox/app/api/templateRepository/get/route.ts
- frontend/providers/devbox/app/api/templateRepository/list/route.ts
- frontend/providers/devbox/app/api/templateRepository/listOfficial/route.ts
- frontend/providers/devbox/app/api/templateRepository/template/getConfig/route.ts
- frontend/providers/devbox/app/api/templateRepository/template/list/route.ts
- frontend/providers/devbox/app/api/templateRepository/update/route.ts
- frontend/providers/devbox/app/api/templateRepository/withTemplate/create/route.ts
- frontend/providers/devbox/app/api/templateRepository/withTemplate/update/route.ts
- frontend/providers/devbox/prisma/migrations/20250103095011_region_update/migration.sql
- frontend/providers/devbox/prisma/schema.prisma
- frontend/providers/devbox/utils/env.ts
> fix(devbox):fix multi-region

- README.md
- README_zh.md
- docs/4.0/docs/Community.md
- docs/4.0/i18n/zh-Hans/Community.md
- docs/5.0/docs/community.md
- docs/5.0/i18n/zh-Hans/community.md
- lychee.toml
Updated the Twitter handle from @sealosio to @Sailos_io across multiple files.
> chore(twitter): update Twitter handle to @Sailos_io

- frontend/providers/devbox/app/[lang]/(platform)/devbox/detail/[name]/components/Version.tsx
- frontend/providers/devbox/app/api/v1/getDevboxDetail/route.ts
- frontend/providers/devbox/types/k8s.d.ts
- frontend/providers/devbox/utils/adapt.ts
> fix(devbox): fix invaild devbox cr

- frontend/providers/devbox/services/backend/response.ts
- frontend/providers/devbox/utils/vaildate.ts
> Fix devbox name regx

- frontend/providers/devbox/components/modals/JetbrainsGuideModal.tsx
> fix(devbox): jb bug download circle

- controllers/account/controllers/account_controller.go
- controllers/account/controllers/billing_controller.go
- controllers/account/controllers/debt_controller.go
- controllers/account/main.go
- controllers/pkg/common/account.go
- controllers/pkg/database/interface.go
- controllers/pkg/database/mongo/account.go
- controllers/pkg/database/mongo/account_test.go
- controllers/pkg/resources/resources.go
1. Remove the original controller logic and use manager timed tasks to process billing
2. Change the processing logic from the original mongo aggregate to batch task memory processing.
> Optimize billing efficiency

- frontend/Dockerfile
- frontend/providers/invite/public/locales/en/common.json
- frontend/providers/invite/public/locales/zh/common.json
- frontend/providers/invite/src/pages/index.tsx
> feat: update invite page and adjust cashback

- controllers/devbox/cmd/main.go
- controllers/devbox/internal/controller/devbox_controller.go
> feat: devbox  controller concurrent and config qps flag.

- frontend/desktop/src/pages/api/account/enterpriseRealName.ts
- frontend/desktop/src/pages/api/account/enterpriseRealNameVerify.ts
- frontend/desktop/src/pages/api/account/faceIdRealNameAuthCallback.ts
- frontend/desktop/src/utils/getInviteInfo.ts
> feat(desktop): Add Real Name Invitee Rewards

- .github/workflows/frontend.yml
> update frontend ci

- frontend/providers/devbox/deploy/manifests/ingress.yaml.tmpl
frontend devbox ingress host is not correct
ref issue: #5332
> fix frontend devbox ingress host

- controllers/pkg/database/mongo/account.go
> fix skip llm token

- frontend/providers/devbox/app/[lang]/(platform)/(home)/components/DevboxListContainer.tsx
- frontend/providers/devbox/components/PodLineChart.tsx
> fix: devboxList monitor show bug

- controllers/devbox/internal/controller/devboxrelease_controller.go
- controllers/devbox/internal/controller/helper/devbox.go
> fix: devbox release tag use last predicated success commit.

- frontend/providers/devbox/app/[lang]/(platform)/devbox/create/components/form/BasicConfiguration/TemplateRepositorySelector/index.tsx
> fix(devbox): desktop call devbox runtime bug

- frontend/providers/dbprovider/src/pages/api/delDBByName.ts
- frontend/providers/template/src/pages/index.tsx
- frontend/providers/template/src/types/index.ts
- frontend/providers/template/src/utils/tools.ts
> fix: database deletion policy

- extensions/ide/vscode/devbox/CHANGELOG.md
- extensions/ide/vscode/devbox/package.json
- extensions/ide/vscode/devbox/src/utils/remoteSSHConfig.ts
> fix(devbox/plugin): windsurf can not open

- controllers/objectstorage/deploy/manifests/deploy.yaml.tmpl
> fix deploy.yaml

- docs/website/src/pages/self-hosting/plan/index.tsx
- frontend/desktop/src/components/task/useDriver.tsx
- frontend/providers/cronjob/src/utils/json2Yaml.ts
- frontend/providers/dbprovider/src/pages/db/detail/components/AppBaseInfo.tsx
- frontend/providers/dbprovider/src/pages/dbs/components/dbList.tsx
- frontend/providers/dbprovider/src/utils/adapt.ts
> fix: docs select style & cronjob bug, desktop guide bug

- frontend/providers/devbox/components/modals/JetbrainsGuideModal.tsx
> fix(devbox): JB multiple clicks will result in multiple cn

- README.md
- README_zh.md
> chore: Update ReadMe

- frontend/desktop/src/components/signin/Captcha/index.tsx
- frontend/desktop/src/components/signin/auth/useSms.tsx
- frontend/desktop/src/components/signin/index.tsx
- frontend/desktop/src/pages/api/auth/phone/sms.ts
- frontend/desktop/src/services/backend/middleware/sms.ts
- frontend/desktop/src/stores/captcha.ts
> fix(desktop): twice captcha

- controllers/job/init/internal/util/database/user.go
> feat: make admin user id fixed

- frontend/desktop/src/components/account/AccountCenter/SmsModify/SmsBind.tsx
- frontend/desktop/src/components/account/AccountCenter/index.tsx
- frontend/desktop/src/pages/api/platform/getAuthConfig.ts
- frontend/desktop/src/services/backend/sms.ts
- frontend/desktop/src/services/enable.ts
- frontend/desktop/src/types/system.ts
> fix(frontend):perf email env

- controllers/account/controllers/billing_controller.go
> fix repetitive execution

- frontend/providers/template/src/utils/json-yaml.ts
> fix: template yaml separator regex

- frontend/providers/devbox/constants/scripts.ts
> fix(devbox): ssh script bug

- controllers/user/controllers/user_controller.go
- controllers/user/main.go
> fix: user controller with event filter.

- controllers/devbox/cmd/main.go
- controllers/devbox/internal/controller/devbox_controller.go
> fix: devbox controller with event filter.

- .github/workflows/e2e_test_core.yml
- .github/workflows/e2e_test_core_k3s.yml
- .github/workflows/e2e_test_image_cri_shim.yml
> fix the workflow's paths

- controllers/pkg/pay/stripe_payment.go
> feat: Allow coupons on Stripe checkout

- lifecycle/README.md
> add lifecycle readme

- extensions/ide/vscode/devbox/.prettierrc.json
- extensions/ide/vscode/devbox/CHANGELOG.md
- extensions/ide/vscode/devbox/package.json
- extensions/ide/vscode/devbox/src/commands/remoteConnector.ts
- extensions/ide/vscode/devbox/src/utils/handleUri.ts
- extensions/ide/vscode/devbox/src/utils/remoteSSHConfig.ts
- frontend/providers/devbox/components/IDEButton.tsx
- frontend/providers/devbox/stores/ide.ts
> feat: trae cn support web&plugin

- frontend/providers/applaunchpad/public/locales/en/common.json
- frontend/providers/applaunchpad/public/locales/zh/common.json
- frontend/providers/applaunchpad/src/components/app/detail/index/AppMainInfo.tsx
> feat(applaunchpad): network tooltip

- frontend/providers/devbox/app/[lang]/(platform)/devbox/detail/[name]/components/MainBody.tsx
- frontend/providers/devbox/message/en.json
> fix(devbox): typo bug 

- frontend/providers/devbox/deploy/manifests/deploy.yaml.tmpl
- frontend/providers/devbox/deploy/manifests/ingress.yaml.tmpl
> chore(devbox): deploy yaml update

- frontend/providers/devbox/app/[lang]/(platform)/devbox/detail/[name]/components/MainBody.tsx
- frontend/providers/devbox/app/api/checkReady/route.ts
- frontend/providers/devbox/components/IDEButton.tsx
> style&fix(devbox): ui adjust and network refetch bug

- frontend/providers/devbox/app/[lang]/(platform)/devbox/detail/[name]/components/BasicInfo.tsx
- frontend/providers/devbox/components/modals/SshConnectModal.tsx
- frontend/providers/devbox/constants/scripts.ts
- frontend/providers/devbox/message/en.json
- frontend/providers/devbox/message/zh.json
> fix(devbox): ssh connnect info adjust

- frontend/desktop/src/pages/api/auth/namespace/details.ts
- frontend/desktop/src/services/backend/cronjob/deleteUserCr.ts
- frontend/desktop/src/services/backend/kubernetes/admin.ts
> fix(desktop): update-namespace-error

- frontend/desktop/src/components/desktop_content/index.tsx
- frontend/desktop/src/components/task/taskModal.tsx
> fix(deskop): fix real name error when account is not exists

- .github/workflows/bot-cherry-pick.yml
- .github/workflows/check-coverage.yml
- .github/workflows/check-format-code.yml
- .github/workflows/check-license.yml
- .github/workflows/check-link-error.yml
- .github/workflows/ci-patch-image.yml
- .github/workflows/cloud.yml
- .github/workflows/controllers.yml
- .github/workflows/deploy-docs-preview.yml
- .github/workflows/deploy-docs-site.yml
- .github/workflows/e2e_k3s_multi_node.yml
- .github/workflows/e2e_k8s_multi_node.yml
- .github/workflows/e2e_test_core.yml
- .github/workflows/e2e_test_core_k3s.yml
- .github/workflows/frontend.yml
- .github/workflows/import-patch-image.yml
- .github/workflows/objectstorage.yaml
- .github/workflows/release.yml
- .github/workflows/services.yml
- .github/workflows/webhooks.yml
> fix: fix run-shell-injection in workflows

- frontend/providers/devbox/app/[lang]/(platform)/devbox/detail/[name]/components/Version.tsx
> fix(devbox): devbox release protocol bug caused by applaunchpad 

- .github/workflows/bot-labels.yml
> Test update remove GH_PAT at labels bot.

- .github/workflows/bot-labels.yml
> Revert actions/labeler@v4

- .github/workflows/deploy-docs-preview.yml
> Try fix doc preview.

- .github/workflows/check-link-error.yml
> Try fix check-linter.

- .github/workflows/check-link-error.yml
> fix GITHUB_TOKEN permissions.

- .github/workflows/bot-auto-cherry-pick.yml
- .github/workflows/bot-cherry-pick.yml
- .github/workflows/bot-issues-translator.yml
- .github/workflows/bot-labels.yml
- .github/workflows/bot.yml
- .github/workflows/check-link-error.yml
- .github/workflows/ci-patch-image.yml
- .github/workflows/cloud.yml
- .github/workflows/controllers.yml
- .github/workflows/deploy-docs-preview.yml
- .github/workflows/docs-site-image.yml
- .github/workflows/e2e_k3s_multi_node.yml
- .github/workflows/e2e_k8s_multi_node.yml
- .github/workflows/frontend.yml
- .github/workflows/objectstorage.yaml
- .github/workflows/release.yml
- .github/workflows/services.yml
- .github/workflows/sync_code.yml
- .github/workflows/sync_docs.yml
- .github/workflows/webhooks.yml
Solve: https://github.com/labring/sealos/issues/5516
> make workflows less permissive

- controllers/devbox/api/v1alpha1/devbox_types.go
- controllers/devbox/config/crd/bases/devbox.sealos.io_devboxes.yaml
- controllers/devbox/internal/controller/devbox_controller.go
- controllers/devbox/internal/controller/helper/devbox.go
> feat: devbox cold shutdown.

- controllers/devbox/internal/controller/devboxrelease_controller.go
> fix: devbox release target image tag

- frontend/providers/devbox/utils/adapt.ts
> fix(devbox): release status perf

- frontend/providers/applaunchpad/src/pages/api/checkReady.ts
- frontend/providers/devbox/app/api/checkReady/route.ts
> fix(devbox&applaunchapd): network fetch bug 

- CONTRIBUTING.md
> FIx doc doc.

- frontend/providers/devbox/app/api/templateRepository/withTemplate/create/route.ts
- frontend/providers/devbox/app/api/templateRepository/withTemplate/update/route.ts
> fix(devbox): transform to template bug

- controllers/devbox/deploy/manifests/deploy.yaml.tmpl
> update: devbox deploy.yaml.tmpl to build latest cluster image

- controllers/devbox/internal/controller/devbox_controller.go
> fix: devbox pod create logic should not retry on conflict, just return.

- .github/workflows/frontend.yml
> fix: frontend ci

- frontend/providers/applaunchpad/src/pages/app/edit/index.tsx
- frontend/providers/dbprovider/src/pages/db/edit/index.tsx
- frontend/providers/dbprovider/src/pages/db/migrate/index.tsx
- frontend/providers/devbox/app/[lang]/(platform)/devbox/create/page.tsx
- frontend/providers/template/src/pages/deploy/index.tsx
> feat: apps delete quote check

- frontend/providers/applaunchpad/src/pages/api/updateApp.ts
> fix: service nodeport modification issue

- frontend/providers/template/src/pages/api/updateRepo.ts
- frontend/providers/template/src/pages/deploy/index.tsx
- frontend/providers/template/src/utils/usage.ts
> fix: add database billing in template system

- controllers/account/api/v1/debt_webhook.go
- controllers/account/main.go
- controllers/pkg/utils/maps/ttl_map.go
- controllers/pkg/utils/maps/ttl_map_test.go
> debt webhook cache user account info

- controllers/account/controllers/debt.go
> fix debt send msg

- frontend/desktop/src/services/backend/cronjob/mergeUserCr.ts
Update mergeUserCr to correctly handle user workspace roles during the merge process. This includes creating event logs for each workspace and ensuring proper role assignment. Also, improve error handling and log formatting for better traceability.
> Refactor mergeUserCr to handle user workspace roles

- controllers/pkg/database/cockroach/accountv2.go
> fix assignment user uid to UserQueryOpts

- controllers/pkg/types/subscription.go
- service/account/api/subscription_process.go
> fix skip abnormal user subscriptions

- controllers/pkg/resources/resources.go
> support pods/service limit

- controllers/account/controllers/subscription.go
- controllers/account/controllers/subscription_test.go
- controllers/account/controllers/user_traffic_controller.go
- controllers/account/controllers/utils/subscription_cache.go
- controllers/account/main.go
- controllers/pkg/database/cockroach/accountv2.go
- controllers/pkg/database/interface.go
- controllers/pkg/database/mongo/traffic.go
- controllers/pkg/database/mongo/traffic_test.go
- controllers/pkg/types/traffic.go
- controllers/resources/controllers/network_controller.go
- controllers/resources/deploy/manifests/deploy.yaml
- controllers/resources/main.go
- service/account/api/admin.go
- service/account/api/api.go
- service/account/api/flush.go
- service/account/helper/common.go
- service/account/router/router.go
> support the suspension and resumption of export network services

- frontend/providers/devbox/api/devbox.ts
> fix:devbox api #785b9f8

- frontend/providers/applaunchpad/src/pages/_document.tsx
- frontend/providers/applaunchpad/src/pages/api/checkReady.ts
- frontend/providers/applaunchpad/src/pages/api/getAppByAppName.ts
- frontend/providers/applaunchpad/src/pages/app/edit/components/ConfigmapModal.tsx
- frontend/providers/applaunchpad/src/pages/app/edit/components/Form.tsx
- frontend/providers/applaunchpad/src/pages/app/edit/components/StoreModal.tsx
- frontend/providers/applaunchpad/src/types/app.d.ts
- frontend/providers/applaunchpad/src/utils/adapt.ts
- frontend/providers/applaunchpad/src/utils/deployYaml2Json.ts
- frontend/providers/applaunchpad/src/utils/tools.ts
- frontend/providers/template/src/pages/index.tsx
> refactor: launchpad configmap logic

- controllers/resources/controllers/quota_controller.go
> fix quota controller predicate select event devbox reason.

- frontend/desktop/src/components/region/RegionToggle.tsx
- frontend/providers/applaunchpad/.vscode/settings.json
- frontend/providers/applaunchpad/public/locales/en/common.json
- frontend/providers/applaunchpad/public/locales/zh/common.json
- frontend/providers/applaunchpad/src/api/app.ts
- frontend/providers/applaunchpad/src/components/apps/appList.tsx
- frontend/providers/applaunchpad/src/constants/account.ts
- frontend/providers/applaunchpad/src/pages/api/getApps.ts
- frontend/providers/applaunchpad/src/pages/api/pauseApp.ts
- frontend/providers/applaunchpad/src/pages/api/platform/authCname.ts
- frontend/providers/applaunchpad/src/pages/api/remark.ts
- frontend/providers/applaunchpad/src/pages/api/v1alpha/updateReplica.ts
- frontend/providers/applaunchpad/src/types/app.d.ts
- frontend/providers/applaunchpad/src/utils/adapt.ts
- frontend/providers/template/public/locales/en/common.json
- frontend/providers/template/public/locales/zh/common.json
> feat: launchpad support remark

- extensions/ide/vscode/devbox/l10n/bundle.l10n.zh-CN.json
- extensions/ide/vscode/devbox/package.json
- extensions/ide/vscode/devbox/src/commands/remoteConnector.ts
> fix(devbox/extension): cursor 1.0 extension compatibility bug

- controllers/devbox/internal/controller/devbox_controller.go
> feat：change devbox pod delete logic,set GracePeriod 0.

- frontend/packages/client-sdk/src/master.ts
> fix: sealos desktop sdk

- .github/workflows/frontends.yml
- frontend/providers/applaunchpad/src/pages/api/v1alpha/createApp.ts
- frontend/providers/applaunchpad/src/types/app.d.ts
- frontend/providers/objectstorage/src/pages/api/site/openHost.ts
> fix: objectstorage openHost

- frontend/providers/devbox/app/api/openapi/route.ts
- frontend/providers/devbox/app/reference/page.tsx
> fix(devbox): openapi show bug

- frontend/desktop/src/hooks/useSemParams.ts
- frontend/desktop/src/services/backend/globalAuth.ts
This PR fixes SEM and AD clicks are not correctly uploaded/stored sometimes.
> fix(desktop): sem&ad click data not correctly stored sometimes

- frontend/providers/applaunchpad/src/components/app/detail/index/AppMainInfo.tsx
- frontend/providers/applaunchpad/src/types/app.d.ts
- frontend/providers/applaunchpad/src/utils/adapt.ts
> fix:launchpad internal tcp address

- frontend/desktop/public/locales/en/common.json
- frontend/desktop/public/locales/zh/common.json
- frontend/desktop/src/components/account/AccountCenter/SmsModify/SmsChange.tsx
- frontend/desktop/src/components/account/AccountCenter/index.tsx
- frontend/desktop/src/services/backend/middleware/sms.ts
* Prefill old identity fields by default.
* Notify user if they click send SMS button too frequently.
> feat(desktop): better ux when chaging phone/email binding

- frontend/desktop/src/components/v2/Workspace.tsx
- frontend/desktop/src/stores/initWorkspace.ts
* Add default workspace name
* Fix region selection popup behavior
* Select the first item in selection popup by default
> fix(desktop): ux issue on workspace creation popover in /workspace

- frontend/desktop/src/components/v2/SignLayout.tsx
> fix(desktop): add missing forced language logic

- frontend/desktop/src/services/backend/cronjob/mergeUserCr.ts
- frontend/desktop/src/services/backend/regionAuth.ts
> fix: account merge issue

- frontend/desktop/src/components/account/index.tsx
- frontend/desktop/src/components/team/WorkspaceToggle.tsx
> fix(desktop): hide logo on mobile screens

- extensions/ide/vscode/devbox/package.json
- extensions/ide/vscode/devbox/package.nls.zh-CN.json
> chore: update version

- service/account/api/subscription.go
> Fix includes empty namespace

- frontend/desktop/src/services/backend/sms.ts
【sealos】Verification Code
【Sealos】Verification Code
> fix(desktop): incorrect titlecase in mail subject

- controllers/pkg/resources/resources.go
> add pods limit, default: 20

- frontend/desktop/src/components/SecondaryLinks/index.tsx
- frontend/desktop/src/components/account/index.tsx
- frontend/desktop/src/components/desktop_content/apps.tsx
- frontend/desktop/src/components/team/WorkspaceToggle.tsx
- frontend/desktop/src/components/v2/EmailCheck.tsx
- frontend/desktop/src/components/v2/PhoneCheck.tsx
1. Folder grid spacing tweaks.
2. Auth page spacing tweaks.
3. Show navbar links in a menu on narrow screens.
> feat(desktop): desktop design catchup

- frontend/desktop/src/components/SecondaryLinks/index.tsx
> fix(desktop): remove recharge entry restriction

- LICENSE
- frontend/providers/devbox/app/[lang]/(platform)/devbox/create/components/Form.tsx
- frontend/providers/devbox/app/[lang]/(platform)/devbox/create/components/Network.tsx
- frontend/providers/devbox/app/[lang]/(platform)/devbox/create/components/PriceBox.tsx
- frontend/providers/devbox/app/[lang]/(platform)/devbox/create/components/Runtime.tsx
- frontend/providers/devbox/app/[lang]/(platform)/devbox/create/page.tsx
- frontend/providers/devbox/app/[lang]/(platform)/devbox/detail/[name]/components/Monitor.tsx
- frontend/providers/devbox/app/[lang]/(platform)/devbox/detail/[name]/components/Network.tsx
- frontend/providers/devbox/app/[lang]/(platform)/devbox/detail/[name]/page.tsx
- frontend/providers/devbox/app/[lang]/(platform)/template/components/Header.tsx
- frontend/providers/devbox/app/[lang]/(platform)/template/components/PrivateTemplate.tsx
- frontend/providers/devbox/app/[lang]/(platform)/template/components/PublicTemplate.tsx
- frontend/providers/devbox/app/[lang]/(platform)/template/components/TemplateCard.tsx
- frontend/providers/devbox/components/DatePicker.tsx
- frontend/providers/devbox/components/MonitorChart.tsx
- frontend/providers/devbox/components/dialogs/ReleaseDialog.tsx
- frontend/providers/devbox/components/drawers/DeployDevboxDrawer.tsx
- frontend/providers/devbox/components/ui/form.tsx
- frontend/providers/devbox/message/en.json
- frontend/providers/devbox/message/zh.json
> fix(devbox): devbox v2 some little bug

- LICENSE
- frontend/pnpm-lock.yaml
- frontend/providers/dbprovider/package.json
- frontend/providers/dbprovider/src/pages/db/detail/components/AppBaseInfo.tsx
- frontend/providers/dbprovider/src/pages/db/detail/components/DelModal.tsx
- frontend/providers/dbprovider/src/pages/db/detail/components/Header.tsx
- frontend/providers/dbprovider/src/pages/db/detail/index.tsx
- frontend/providers/dbprovider/src/pages/db/edit/index.tsx
- frontend/providers/dbprovider/src/pages/dbs/components/dbList.tsx
- frontend/providers/dbprovider/src/pages/dbs/components/empty.tsx
- frontend/providers/dbprovider/src/pages/dbs/index.tsx
- **Database Creation**: Added `deployment_create` event tracking with detailed configuration data including database type, version, resources, and backup settings
- **Database Deletion**: Added `deployment_delete` event tracking for database removal operations
- **Module Open**: Added `module_open` event tracking when users access the database module, distinguishing between onboarding and manual access
- **Page Navigation**: Added `module_view` event tracking for all database detail page tabs:
- Overview
- Monitor
- Backup
- Data Import
- Reconfigure
- Error Log
- Operation Log
- **Database Connection**: Added `module_view` event tracking when users connect to databases
- **Database Details**: Added `deployment_details` event tracking when viewing database information
- **Database …
> feat(database): add GTM v2 tracking for database module navigation and operations

- frontend/desktop/src/components/SecondaryLinks/index.tsx
- frontend/desktop/src/components/account/AccountCenter/ConfigItem.tsx
- frontend/desktop/src/components/account/GuideModal.tsx
- frontend/desktop/src/components/account/index.tsx
- frontend/desktop/src/components/desktop_content/apps.tsx
draft, waiting for design.
Currently hides on screens narrower than 640px.
Signed-off-by: Nixieboluo <me@sagirii.me>
> feat(desktop): basic layout for mobile version of the guide modal

- frontend/packages/client-sdk/README.md
- frontend/packages/client-sdk/README_zh.md
* rename LICENSE to LICENSE.md in README files in frontend/packages/client-sdk
This pull request should fix: https://github.com/labring/sealos/issues/5805
> fix(docs): update LICENSE file references

- lifecycle/docker/patch/Dockerfile
- service/exceptionmonitor/Dockerfile
- service/vlogs/request/req.go
fix https://github.com/labring/sealos/actions/runs/16907686794/job/47901170968
> fix(security): add non-root user to Dockerfile and update TLS configuration in req.go

- frontend/providers/devbox/app/[lang]/(platform)/template/components/PublicTemplate.tsx
- frontend/providers/devbox/message/en.json
- frontend/providers/devbox/message/zh.json
> fix(devbox): template list show bug 

- frontend/providers/applaunchpad/src/pages/api/updateApp.ts
> fix(launchpad): extract AppCR URL update logic to prevent API response blocking

- frontend/providers/applaunchpad/src/components/app/detail/logs/Header.tsx
- frontend/providers/applaunchpad/src/constants/editApp.ts
- frontend/providers/applaunchpad/src/utils/deployYaml2Json.ts
> feat(launchpad): use deterministic hash for service names

- README.md
- README_zh.md
> Update the Sealos demonstration video

- .chglog/config.yml
This pull request updates the `.chglog/config.yml` configuration to improve the organization and clarity of your changelog. The most important changes are focused on sorting and labeling conventions.
Changelog configuration improvements:
* Changed the commit sorting method from `Scope` to `Type` in the `options.commits.sort_by` setting, which will group commits by their type (e.g., feature, fix) rather than their scope.
* Updated the title mapping for the `feat` type from "Features" to "New Features" in the `options.group_by.title_maps` section, making the changelog headings more descriptive.
> fix(changelog): update sorting criteria and improve title mapping in config

- frontend/desktop/src/components/desktop_content/index.tsx
> revert(desktop): disable desktop closing alert

- frontend/providers/dbprovider/public/locales/en/common.json
- frontend/providers/dbprovider/public/locales/zh/common.json
- frontend/providers/dbprovider/src/pages/db/detail/components/StopBackupModal.tsx
- frontend/providers/dbprovider/src/pages/db/edit/index.tsx
> feat(dbprovider): added prompt database update process when backup is running

- service/account/dao/init.go
> fix(account): fix remove account service smtp config verification

- CODEOWNERS
- deploy/cloud/etc/sealos/.env.tmpl
> fix(env): add loggerfile variable to environment template

- frontend/providers/applaunchpad/src/components/DatePicker/index.tsx
- frontend/providers/applaunchpad/src/pages/api/log/queryLogs.ts
- frontend/providers/applaunchpad/src/pages/api/log/queryPodList.ts
- frontend/providers/applaunchpad/src/pages/app/detail/logs.tsx
> feat(launchpad): update log api

- lifecycle/staging/src/github.com/labring/image-cri-shim/pkg/types/config.go
> fix(config): use local variable for registry domain normalization

- .github/workflows/release.yml
> fix(release): update CI runner to Ubuntu 22.04

- frontend/providers/devbox/components/IDEButton.tsx
> fix(devbox): cn show bug 

- frontend/desktop/deploy/manifests/configmap.yaml.tmpl
- frontend/desktop/deploy/scripts/init.sh
> fix(desktop): update desktop configmap.yaml.tmpl

- frontend/providers/costcenter/src/components/RechargeModal.tsx
- frontend/providers/invite/public/locales/en/common.json
- frontend/providers/invite/public/locales/zh/common.json
- frontend/providers/invite/src/pages/index.tsx
fix(costcenter): internationalize count unit and set default recharge amount to 16
> fix(costcenter): internationalize count unit and set default recharge amount to 16

- frontend/packages/client-sdk/README.md
- frontend/packages/client-sdk/README_zh.md
> chore(client-sdk): update README prefix

- frontend/providers/devbox/app/[lang]/(platform)/template/components/TemplateCard.tsx
> fix(devbox): template hover show bug

- frontend/providers/template/src/pages/deploy/components/Header.tsx
> feat(template): append uid to template share links

- frontend/providers/dbprovider/deploy/manifests/rbac.yaml
> fix(deploy): add permissions for addons in rbac.yaml

- frontend/providers/template/next.config.js
- frontend/providers/template/src/instrumentation.ts
- frontend/providers/template/src/pages/api/updateRepo.ts
- frontend/providers/template/src/services/backend/template-repo.ts
> feat(template): update git repo in instrumentation hook

- frontend/providers/cronjob/src/constants/theme.ts
- frontend/providers/template/src/pages/api/getTemplateSource.ts
Signed-off-by: Nixieboluo <me@sagirii.me>
> feat(template): include resource requirements in getTemplateSource api
