labring/sealos

roles/etcd/tasks/main.yaml, roles/keepalived/templates/keepalived.conf.j2, roles/uninstall/tasks/main.yaml
Install etcd cluster，Wait time increased from 30 to 150
Correct the spelling of 'kuburnetes'
=> Fixed ansible script

install/init.go, install/join.go, install/sealos.go, install/utils.go
=> fix(v2.0.5): fix ssh port is error

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/question.md
=> [SKIP CI]docs(devlop): template fix

install/join.go
[SKIP CI]seaols: 多master时master节点生成kubeconfig文件
#161
=> improvement(master): 其他master节点生成config文件

cmd/join.go
=> [SKIP CI] fix(devlop): 支持配置文件简化join和clean命令 - 修复join时覆盖问题

install/clean.go, install/join.go
fix #194 #191
- 暂时移除清理/tmp，目前好像没用到/tmp目录
- 安装完成清理解压文件`/root/kube`
=> feat: clean

net/calico.go, net/flannel.go, net/net.go
=> flannel yaml 渲染

cmd/clean.go, install/clean.go, install/utils.go
=> node 参数可以指定连续多个node的IP地址

cmd/clean.go, cmd/join.go, install/check.go, install/join.go
=> fix node join and clean node

install/init.go, install/join.go, install/sealos.go
=> join master

cmd/cloud.go, cmd/init.go, go.mod, go.sum, install/check.go, install/clean.go, install/cloud.go, install/config.go, install/generator_test.go, install/init.go, install/install.go, install/join.go, install/utils.go, install/utils_test.go, install/vars.go
=> 使用cuisongliu/sshcmd的lib包

cmd/join.go, install/join.go
=> feature(devlop): fix join feature

cmd/clean.go, go.sum, install/clean.go, install/utils.go, install/vars.go
修复 https://github.com/fanux/sealos/issues/197
=> 增加clean交互式确认

install/clean.go, install/utils.go
=> feature(devlop): fix clean bug  / hostname

install/clean.go, install/join.go
=> feature(devlop): fix clean bug  / join master

go.mod, go.sum, install/check.go, install/join.go, install/sealos.go, install/utils.go, vendor/github.com/cuisongliu/sshcmd/pkg/sshutil/ssh.go, vendor/modules.txt
=> merge cmdtostring

go.mod, go.sum, vendor/github.com/cuisongliu/sshcmd/pkg/sshutil/scp.go, vendor/github.com/cuisongliu/sshcmd/pkg/sshutil/watch.go, vendor/modules.txt
=> feature(devlop): support ssh cmd

install/check.go
=> fix sshcmd check clean

cmd/init.go, install/config.go, install/init.go, install/vars.go, net/calico.go, net/flannel.go, net/net.go, net/net_test.go
=> init命令增加IPIP选项

install/utils.go
=> feat(develop): fix port add :22

cmd/clean.go, go.mod, go.sum, vendor/github.com/fanux/lvscare/care/care.go, vendor/github.com/fanux/lvscare/care/create.go, vendor/github.com/fanux/lvscare/care/vars.go, vendor/github.com/fanux/lvscare/service/service.go, vendor/github.com/fanux/lvscare/utils/utils.go, vendor/modules.txt
=> merge remove lvs 

cmd/init.go, go.mod, go.sum, install/config.go, install/generator.go, install/init.go, install/vars.go, vendor/github.com/ghodss/yaml/.gitignore, vendor/github.com/ghodss/yaml/.travis.yml, vendor/github.com/ghodss/yaml/LICENSE, vendor/github.com/ghodss/yaml/README.md, vendor/github.com/ghodss/yaml/fields.go, vendor/github.com/ghodss/yaml/yaml.go, vendor/modules.txt
=> fix: 用户自定义kubeadm配置时，apiserver 证书altname添加 #261

install/download.go, install/install.go, install/send.go, install/utils.go
=> sealos和离线包同时发送到各个节点

install/config.go, install/generator.go, install/init.go, install/vars.go
=> feat(develop): 存储apiserver cert sans

go.mod, install/config.go, vendor/github.com/hashicorp/hcl/go.mod, vendor/github.com/wonderivan/logger/config.go, vendor/github.com/wonderivan/logger/console.go, vendor/github.com/wonderivan/logger/log.go, vendor/modules.txt
[SKIP CI]seaols: 添加vendor和修改load解析文件返回错误的提示
=> add: 添加vendor

cmd/clean.go, install/join.go
[SKIP CI]seaols: fix: #296 优化clean密码输入
=> fix: #296 优化clean密码输入

ipvs/lvscare.go, ipvs/lvscare_test.go
=> feat(develop): lvscare需要挂载/lib/modules #312

install/clean.go, install/join.go
=> feat(develop): lvscare版本支持

pkg/sshcmd/cmd/watch.go, pkg/sshcmd/sshutil/scp.go, pkg/sshcmd/sshutil/watch.go
=> feat(develop): kb support

cert/kube_certs.go, install/init.go, install/join.go
拷贝scheduler manager 的kubeconfig 到其它master
=> fix issue 327

cmd/clean.go, install/clean.go, install/vars.go
=> feat(develop): sealos clean  sealos clean --all -f

install/init.go
=> fix issue #327

cmd/cert.go, cmd/clean.go, cmd/cloud.go, cmd/config.go, cmd/init.go, cmd/install.go, cmd/ipvs.go, cmd/join.go, cmd/version.go, go.mod, install/clean.go, install/cloud.go, install/download.go, install/generator_test.go, install/init.go, install/join.go, install/vars.go, main.go, pkg/sshcmd/sshutil/scp.go, vendor/modules.txt
=> support v3

cert/kubeconfig.go
=> fix issue #327(change 99 year to 100 year)

go.mod, go.sum, vendor/github.com/fanux/lvscare/care/care.go, vendor/github.com/fanux/lvscare/care/create.go, vendor/github.com/fanux/lvscare/service/service.go, vendor/github.com/fanux/lvscare/utils/log.go, vendor/modules.txt
=> feat(develop): support v3

README.md
=> feat(develop): 联系方式

install/clean.go, install/init.go, install/send.go
=> feat(develop): 修复join时候kubeadm找不到的问题

cmd/init.go, install/clean.go, install/join.go, install/sealos.go, install/vars.go
=> feat(develop): 新增日志参数 vlog 默认为0

cmd/init.go, cmd/install.go, cmd/join.go, install/clean.go
=> feat(develop): 验证参数数据

cmd/clean.go, cmd/join.go, install/clean.go, install/send.go
=> feat(develop): 修复由于kubectl出现的问题导致无法delete node

Makefile, build-in-docker-and-put-oss.sh, build.sh
buildstamp -> buildtime
抱歉，我粗心了， 最后一次修改没改全。
=> fix buildstamp to buildtime

cmd/init.go, install/utils.go
1. 安装开始, 出现错误后, ip未保存. 
2. init 安装一些必要的检查,  如 masterIP未填写,  pkg-url未填写, version未填写. 直接退出.  
3. 密码和秘钥这边判断给ssh. 就没有添加到这个检查里面.
=> #378 prerun验证参数

install/utils.go, install/utils_test.go
=> #325 pkg-url 文件写错了位置, 不能及时停止.

cmd/install.go, install/install.go, install/utils.go, install/vars.go
=> add workdir add sealos install -f -c flag #399, #398

cmd/delete.go, install/delete.go, install/install.go, install/utils.go
--force 确认删除APP  -c 从命令行读取config ， 一个-w， 要删除的包的路径
install的 -f 可以不用了。 因为安装的时候， -f 文件会直接复制到 `workdir/pkgname/values.yaml`  ，
所以只需要在config里面解析即可。
安装的时候已经解压缩了。delete可以省去解压缩tar包命令。
=> implementation for #413

pkg/appmanager/appmanager.go, pkg/appmanager/installapp.go, test/testforlocal.sh
read byte to remote file by sftp.
=> read byte to remote file by sftp

.drone.yml, Dockerfile, build-in-docker-and-put-oss.sh, build.sh
=> remove vendor in build.sh

install/exec.go, pkg/sshcmd/sshutil/scp.go
1. 重新写了一下scp, 每次复制文件都复用`sftpClient`. 
2. 支持传输文件夹.
=> support exec scp local dir to remote

docs/execCmd.md
=> add exec command docs

cmd/init.go, cmd/route.go, install/check.go, install/init.go, install/route.go, install/send.go, install/vars.go
[SKIP CI]seaols: solution 1  . just test fuction
<details><summary><code> set default gateway. maybe dangerous !!! </code> Output</summary><br><pre>
23:36:19 [INFO] [scp.go:33] [ssh]md5 validate true
23:36:19 [INFO] [download.go:38] [192.168.253.129:22]copy file md5 validate success
23:36:19 [DEBG] [download.go:44] [192.168.253.129:22]please wait for after hook
23:36:19 [INFO] [ssh.go:57] [ssh][192.168.253.129:22] chmod a+x /usr/sbin/sealos
23:36:19 [INFO] [ssh.go:57] [ssh][192.168.253.129:22] sealos route --host 192.168.253.129:22
23:36:19 [INFO] [ssh.go:50] [192.168.253.129:22] 192.168.160.243 is default route ip
23:36:19 [INFO] [ssh.go:57] [ssh][192.168.253.128:22] sealos route --host 192.168.253.128:22
23:36:19 [INFO] [ssh.go:50] [192.168.253.128:22] 192.168.160.244 is default route …
=> multi Iface solution 1. 

.drone.yml, Dockerfile, build.sh, cert/cert_cmd.go, docs/multiNetworkInstall.md, docs/route.md, install/check.go, install/clean.go, install/init.go, install/join.go, install/send.go
=> rm original sealos in old package to aviod some problem.

install/init.go, install/utils_test.go
=> fix versiontointall when version like v1.16.14 >= 1191

CONTRIBUTING.md, CONTRIBUTORS
=> add sealos CONTRIBUTING.md

install/init.go, install/join.go, pkg/sshcmd/sshutil/scp.go
simple implementation , need to rm code and more test for function.
test for sealos init cmd. #490 
```
[root@k8s-dev ~]# ps aux |grep sshd |wc -l
27
[root@k8s-dev ~]# ps aux |grep sshd |wc -l
27
```
=> [WIP]: Fix ssh session

cmd/clean.go, cmd/delete.go, cmd/etcd.go, cmd/exec.go, cmd/init.go, cmd/install.go, cmd/join.go, cmd/upgrade.go, install/etcd_restore.go, install/etcd_save.go, install/exec.go, install/upgrade.go, pkg/appmanager/deleteapp.go, pkg/appmanager/installapp.go
=> fix --config when use customer config.

README.md
=> fix sealos clean in readme

install/etcd_restore.go
fix #509.
```
$ kubectl get pod -A
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-688c5dc8c7-7zmbq   1/1     Running   0          17m
kube-system   calico-node-9dvcx                          1/1     Running   0          17m
kube-system   calico-node-r7pqr                          1/1     Running   0          17m
kube-system   calico-node-zbfgj                          1/1     Running   0          17m
kube-system   coredns-6955765f44-md4vh                   1/1     Running   0          17m
kube-system   coredns-6955765f44-x6t7k                   1/1     Running   0          17m
kube-system   etcd-k8s-78 …
```
=> fix mutli etcd restore cmd

install/send.go
=> 加载docker image异常时的容错问题

install/config.go
`ApiServerDomian` shoud be `ApiServerDomain`
=> fix misspell

install/upgrade.go
change 1:
当节点已经ready的时候, 我们再`uncordon`节点, 让节点可以被调度. 
当节点没有ready. 则不需要调度了. 这个时候查看日志, 为什么没有ready.
change2:
添加 `--delete-local-data` , 当 `drain node`的时候
=> change step to upgrade when node is ready then uncordon node

.drone.yml
=> feat(develop): fix drone

.drone.yml
=> Revert "feat(develop): fix drone"

install/init.go
fix join --master  when master is not s.Masters
=> fix #534 only for 1.19.1 and 1.19.2

cmd/etcd.go, docs/etcdbackup.md, install/constants.go, install/etcd_restore.go, install/etcd_save.go
=> fix mispell of etcd

.github/workflows/go.yml, .github/workflows/pr.yml
=> fix pr to build to oss

.github/workflows/go.yml, .goreleaser.yml
=> fix workflows and goreleaser

install/constants.go, install/generator.go, install/send.go, install/utils.go, install/utils_test.go
=> fix for alpha beta rc release when version ge 1.20.0

install/constants.go, install/generator.go
某些情况还是会自动去找docker。 所以这边直接指定cri了。
=> add JoinCPTemplateTextV1beate2Container when version >=1.20

cmd/ipvs.go, go.mod, go.sum, install/join.go
=> [WIP] add sealos ipvs --clean

.github/workflows/pr.yml, README_en.md, README_zh.md, cert/kube_certs_test.go, install/generator_test.go, install/utils_test.go, ipvs/lvscare_test.go, k8s/utlis.go
=> fix readme_en add go test in pr. 

pkg/appmanager/installapp.go
=> fix #571. handle unexpected error

.github/workflows/go.yml, install/constants.go, install/generator.go, install/generator_test.go, install/join.go, install/sealos.go, install/utils_test.go, install/vars.go
=>  join node use config file

install/upgrade.go
=> fix #586,  drain node is too danger for prod use; do not drain nodes

install/check.go
=> add prefight when version >= 1.20.

README.md, README_en.md, README_zh.md
=> fix build status in readme

install/join.go
=> fix #613, delete -i for cp command

install/sealos.go
=> fix decode cmd miss TokenCaCertHash

install/sealos.go
=> feat(develop): fix  decode

cmd/clean.go, cmd/join.go
=> fix #621. join node or master should not exsit in kubernetes.

cmd/cni.go, install/init.go, install/utils_test.go, install/vars.go, net/calico.go, net/calico_yaml.go, net/net.go
- 使用tar包里面的文件作为标志位。 如果读取到了，则使用构建新版本calico。 否则使用老版本。
=> [WIP]update calico to v3.19.1

cmd/init.go, install/init.go, install/vars.go
=> feat(develop): fix  ipip param not set false

install/utils.go
=> # 决绝路径取消拼接，防止出错。

install/init.go
=> feat(develop): fix cni config too long

net/calico_yaml.go
=> fix version 3.19.1 yaml file lint error.

net/calico_yaml.go
=> fix calico

install/constants.go, install/generator.go, install/vars.go
=> fix  bootstrapToken

CHANGELOG.md
=> feat(develop): rc6 release

.github/workflows/release.yml, hack/dockerfile/Dockerfile
=> ci(master): add dockerfile

install/clean.go
1. 执行clean panic
2. 执行太快并发写输出导致数组越界 panic了
#749 fix it
=> hotfix(master): clean panic fix by lock

cmd/version.go
=> hotfix(master): fix sealer -> sealos

.github/workflows/auto-invite.yml
=> refactor(ci): add auto invite

pkg/infra/README.md, pkg/infra/aliyun/ali_ecs.go, pkg/infra/aliyun/ali_image.go, pkg/types/v1beta1/types.go
=> refactor(dev): add sys and data category

pkg/infra/aliyun/ali_ecs.go, pkg/infra/aliyun/ali_image.go, pkg/infra/aliyun/ali_provider.go, pkg/infra/aliyun/ali_vpc.go, pkg/types/v1beta1/types.go, pkg/types/validation/validation.go
=> refactor(dev): aliyun fix bug

README.md, README_en.md
=> docs: readme align

.github/workflows/auto-invite.yml, install/clean.go
=> merge master

README.md
=> refactor(dev): fix docs site

install/init.go
=> 缺陷: 添加打开hosts文件错误日志

pkg/install/init.go
Fixes #691
(cherry picked from commit 2b4578385c57936d9af492b98ebaf9438cff9e81)
=> Fixes #691

.github/workflows/release.yml, CHANGELOG.md
(cherry picked from commit e57509274c6fdfcc1d53404662ca35a4db2d4a95)
=> refactor(master): release rc.8 (#782)

CHANGELOG.md
=> refactor(master): changelog

pkg/logger/conn.go, pkg/logger/console.go
=> refactor(dev): delete bug printf

cmd/version.go
=> refactor(master): fix version

README.md
=> refactor(master): readme.md fix

install/init.go
fix bug(https://github.com/fanux/sealos/issues/806)
=> bugfix(master): fixed cni but always is calico

pkg/install/init.go
=> bugfix(master): fixed cni but always is calico (#807)

CHANGELOG.md
=> docs(master): changelog rc.10

pkg/infra/aliyun/ali_provider.go, pkg/infra/infra.go, pkg/infra/infra_test.go
=> refactor(master): fix aliyun infra

pkg/infra/README.md, pkg/infra/aliyun/ali_const.go, pkg/infra/aliyun/ali_image.go, pkg/infra/aliyun/ali_provider.go
=> aliyun fix docs

.github/workflows/auto-merge.yml
=> refactor(ci): auto merge

.github/workflows/auto-merge.yml, pkg/config/config.go, pkg/utils/exec/cmd.go
=> refactor(master): add refactor config

cmd/sealctl/cmd/cri.go
=> refactor(master): add sealctl cri  containers

cmd/sealctl/boot/boot.go, cmd/sealctl/cmd/root.go, cmd/sealos/boot/boot.go, cmd/sealos/cmd/root.go, pkg/utils/logger/log.go
=> refactor(master): fix logger #645

install/send.go
=> refactor(master): containerd cni

.github/workflows/release.yml, README.md, README_en.md, docs/multiNetworkInstall.md, test/note.sh, test/test-sealos-beijing.sh
=> refactor(master): move oss addr

.github/workflows/release.yml, README.md, README_en.md, docs/plan/multi_network_install.md, hack/release/note.sh, test/old/test-sealos-beijing.sh
* refactor(master): move oss addr
=> refactor(master): move oss addr (#878)

cmd/root.go, docs/upgrade.md, test/testUpgrade.md
=> docs: replace ture with true

pkg/runtime/default_kubeadm_config.go, pkg/runtime/init.go, pkg/runtime/kubeadm.go, pkg/runtime/kubeadm_config.go, pkg/runtime/kubeconfig.go, pkg/runtime/master.go, pkg/runtime/node.go, pkg/runtime/registry.go, pkg/runtime/reset.go, pkg/runtime/runtime.go, pkg/runtime/runtime_getter.go, pkg/runtime/runtime_setter.go, pkg/runtime/token.go, pkg/runtime/utils.go, pkg/utils/contants/contants.go
=> refactor(master): runtime fix code

pkg/image/binary/cluster.go, pkg/image/types/interface.go, pkg/image/types/types.go
=> refactor(master): list cluster interface

pkg/image/binary/image.go, pkg/image/binary/registry.go, pkg/image/types/interface.go, pkg/image/types/types.go, pkg/registry/save_test.go
#896   binary runtime from buildah
=> refactor(master): impl from binary interface

pkg/apply/processor/create.go, pkg/filesystem/rootfs/rootfs_default.go, pkg/guest/guest.go, pkg/image/binary/registry.go, pkg/image/buildah.go, pkg/image/image.go, pkg/image/types/interface.go, pkg/image/types/types.go, pkg/ipvs/lvscare.go, pkg/remote/remote.go, pkg/runtime/init.go, pkg/runtime/kubeadm.go, pkg/runtime/master.go, pkg/runtime/node.go, pkg/runtime/registry.go, pkg/runtime/runtime.go, pkg/runtime/runtime_getter.go, pkg/runtime/token.go, pkg/token/token.go, pkg/utils/contants/data.go
=> refactor(master): join node and master logic

hack/release/note.sh
=> refactor(master): support  docs for sealos 4.0

cmd/sealos/cmd/run.go, docs/4.0/images.md, pkg/apply/processor/delete.go, pkg/filesystem/rootfs/rootfs_default.go, pkg/image/binary/cluster.go, pkg/image/types/interface.go, pkg/runtime/master.go
=> refactor(master): add multi image and go func

hack/release/note.sh
=> refactor(master): add note

Makefile, cmd/sealos/cmd/images.go, cmd/sealos/cmd/load.go, cmd/sealos/cmd/login.go, cmd/sealos/cmd/logout.go, cmd/sealos/cmd/prune.go, cmd/sealos/cmd/pull.go, cmd/sealos/cmd/push.go, cmd/sealos/cmd/rmi.go, cmd/sealos/cmd/save.go, cmd/sealos/cmd/tag.go, pkg/checker/cluster_checker.go, pkg/checker/cluster_checker_test.go, pkg/cri/cri_unix.go, pkg/image/binary/image.go, pkg/image/types/interface.go, pkg/utils/exec/cmd.go, pkg/utils/file/file_v2.go, pkg/utils/file/file_v3.go
=> feature(main): add cmd feature for main branch

.github/workflows/go.yml, .github/workflows/release.yml
=> feature(main): fix release config

pkg/apply/processor/delete.go
=> feature(main):  support skip error process

pkg/image/binary/cluster.go, pkg/image/binary/image.go, pkg/image/binary/registry.go, pkg/image/image.go, pkg/runtime/runtime_getter.go, pkg/utils/exec/cmd.go, pkg/utils/ssh/sshcmd.go
=> feature(main):  cmd \n and process in pull images

pkg/image/binary/image.go
=> feature(main):  fix images build

pkg/apply/applydrivers/apply_drivers_default.go, pkg/apply/processor/delete.go, pkg/apply/processor/install.go, pkg/apply/run.go, pkg/filesystem/rootfs/rootfs.go, pkg/filesystem/rootfs/rootfs_default.go, pkg/image/binary/cluster.go, pkg/image/types/interface.go, pkg/utils/exec/cmd.go
=> feature(main): add patch package in run func

cmd/sealctl/cmd/registry.go, pkg/utils/maps/maps.go, pkg/utils/maps/maps_test.go
=> feature(main): add auths data

pkg/apply/applydrivers/apply_drivers_default.go, pkg/apply/processor/create.go, pkg/apply/processor/install.go, pkg/guest/guest.go
=> feature(main): sealos run repeat exec

pkg/guest/guest.go
=> feature(main): guest run in host cmd for bash

cmd/sealos/cmd/add.go, cmd/sealos/cmd/delete.go, pkg/apply/applydrivers/apply_drivers_default.go, pkg/apply/args.go, pkg/apply/processor/create.go, pkg/apply/processor/delete.go, pkg/apply/processor/install.go, pkg/apply/processor/scale.go, pkg/apply/run.go, pkg/apply/scale.go, pkg/apply/utils.go, pkg/image/binary/cluster.go, pkg/registry/util.go, pkg/utils/iputils/iputils_v2.go
=> feature(main): no change images

pkg/runtime/default_kubeadm_config.go, pkg/runtime/init.go, pkg/runtime/kubeadm.go, pkg/runtime/kubeadm_config.go, pkg/runtime/master.go
=> feature(main): fix #960 for controller and schedule bind 0.0.0.0

cmd/sealos/cmd/add.go, pkg/apply/processor/scale.go, pkg/apply/scale.go, pkg/checker/host_checker.go, pkg/runtime/kubeadm.go
=> feature(main): fix add feature and delete node feature

docs/4.0/build.md, docs/4.0/config.md, docs/4.0/install-sealos.md, docs/4.0/run.md, pkg/config/test_clusterfile.yaml
=> feature(main): 4.0 docs fix

pkg/image/binary/image.go
=> feature(main): fix tag images

Makefile
=> feature(main): fix goinstall

.goreleaser.yml
=> feature(main): fix go release

cmd/sealos/cmd/add.go, cmd/sealos/cmd/delete.go, cmd/sealos/cmd/ssh.go, pkg/ssh/ssh.go
=> feature(main): add ssh exec/copy feature

pkg/types/v1beta1/doc.go, pkg/types/v1beta1/register.go
=> feature(main): rename sealyun to sealos.io

cmd/sealos/cmd/apply.go, cmd/sealos/cmd/build.go, cmd/sealos/cmd/reset.go, cmd/sealos/cmd/run.go, pkg/apply/processor/create.go, pkg/apply/processor/install.go, pkg/apply/processor/scale.go, pkg/apply/run.go, pkg/config/config.go, pkg/config/config_test.go, pkg/filesystem/rootfs/rootfs_default.go, pkg/utils/yaml/yaml.go
=> feature(main): fix install config

cmd/sealos/cmd/pull.go, pkg/image/buildah/registry/refer.go, pkg/image/buildah/registry/registry.go, pkg/image/service.go
feature: add pull commands using buildah #986
=> feature: add pull commands using buildah #986

pkg/image/buildah.go, pkg/image/buildah/registry/registry.go, pkg/image/service.go
=> feature(main): fix build config

pkg/image/binary/registry.go
=> feature(main): http push registry

cmd/sealos/cmd/delete.go, cmd/sealos/cmd/reset.go, pkg/apply/processor/delete.go, pkg/apply/processor/install.go, pkg/apply/processor/interface.go, pkg/runtime/runtime.go, pkg/runtime/utils.go, pkg/types/v1beta1/cluster_args.go
fix:
1. https://github.com/labring/sealos/issues/999  confirm if input no always exec process
2. https://github.com/labring/sealos/issues/991 not override mount path
=> feature(main): fix confirm bug

pkg/apply/processor/create.go, pkg/apply/processor/install.go
check create error use application image
=> feature(main): fix create check bug

pkg/image/buildah/registry/push.go, pkg/image/buildah/registry/refer.go, pkg/image/buildah/registry/registry.go
feature: add push commands using buildah #986
=> feature: add push commands using buildah #986

pkg/guest/guest.go
modify logger.Debug to logger.Info
=> modify pkg/guest/guest.go

pkg/image/buildah/registry/login.go, pkg/image/buildah/registry/logout.go, pkg/image/buildah/registry/refer.go, pkg/image/buildah/registry/registry.go
feature: add login/logout commands using buildah #986
=> feature: add login/logout commands using buildah #986

cmd/sealos/cmd/pull.go, pkg/image/binary/registry.go, pkg/image/buildah/registry/login.go, pkg/image/buildah/registry/logout.go, pkg/image/buildah/registry/pull.go, pkg/image/buildah/registry/push.go, pkg/image/buildah/registry/refer.go
fix: when operator the registry,defautl is tls_verify=false #986
fix: delete repeated call func buildah.InitReexec()
=> fix: when operator the registry,defautl is tls_verify=false #986

Makefile, pkg/apply/applydrivers/apply_drivers_default.go, pkg/apply/scale.go, pkg/runtime/reset.go, pkg/runtime/utils.go, pkg/utils/iputils/iputils_v2.go
=> feature(main): fix delete add node and skip error

Makefile, pkg/filesystem/rootfs/rootfs_default.go
add nodes ,  send app images is unnecessary
=> feature(main): fix add error send app images

.goreleaser.yml, Makefile
[fix: arm64 cross netgo panic](https://github.com/labring/sealos/commit/554b53e9c9b07bac9ef6c670c3d307dd269efe52)
=> fix: arm64 cross netgo panic

cmd/sealos/cmd/root.go
[SKIP CI]seaols: set default logurs log-level to warn
=> Fix: set default logurs log-level to warn

pkg/image/buildah/image/build.go
[SKIP CI]seaols: fix build images tag not work
=> fix build images tag not work

pkg/image/buildah/image/build.go
[SKIP CI]seaols: use GH_TOKEN insetead of GIT_AUTH_TOKEN
=> fix release using wrong token

.github/workflows/release.yml
=> feature(main): fix actions token

docs/4.0/README_en.md
Add v4.0 README in English, which should close #1055.
Reference: https://github.com/labring/sealos/blob/main/docs/4.0/README.md.
=> Add v4.0 README in English

MAINTAINERS.md, USERS.md
Signed-off-by: maybaby <ybyang7@iflytek.com>
[SKIP CI]seaols: add users and MAINTAINERS.md
=> feature: add users and MAINTAINERS.md

pkg/apply/processor/create.go
=> feature(main): fix check image type after image pull

pkg/image/buildah.go
=> Add default registry mirror

cmd/sealos/cmd/root.go, pkg/utils/contants/data.go
=> feat: make cluster root dir customizable with root cmd flags (#995)

Makefile, README.md, applications/calico/Kubefile, cmd/sealos/cmd/build.go, cmd/sealos/cmd/pull.go, cmd/sealos/cmd/push.go, cmd/sealos/cmd/rmi.go, cmd/sealos/cmd/run.go, cmd/sealos/cmd/save.go, cmd/sealos/cmd/tag.go, docs/4.0/README.md, docs/4.0/build.md, docs/4.0/design/rootfs.md, docs/4.0/images.md, docs/4.0/run.md, hack/release/note.sh, pkg/image/buildah.go
=> feature(main): rename image short name

pkg/config/config.go, pkg/config/config_test.go
=> feat: support config override

pkg/image/buildah.go, pkg/registry/save.go
=> fix: panic when building offline and syntax error in registry config

pkg/cri/cri.go, pkg/cri/cri_unix.go
=> feat: CRI defaults to containerd

README.md
Modify characters and add a space after the comma.
=> Modify characters in README.md

pkg/buildimage/images.go, pkg/utils/tmpl/tmpl.go
=> feat: include .tmpl files when searching for images

pkg/image/buildah.go
fix sealos pull images default domain localhost to docker.io #1097
=> fix sealos pull images default domain localhost to docker.io #1097

README.md, applications/calico/Kubefile, cmd/sealos/cmd/build.go, cmd/sealos/cmd/pull.go, cmd/sealos/cmd/push.go, cmd/sealos/cmd/rmi.go, cmd/sealos/cmd/run.go, cmd/sealos/cmd/save.go, cmd/sealos/cmd/tag.go, docs/4.0/README.md, docs/4.0/build.md, docs/4.0/images.md, docs/4.0/run.md, hack/release/note.sh
fix doc,all images add prefix labring #1100
=> fix doc,add prefix labring

cmd/sealos/cmd/run.go
Change official website, update description to English
=> add en-help

CONTRIBUTORS
=> add contributors

README.md
=> docs(main): add oscs

pkg/types/v1beta1/cluster_args.go
[SKIP CI]seaols: see #1132 
Closes #1132
=> remove unuseful code

cmd/sealos/cmd/delete.go
[SKIP CI]seaols: solve #1068 
Closes #1068
=> docs: add more description for delete command

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/question.md
[SKIP CI]seaols: resolve #1091
=> docs: update issue templates to English

pkg/apply/applydrivers/apply_drivers_default.go, pkg/apply/processor/create.go, pkg/apply/processor/scale.go, pkg/types/v1beta1/cluster.go, pkg/types/v1beta1/helper.go
=> feature(main): sealos run not save clusterfile when init failed

pkg/apply/processor/interface.go, pkg/guest/guest.go, pkg/types/v1beta1/cluster.go
[SKIP CI]sealos: resolve #1099
=> feat: support entrypoint in Dockerfile

DEVELOPGUIDE.md
[SKIP CI]sealos:  fix typo "clonne" in develop guide
=> typo: fix typo clonne in develop guide

Makefile
=> feature(main): seactl - sealctl

cmd/sealos/cmd/gen.go, pkg/apply/run.go, pkg/types/v1beta1/cluster.go
[SKIP CI]sealos: resolve #1179
=> feature: sealos gen

.github/workflows/go.yml, .github/workflows/release.yml, .goreleaser.yml, Makefile
- `make release.build` -> `make release-build`
- `make release.release` -> `make release`
=> ci: adjust makefile release targets

pkg/guest/guest.go
=> Add support for command override

cmd/sealctl/cmd/ipvs.go, pkg/remote/remote.go, pkg/runtime/reset.go, pkg/runtime/runtime_getter.go
=> feature(main): delete lvscare ipvs and route

pkg/apply/args.go, pkg/apply/reset.go, pkg/apply/run.go, pkg/apply/scale.go, pkg/apply/utils.go
=> refactor: improve scale and reset params

pkg/checker/host_checker.go
=> fix a word spell problem

cmd/sealos/cmd/inspect.go
=> feat: sealos inspect

pkg/infra/README.md
[SKIP CI]sealos:  refactor infra yaml struct
=> feat: refactor infra yaml struct

.github/workflows/unit-test.yml, pkg/registry/save_test.go, pkg/utils/logger/conn_test.go
=> refactor(main): add test workflows

.github/sources.list, .github/workflows/build.yml, .github/workflows/unit-test.yml, .goreleaser.yml, scripts/make-rules/release.mk
Signed-off-by: maybaby <ybyang7@iflytek.com>
=> fix:  reduce ci time

README.md
=> refactor(main): add codecov img

.github/workflows/ci.yml
=> refactor(main): add fossa workflows

.github/workflows/ci.yml, README.md
=> refactor(main): delete fossa workflows

pkg/filesystem/rootfs/rootfs_default.go
=> refactor(main): run app image fix port

.github/workflows/ci.yml, .golangci.yml, .goreleaser.yml, CONTRIBUTING.md, scripts/make-rules/golang.mk, staging/src/github.com/labring/image-cri-shim/pkg/glog/glog.go, staging/src/github.com/labring/image-cri-shim/pkg/glog/glog_test.go, staging/src/github.com/labring/lvscare/pkg/glog/glog.go, staging/src/github.com/labring/lvscare/pkg/glog/glog_test.go
=> ci: build binaries for lvscare and image-cri-shim

pkg/ssh/connect.go, pkg/ssh/scp.go, pkg/ssh/ssh.go, pkg/ssh/sshcmd.go
=> refactor(main): Execute the command If it is a local IP, use the os package.

pkg/constants/contants.go
=> fix disposition

.gitignore, Makefile, docker/lvscare/Dockerfile, scripts/make-rules/common.mk, scripts/make-rules/golang.mk, scripts/make-rules/image.mk, scripts/make-rules/release.mk, scripts/make-rules/tools.mk
=> ci: add workflows to build and push images for lvscare

.github/workflows/ci.yml, pkg/image/binary/image.go, pkg/image/buildah/image/load.go, pkg/image/buildah/image/save.go, pkg/image/types/types.go
=> refactor(main): set default Transport for buildah

cmd/sealos/cmd/load.go, cmd/sealos/cmd/save.go, pkg/image/types/types.go
=> refactor(main): add transport param for save and load

deploy/desktop/casdoor.yaml
1. Start a Casdoor server
2. Use MySQL as the database of Casdoor
3. Use OpenEBS as the persistence of MySQL
```
sealos run labring/openebs:v1.9.0
kubectl apply -f casdoor.yaml
```
=> feat(desktop): casdoor k8s yaml

.github/workflows/release.yml, .goreleaser.yml
=> refactor(main): fix release to any one

pkg/runtime/reset.go
=> refactor(main): reset add getSSHInterface for shim

.github/workflows/release.yml, .goreleaser.yml, scripts/release/note.sh
=> refactor(main): add note for image and apt deb

pkg/cloud/src/components/header.rs, pkg/cloud/src/components/image_list.rs
Signed-off-by: xiaorx <xiaorx@asiainfo.com>
[SKIP CI]sealos: fix dashboard header narbar class `botton` typo
=> bugfix: fix dashboard css typo

pkg/runtime/kubeadm.go, pkg/runtime/kubeadm_cmd.go, pkg/runtime/runtime_getter.go
=> feat: support custom apiserver port

pkg/runtime/registry.go
=> fix(main): port set error

pkg/runtime/kubeconfig.go
=> fix: generate .kube dir in home dir

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Signed-off-by: fanux <fhtjob@hotmail.com>
=> update contribute guide

pkg/utils/iputils/iputils.go, staging/src/github.com/labring/lvscare/pkg/utils/iputils.go
upgrade IsIpv4 function use to system api
=> upgrade IsIpv4 function use to system api

.github/sync_code.yml, .github/sync_docs.yml
=> ci: fix docs sync error

DEVELOPGUIDE.md
=> docs: update notes about cross-platform building

pkg/filesystem/rootfs/rootfs_default.go, pkg/ssh/scp.go, pkg/ssh/sshcmd.go, pkg/utils/iputils/iputils_v2.go
=> fix(main): add local ip logger

docker/patch/Dockerfile, docker/patch/images/shim/lvscareImage, pkg/apply/processor/install.go, pkg/filesystem/rootfs/rootfs_default.go, pkg/types/v1beta1/cluster.go
=> fix(main): rename AddonsImage to PatchImage

cmd/lvscare/cmd/care.go, cmd/sealctl/cmd/ipvs.go, staging/src/github.com/labring/lvscare/care/care.go, staging/src/github.com/labring/lvscare/care/create.go, staging/src/github.com/labring/lvscare/care/utils.go, staging/src/github.com/labring/lvscare/care/vars.go, staging/src/github.com/labring/lvscare/go.mod, staging/src/github.com/labring/lvscare/go.sum
refactor `--clean` flag of lvscare implementation, unified flags registeration.
=> refactor: clean flag of lvscare

staging/src/github.com/labring/lvscare/README.md
=> docs: remove badges for lvscare

.github/workflows/sync_code.yml
=> ci: fix sync_code trigger paths

pkg/utils/iputils/iputils_v2.go
=> fix(main): delete logger for isLocal

pkg/utils/logger/logger.go
=> logger support fulltext color

pkg/ssh/sshcmd.go, pkg/utils/iputils/iputils_v2.go
=> feature(main): local ip not ping

.github/PULL_REQUEST_TEMPLATE.md
=> update pull request template to supress showing

pkg/buildimage/chart.go, pkg/utils/iputils/iputils_v2.go
1. fix variables definition in the for loop
2. fix typo error
=> perf: singleton just fine

.github/workflows/ci.yml
=> Revert "feature(main): add lvscare docker build"

.github/workflows/sync_code.yml, .github/workflows/sync_docs.yml
=> ci: skip pr when syncing

pkg/image/binary/cluster.go
remove duplicate code in ClusterService
=> remove duplicate codes

scripts/make-rules/golang.mk
Signed-off-by: xuehaipeng <hpxue13@hotmail.com>
=> fix: go.build.verify

staging/src/github.com/labring/image-cri-shim/pkg/shim/client/clinet.go
Signed-off-by: xuehaipeng <hpxue13@hotmail.com>
fix image-cri-shim deprecated grpc dial option
=> fix: deprecated grpc dial option

pkg/checker/host_checker.go, pkg/ssh/ssh.go, pkg/utils/iputils/iputils_v2.go
1. avoid variable reassign in the loop;
2. fix `WaitSSHReady`, error may been overrided by nil
=> refactor ssh client

.github/workflows/ci.yml, docker/patch/Dockerfile, docker/patch/images/shim/lvscareImage
=> feature(main): add lvscare docker build

.github/workflows/ci.yml, scripts/save-cluster-images.sh
=> ci: improve ci workflow

README.md, docs/4.0/docs/getting-started/installation.md, docs/4.0/i18n/zh-Hans/Intro.md, docs/4.0/i18n/zh-Hans/getting-started/installation.md
Remove oss download link to github release link.
=> update readme deadlink

controllers/infra/controllers/infra_controller.go, controllers/infra/drivers/driver.go, controllers/infra/drivers/reconcile.go, go.mod, go.sum
=> add controller reconcile, add events recorder.

cmd/sealos/cmd/run.go, pkg/utils/iputils/iputils_v2.go
=> feature(main): single module kubernetes cluster

README.md, docs/4.0/docs/getting-started/installation.md, docs/4.0/i18n/zh-Hans/Intro.md, docs/4.0/i18n/zh-Hans/getting-started/installation.md
=> fixed readme run command

README.md, controllers/infra/controllers/infra_controller.go, controllers/infra/drivers/aws/aws.go, controllers/infra/drivers/aws/create_instance.go
=> add sleaos cloud overview

README.md, docs/4.0/docs/getting-started/installation.md, docs/4.0/i18n/zh-Hans/Intro.md, docs/4.0/i18n/zh-Hans/getting-started/installation.md
> Conflicts:
README.md
docs/4.0/docs/getting-started/installation.md
docs/4.0/i18n/zh-Hans/Intro.md
docs/4.0/i18n/zh-Hans/getting-started/installation.md
=> docs(main): fix targz

README.md
=> add trackgit

pkg/auth/sso/casdoor.go, pkg/utils/httpserver/cors.go, pkg/utils/httpserver/go_restful.go, service/auth/.gitignore, service/auth/Dockerfile, service/auth/Makefile, service/auth/README.md
=> add docker and readme

docs/4.0/i18n/zh-Hans/cli/build.md
fix docs that have english， the issue: https://github.com/labring/sealos/issues/1364
=> fix docs that have english

.github/workflows/sync_docs.yml, CONTRIBUTING.md
=> ci: fix path error in sync_docs.yml

.github/workflows/sync_code.yml, .github/workflows/sync_docs.yml
=> ci: set COMMIT_EACH_FILE to false in sync

CONTRIBUTING.md
=> docs: add more instructions on docs contributing

pkg/apply/processor/scale.go
=> docs(main): fix miss mount in add nodes

pkg/buildimage/chart.go, pkg/buildimage/chart_test.go
Signed-off-by: yyf1986 <191557539@qq.com>
fix_chart_1431
default like:
```
- name: ***
image: ***
```
support chart image like:
```
- image: ***
name: ***
```
=> fix chart parse image  and add unit test

docs/4.0/docs/design/private-registry.md
=> docs：Add registry docs

docs/4.0/docs/ai-applications/blazeface.md, docs/4.0/i18n/zh-Hans/ai-applications/blazeface.md
=> add blazeface docs

docs/4.0/docs/getting-started/customize-cluster.md
Signed-off-by: will <willzhmic@outlook.com>
Add Customize install Docs
=> Add Customize Docs

docs/4.0/docs/getting-started/prerequisites.md
Signed-off-by: will <willzhmic@outlook.com>
Add Prerequisites Docs
=> Add Prerequisites Docs

controllers/infra/api/v1/infra_types.go, controllers/infra/common/common.go, controllers/infra/controllers/infra_controller.go, controllers/infra/drivers/aws/aws.go, controllers/infra/drivers/aws/create_instance.go, controllers/infra/drivers/aws/get_instance.go, controllers/infra/drivers/aws/stop_instance.go, controllers/infra/drivers/delete_instance_test.go, controllers/infra/drivers/driver.go, controllers/infra/drivers/reconcile.go, controllers/infra/drivers/reconcile_test.go
=> add reconcile instance, test aws reconcile instance success

staging/src/github.com/labring/image-cri-shim/pkg/server/const.go, staging/src/github.com/labring/image-cri-shim/pkg/server/service.go, staging/src/github.com/labring/image-cri-shim/pkg/utils/http.go
Master issue: #1463. Fix #1460.
Also includes some code refactor and comment addition.
=> feat: support removing digest from image tags

docs/4.0/docs/examples/build-example-cloudimage.md, go.mod, go.sum, pkg/buildimage/chart.go, pkg/buildimage/chart_test.go, pkg/buildimage/images.go, pkg/buildimage/manifests/manifests.go, pkg/buildimage/manifests/utils.go, pkg/image/binary/image.go, pkg/image/buildah/image/build.go, pkg/utils/strings/strings.go
1. unified list images functions
2. support render chart tar file
3. support render chart with custom values file
=> Fix sealos build

docs/4.0/docs/design/private-registry.md
Fix incorrect description of private registry document.
=> fix private registry docs

go.mod, go.sum, pkg/guest/guest.go, pkg/guest/guest_test.go
=> feature(main): guest env render

cloud/deploy/manifests/ingress-kubernetes-dashboard.yaml, cloud/deploy/manifests/ingress-nginx-with-cert.yaml, desktop/frontend/deploy/manifests/frontend.yaml, desktop/frontend/package-lock.json, desktop/frontend/package.json, desktop/frontend/src/lib/api.ts, desktop/frontend/src/pages/dashboard/index.tsx, desktop/frontend/src/pages/login/callback.tsx, desktop/frontend/src/store/session.ts, pkg/utils/httpserver/go_restful.go, service/auth/Dockerfile, service/auth/api/api.go, service/auth/api/struct.go, service/auth/deploy/manifests/auth.yaml
=> Fix ingress-nginx route rewrite.

controllers/infra/drivers/aws/create_instance.go
Set aws infra name & index tag. (#1462)
Signed-off-by: Ficus <ficusf@qq.com>
=> Set aws infra name & index tag. (#1462)

cmd/sealos/cmd/add.go, cmd/sealos/cmd/create.go, cmd/sealos/cmd/delete.go, cmd/sealos/cmd/gen.go, cmd/sealos/cmd/inspect.go, cmd/sealos/cmd/prune.go, cmd/sealos/cmd/reset.go, cmd/sealos/cmd/rmi.go, cmd/sealos/cmd/run.go
=> fix(cmd): unifiy the format of print columns

docker/lvscare/Dockerfile
add iptables tool in lvscare image.
=> fix: iptables tool missing in lvscare image

staging/src/github.com/labring/lvscare/README.md, staging/src/github.com/labring/lvscare/care/iptables.go
prevent doing snat for packets those didn't mark.
=> fix: only snat packets marked

.golangci.yml, cmd/sealctl/cmd/password.go, cmd/sealctl/cmd/static_pod.go, pkg/buildimage/chart.go, pkg/buildimage/manifests/manifests.go, pkg/clusterfile/util.go, pkg/config/config.go, pkg/config/config_test.go, pkg/filesystem/rootfs/rootfs_default.go, pkg/image/buildah/cluster/buildah/from.go, pkg/image/buildah/image/build.go, pkg/image/buildah/image/manifest.go, pkg/image/buildah/image/save.go, pkg/image/buildah/registry/push.go, pkg/image/buildah/registry/refer.go, pkg/registry/distributionpkg/client/blob_writer.go, pkg/registry/distributionpkg/client/errors.go, pkg/registry/distributionpkg/client/repository.go, pkg/registry/filesystem.go, pkg/registry/save.go, pkg/ssh/connect.go, pkg/ssh/scp.go, pkg/utils/archive/compress_test.go, pkg/utils/file/file_v2.go, staging/src/github.com/labring/image-cri-shim/pkg/cri/cri.go, test/testhelper/utils.go
=> Fix lint error by replace `os`&`io`

controllers/terminal/README.md, controllers/terminal/api/v1/terminal_types.go, controllers/terminal/config/crd/bases/terminal.sealos.io_terminals.yaml, controllers/terminal/config/samples/terminal_v1_terminal.yaml, controllers/terminal/controllers/terminal_controller.go
- add default APIServer address for Terminal CRD
- add terminal keepalived
Resolve #1335
=> feat: add terminal keepalived

.github/workflows/ci.yml, .golangci.yml, controllers/app/api/v1/groupversion_info.go, controllers/infra/api/v1/groupversion_info.go, controllers/infra/drivers/aws/create_instance.go, controllers/infra/drivers/aws/get_instance.go, controllers/infra/drivers/aws/stop_instance.go, controllers/terminal/api/v1/groupversion_info.go, pkg/image/buildah/cluster/buildah/containers.go, pkg/image/buildah/cluster/buildah/from.go, pkg/image/buildah/cluster/buildah/inspect.go, pkg/image/buildah/cluster/buildah/mount.go, pkg/image/buildah/cluster/buildah/parse/parse.go, pkg/image/buildah/cluster/buildah/parse/util.go, pkg/image/buildah/cluster/buildah/rm.go, pkg/image/buildah/cluster/buildah/umount.go, pkg/image/buildah/cluster/inspect.go, pkg/image/buildah/cluster/list.go, pkg/registry/distributionpkg/client/transport/http_reader.go, pkg/runtime/apis/kubeadm/v1beta2/conversion.go, pkg/runtime/apis/kubeadm/v1beta2/doc.go, pkg/runtime/apis/kubeadm/v1beta3/conversion.go, pkg/runtime/apis/kubeadm/v1beta3/doc.go, pkg/runtime/kubeadm.go, pkg/runtime/kubeadm_config.go, pkg/runtime/runtime.go, pkg/utils/archive/compress_test.go
=> fix typo by `go fmt`

.github/no-response.yml
=> add issue no response auto close it

.github/stale.yml
=> no reply issue auto closer

controllers/infra/drivers/aws/create_instance.go, controllers/infra/drivers/aws/get_instance.go
Feature: reconcile aws infra count. (#1490)
=> Reconcile aws infra count. (#1490)

controllers/infra/drivers/aws/create_instance.go, controllers/infra/drivers/aws/stop_instance.go, controllers/infra/drivers/reconcile.go, controllers/infra/go.sum
Signed-off-by: Work <553834398@qq.com>
=> fix create and delete instance bug

pkg/registry/save.go
=> fixed build out of memory

docs/4.0/docs/getting-started/customize-cluster.md, docs/4.0/docs/getting-started/prerequisites.md, docs/4.0/docs/getting-started/update-cluster.md
=> update the docs sidebar

docs/4.0/docs/getting-started/prerequisites.md
Signed-off-by: x893675 <x893675@icloud.com>
=> docs: fix docs typo

pkg/registry/save.go
=> fix(main): add max goroutine num

staging/src/github.com/labring/image-cri-shim/pkg/cri/cri.go, staging/src/github.com/labring/image-cri-shim/pkg/cri/cri_unix.go
=> fix(main): add docker-shim support

docs/4.0/docs/ai-applications/athenaserving.md, docs/4.0/i18n/zh-Hans/ai-applications/athenaserving.md
Signed-off-by: ybyang7 <ybyang7@iflytek.com>
=> docs: fix some refs

docs/4.0/docs/ai-applications/athenaserving.md, docs/4.0/i18n/zh-Hans/ai-applications/athenaserving.md
=> Some doc optimizations.

docs/4.0/docs/ai-applications/athenaserving.md
Signed-off-by: ybyang7 <ybyang7@iflytek.com>
=> docs: remove some extra pics ref

pkg/registry/save.go
fix `warn save domain xxx image xxxxxxx error: failed to create blob store writer: operation unsupported` error while `sealos build`
=> fix: sealos build(revert saveBlobs function)

service/payment/README.md, service/payment/api/api.go, service/payment/api/client.go, service/payment/api/wechat-payment.go, service/payment/cmd/recharge.go, service/payment/go.mod, service/payment/go.sum
=> add recharge cli

pkg/registry/distributionpkg/proxy/proxyblobstore.go, pkg/registry/save.go
use bufio to avoid oom killed.
=> fix: oom occured when sealos build

pkg/client-go/kubernetes/client.go, pkg/client-go/kubernetes/suite_test.go
=> feature(main): add client for k8s

pkg/auth/utils/config.go
=> Fix ca data not returned under incluster mode

controllers/user/controllers/helper/user.go
=> feature(main): add user load ca for kubeconfig

controllers/terminal/controllers/terminal_controller.go, controllers/terminal/main.go
=> fix(main): fix terminal code,using config host

docs/4.0/docs/cli/apply.md
=> docs: experimental usage for sealos apply

controllers/terminal/config/rbac/role.yaml, controllers/terminal/controllers/ingress.go, controllers/terminal/controllers/terminal_controller.go
=> refactor: optimize the creation of terminal ingress

.goreleaser.yml
=> feature(main): delete go  generate for gorelease

controllers/terminal/api/v1/terminal_types.go, controllers/terminal/config/crd/bases/terminal.sealos.io_terminals.yaml, controllers/terminal/controllers/terminal_controller.go
=> feat: add terminal status

docs/4.0/docs/cli/customize-config.md, docs/4.0/docs/getting-started/customize-cluster.md, docs/4.0/docs/getting-started/prerequisites.md
https://github.com/labring/sealos/issues/1552
=> docs: add example for Config

controllers/terminal/config/samples/terminal_v1_terminal.yaml, desktop/frontend/package-lock.json, desktop/frontend/package.json, desktop/frontend/src/lib/client_api.ts, desktop/frontend/src/lib/kubernetes.ts, desktop/frontend/src/pages/api/cloud/get_all.ts, desktop/frontend/src/pages/api/cloud/get_page.ts, desktop/frontend/src/pages/api/kubernetes/get_terminal.ts, desktop/frontend/src/pages/api/kubernetes/pod.ts, desktop/frontend/src/pages/api/response.ts, desktop/frontend/src/pages/login/callback.tsx
Updated support both outside and incluster apiserver host.
=> update terminal frontend svc get

cmd/sealos/cmd/add.go, cmd/sealos/cmd/delete.go
Correct flags in `add`/`delete` command to avoid misleading user.
=> style: correct flag usage

controllers/terminal/config/deploy.yaml, desktop/frontend/package-lock.json, desktop/frontend/package.json, desktop/frontend/src/lib/kubernetes.ts, desktop/frontend/src/pages/api/kubernetes/get_terminal.ts, desktop/frontend/src/pages/api/kubernetes/pod.ts
=> Update client-js to support crd get status return

go.mod
After this commit merged, one can use `sudo docker build -t controller/user:test1 -f controllers/user/Dockerfile .` to support build `controller/user image from scripts.
=> Fix work replace

controllers/infra/api/v1/infra_types.go, controllers/infra/common/common.go, controllers/infra/drivers/aws/aws.go, controllers/infra/drivers/aws/create_instance.go, controllers/infra/drivers/aws/create_volume.go, controllers/infra/drivers/aws/delete_volume.go, controllers/infra/drivers/aws/get_instance.go, controllers/infra/drivers/aws/modify_instance.go, controllers/infra/drivers/aws/modify_volume.go, controllers/infra/drivers/aws/stop_instance.go, controllers/infra/drivers/driver.go, controllers/infra/drivers/reconcile.go, controllers/infra/drivers/reconcile_test.go
Signed-off-by: <5538343986@qq.com>
Create/Delete Volume complete
=> feat: Attach aws Volume (#1512)

docs/4.0/i18n/zh-Hans/Intro.md
=> fixed typo

controllers/user/api/v1/account_types.go, controllers/user/controllers/account_controller.go, pkg/pay/wechat_payment.go
=> update account controller to listen the payment crd

.github/workflows/semgrep.yml
=> add semgrep sast scan

staging/src/github.com/labring/lvscare/care/runner.go
=> feature(main): add tips in running routeMode

controllers/user/api/v1/payment_types.go
=> add payment spec verify

README.md, docs/4.0/docs/ai-applications/osm.md
=> add terminal record to show how to use sealos install kubernetes cluster

docs/4.0/docs/getting-started/installation.md, docs/4.0/i18n/zh-Hans/getting-started/installation.md
=> update install doc

CONTRIBUTING.md, docs/4.0/i18n/zh-Hans/Intro.md, docs/4.0/i18n/zh-Hans/cli/build.md, docs/4.0/i18n/zh-Hans/getting-started/build-example-cloudimage.md, docs/4.0/i18n/zh-Hans/getting-started/installation.md, docs/4.0/i18n/zh-Hans/getting-started/kuberentes-life-cycle.md, docs/4.0/i18n/zh-Hans/getting-started/offline-install.md, docs/4.0/i18n/zh-Hans/getting-started/prerequisites.md, docs/4.0/i18n/zh-Hans/getting-started/update-cluster.md
=> add first contribution about github workflow

cmd/sealos/cmd/add.go, cmd/sealos/cmd/apply.go, cmd/sealos/cmd/create.go, cmd/sealos/cmd/delete.go, cmd/sealos/cmd/exec.go, cmd/sealos/cmd/gen.go, cmd/sealos/cmd/reset.go, cmd/sealos/cmd/run.go, cmd/sealos/cmd/scp.go, pkg/apply/args.go, pkg/apply/args_test.go, pkg/apply/reset_test.go, pkg/apply/run.go, pkg/apply/scale.go, pkg/apply/scale_test.go
This PR is mostly code style changes, bringing together scattered command line flags definitions.
=> style: unifying definitions of command line flags

controllers/terminal/README.md, controllers/terminal/api/v1/terminal_types.go, controllers/terminal/config/crd/bases/terminal.sealos.io_terminals.yaml, controllers/terminal/config/deploy.yaml, controllers/terminal/config/manager/kustomization.yaml, controllers/terminal/controllers/ingress.go, controllers/terminal/controllers/terminal_controller.go, controllers/terminal/go.mod, controllers/terminal/go.sum
=> add uuid address for terminal

controllers/infra/drivers/aws/get_instance.go, controllers/infra/drivers/aws/modify_volume.go, controllers/infra/drivers/aws/price.go, controllers/infra/drivers/driver.go, controllers/infra/drivers/price_test.go, controllers/infra/drivers/reconcile.go
=> add some notes

go.mod, go.sum, service/auth/main.go
Signed-off-by: zhangmengcong <zhangmengcong@bytedance.com>
=> change 'auth/main.go log'

.github/workflows/ci.yml
=> ci: auto format code with `make format`

pkg/image/buildah.go, pkg/runtime/kubeadm.go, staging/src/github.com/labring/image-cri-shim/pkg/cri/cri.go, staging/src/github.com/labring/image-cri-shim/pkg/cri/cri_unix.go
=> feature(main): add docker support

controllers/infra/config/crd/bases/infra.sealos.io_infras.yaml, controllers/user/api/v1/payment_types.go, controllers/user/config/crd/bases/user.sealos.io_payments.yaml, controllers/user/config/manager/kustomization.yaml, docs/4.0/docs/ai-applications/vrp.md, docs/4.0/docs/design/registry-image.md, docs/4.0/docs/design/user.md
=> translate en docs

.github/workflows/ci.yml
=> fix auto-format by pull from right repo url

pkg/auth/conf/Dockerfile
=> feat(auth): local cdn

pkg/image/buildah.go
=> feature(main): override registry config for buildah

docs/4.0/docs/design/rootfs-docker.md, docs/4.0/i18n/zh-Hans/design/rootfs-docker.md
=> feature(main): doc: add docker images for sealos

pkg/apply/applydrivers/apply_drivers_default.go, pkg/apply/args.go, pkg/apply/args_test.go, pkg/apply/run.go, pkg/clusterfile/clusterfile.go, pkg/clusterfile/clusterfile_test.go, pkg/clusterfile/decode.go, pkg/clusterfile/pre_process.go, pkg/clusterfile/testdata/config.yaml, pkg/config/config.go, pkg/utils/yaml/yaml.go
Support patching files in the image when executing the `sealos run` command
=> feat: support merging configs on run command

pkg/apply/applydrivers/apply_drivers_default.go, pkg/apply/args.go, pkg/runtime/kubeadm.go, pkg/runtime/kubeadm_config.go
=> feature(main):  hotfix kubelet 10250 dead

pkg/apply/run.go
=> fix: override spec value from flags

controllers/user/controllers/user_controller.go, controllers/user/controllers/usergroup_controller.go, controllers/user/controllers/usergroupbinding_controller.go, controllers/user/controllers/usergroupnamespacebinding_controller.go, controllers/user/main.go
=> feature(main): add usergroupbindings controller for namespace

.goreleaser.yml
Should close #1688.
Related issue:
- #1481 
- #1518
=> fix: release binary segfault on centos

staging/src/github.com/labring/image-cri-shim/pkg/server/cri_server.go
=> feature(main): fix shim image for online

.github/workflows/release.yml, scripts/make-rules/golang.mk, scripts/make-rules/license.mk
=> update gorelease typo locaion

.github/workflows/release.yml
=> feature(main): fix upx for release

.github/workflows/ci.yml, .github/workflows/controllers.yml, .github/workflows/release.yml, .github/workflows/sync_code.yml, .github/workflows/sync_docs.yml
=> optimize go step action

.github/workflows/ci.yml, .goreleaser.yml
=> remove upx compress on sealos binary

.goreleaser.yml, pkg/image/binary/cluster.go, pkg/image/binary/image.go, pkg/image/binary/registry.go, pkg/image/buildah.go, pkg/image/service.go, pkg/image/types/types.go
=> feature(main):  add binary for buildah

.github/workflows/ci.yml
=> feature(main):  add upx for sealos

docker/lvscare/Dockerfile, docker/sealos/Dockerfile, docker/sealos/Dockerfile.main
=> feature(main): optimize Dockerfile(#1711)

desktop/frontend/src/layout/index.tsx, desktop/frontend/src/pages/_app.tsx, desktop/frontend/src/pages/home/index.tsx, desktop/frontend/src/pages/index.tsx
1. add index page
2. remove useless home.tsx
=> fix: add index page

cmd/sealos/cmd/merge.go, pkg/cert/cert_cmd.go, pkg/image/buildah/image/build.go, pkg/image/merge.go, pkg/image/merge_test.go, pkg/image/types/types.go, pkg/types/v1beta1/constants.go, pkg/types/v1beta1/helper.go
=> feature(main): sealos merge fearure

pkg/apply/run.go
=> fix: issue 1724

cmd/sealos/cmd/gen.go, pkg/apply/run.go, pkg/runtime/kubeadm_config.go
=> feat: generate config of components

controllers/terminal/Makefile
=> fix ci terminal controller build error

.github/workflows/controllers.yml, controllers/user/Dockerfile, controllers/user/deploy/Dockerfile, controllers/user/deploy/manifests/rbac.yaml
=> feature(main):  add sync user role

controllers/user/.gitignore, controllers/user/api/v1/user_types.go, controllers/user/config/crd/bases/user.sealos.io_users.yaml, controllers/user/config/manager/manager.yaml, controllers/user/controllers/usergroupnamespacebinding_controller.go, controllers/user/deploy/manifests/deploy.yaml, controllers/user/deploy/manifests/rbac.yaml, controllers/user/main.go, pkg/image/types/types.go
=> feature(main):  fix user group role

desktop/frontend/README.md, desktop/frontend/next.config.js, desktop/frontend/package.json, desktop/frontend/pnpm-lock.yaml, desktop/frontend/src/components/desktop_content/iframe_app.tsx, desktop/frontend/src/services/backend/kubernetes.ts
=> tmp fix terminal waiting

cloud/deploy/README.md, cloud/deploy/manifests/ingress-nginx-cloud/2-godaddy-dns.yaml
=> Temp Add `terminal`'s namespace

desktop/frontend/package.json, desktop/frontend/pnpm-lock.yaml, desktop/frontend/src/applications/app_store/index.tsx, desktop/frontend/src/applications/setting/index.tsx, desktop/frontend/src/components/app_icon/index.tsx, desktop/frontend/src/components/app_window/index.module.scss, desktop/frontend/src/components/app_window/index.tsx, desktop/frontend/src/components/app_window/tab.module.scss, desktop/frontend/src/components/background/index.tsx, desktop/frontend/src/components/desktop_content/iframe_app.tsx, desktop/frontend/src/components/desktop_content/index.tsx, desktop/frontend/src/components/taskbar/index.tsx, desktop/frontend/src/components/taskbar/taskbar.module.scss, desktop/frontend/src/layout/index.tsx, desktop/frontend/src/mock/allApps.ts, desktop/frontend/src/mock/installedApps.ts, desktop/frontend/src/services/request.ts, desktop/frontend/src/stores/app.ts, desktop/frontend/tsconfig.json
=> update: window manage

README.md
=> update readme: add cri-docker and new desktop image

docker/sealos/Dockerfile, docker/sealos/Dockerfile.main
=> feature(main): update base image is ubuntu

desktop/frontend/src/applications/app_store/index.tsx
Signed-off-by: BambooSword <herodreamdeng@gmail.com>
=> bugfix: display the correct icon in app store

.github/workflows/ci.yml
=> Update ci dep.

controllers/user/api/v1/user_types.go, controllers/user/config/crd/bases/user.sealos.io_accounts.yaml, controllers/user/config/crd/bases/user.sealos.io_payments.yaml, controllers/user/config/crd/bases/user.sealos.io_usergroupbindings.yaml, controllers/user/config/crd/bases/user.sealos.io_usergroups.yaml, controllers/user/config/crd/bases/user.sealos.io_users.yaml, controllers/user/config/rbac/role.yaml, controllers/user/controllers/user_controller.go, controllers/user/deploy/manifests/deploy.yaml
=> feature(main): fix user-controller-rbac for csr

pkg/apply/processor/create.go, pkg/apply/processor/install.go, pkg/image/binary/image.go, pkg/image/binary/registry.go, pkg/image/buildah/cluster/buildah/from.go, pkg/image/buildah/registry/pull.go, pkg/image/cmd/create.go, pkg/image/cmd/pull.go, pkg/image/merge.go, pkg/image/service.go, pkg/image/types/interface.go, pkg/image/types/types.go
=> feature(main): add Platform for sealos pull/create

README.md
=> add helm when install calico v3.24.1

cmd/sealos/cmd/gen.go, docs/4.0/docs/cli/run.md, docs/4.0/docs/examples/build-private-image.md, docs/4.0/docs/getting-started/customize-cluster.md, docs/4.0/docs/getting-started/kuberentes-life-cycle.md, docs/4.0/i18n/zh-Hans/Intro.md, docs/4.0/i18n/zh-Hans/api/sealos_gen.md, docs/4.0/i18n/zh-Hans/cli/apply.md, docs/4.0/i18n/zh-Hans/cli/run.md, docs/4.0/i18n/zh-Hans/examples/build-private-image.md, docs/4.0/i18n/zh-Hans/getting-started/customize-cluster.md, scripts/release/note.sh, service/auth/README.md
=> fixed docs, calico new version needs helm

pkg/auth/auth.go, pkg/auth/utils/config.go, service/auth/api/api.go
=> feat: generate kubeconfig by user controller

.github/workflows/semgrep.yml
=> Update seg to standalone version.

.github/workflows/semgrep.yml
=> Allow semgpeg fails.

controllers/user/controllers/helper/pod_security.go, controllers/user/controllers/usergroupnamespacebinding_controller.go
=> feature(main): add user namespace Pod Security Admission

controllers/user/main.go
=> feature(main): add disable_webhook_env

controllers/user/controllers/account_controller.go
add user access account permissions
user can get their own balance  in account crd
=> feat: add user access account permissions

controllers/user/controllers/payment_controller.go
add create status when payment create. @zzjin
=> fix:add create status when payment create

pkg/apply/run.go, pkg/apply/run_test.go
This PR should fix #1807 and make env/command override work.
=> fix: ineffective env and cmd override

docs/4.0/docs/getting-started/kuberentes-life-cycle.md
fix #1775: update doc calico version to v3.24.1
=> fix #1775: update doc calico version to v3.24.1

desktop/client-sdk/.gitignore, desktop/client-sdk/README.md, desktop/client-sdk/package.json, desktop/client-sdk/pnpm-lock.yaml, desktop/client-sdk/rollup.config.js, desktop/client-sdk/src/constant.ts, desktop/client-sdk/src/index.ts, desktop/client-sdk/src/log.ts, desktop/client-sdk/src/master.ts, desktop/client-sdk/tsconfig.json, desktop/frontend/next.config.js, desktop/frontend/package.json, desktop/frontend/pnpm-lock.yaml, desktop/frontend/src/applications/app_store/index.tsx, desktop/frontend/src/components/desktop_content/iframe_app.tsx, desktop/frontend/src/components/desktop_content/index.tsx, desktop/frontend/src/components/start_menu/index.tsx, desktop/frontend/src/layout/index.tsx, desktop/frontend/src/mock/installedApps.ts, desktop/frontend/src/pages/demo.tsx, desktop/frontend/tsconfig.json
1. add wechat pay
2. add sealos desktop sdk
2.1 how to use:  https://github.com/LeezQ/sealos/blob/feat-client-sdk-and-wechat-pay/desktop/frontend/src/pages/demo.tsx#L8
=> Feat client sdk and wechat pay

controllers/user/controllers/account_controller.go
example rolebinding.yaml
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
name: read-accounts-0ffc5a5d-12c3-4e3c-a71f-58abbb50047c
namespace: sealos-system
subjects:
- kind: User
name: 0ffc5a5d-12c3-4e3c-a71f-58abbb50047c # "name" 是区分大小写的
apiGroup: rbac.authorization.k8s.io
roleRef:
kind: Role        # 此字段必须是 Role 或 ClusterRole
name: role-account-0ffc5a5d-12c3-4e3c-a71f-58abbb50047c  # 此字段必须与你要绑定的 Role 或 ClusterRole 的名称匹配
apiGroup: rbac.authorization.k8s.io
```
example role.yaml
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
namespace: sealos-system
name: role-account-0ffc5a5d-12c3-4e3c-a71f-58abbb50047c
rules:
- apiGroups: ["user.sealos.io"] # "" 标明 core API 组
resources: ["accounts"]
verbs: ["get", "watch", …
```
=> feat:update role of user access ownerreference account

desktop/frontend/package.json, desktop/frontend/pnpm-lock.yaml, desktop/frontend/src/components/start_menu/index.tsx, desktop/frontend/src/mock/hub/terminal.ts, desktop/frontend/src/pages/api/kubernetes/account/get_amount.ts, desktop/frontend/src/pages/api/kubernetes/account/payment/[name].ts, desktop/frontend/src/pages/api/kubernetes/account/payment/index.ts, desktop/frontend/src/utils/format.ts
=> Update accounts.user.sealos.io sdk usage.

desktop/frontend/package.json, desktop/frontend/pnpm-lock.yaml, desktop/frontend/src/components/start_menu/index.tsx, desktop/frontend/src/mock/hub/terminal.ts, desktop/frontend/src/pages/api/kubernetes/account/get_amount.ts, desktop/frontend/src/pages/api/kubernetes/account/payment/[name].ts, desktop/frontend/src/pages/api/kubernetes/account/payment/index.ts, desktop/frontend/src/utils/format.ts
=> Fix terminal rbac permission.

controllers/user/README.md, controllers/user/controllers/account_controller.go, controllers/user/controllers/payment_controller.go, controllers/user/go.mod, controllers/user/go.sum
=> fix:change log level

pkg/registry/save.go
=> fix: return error if any error occured

desktop/frontend/src/components/start_menu/index.tsx, desktop/frontend/src/components/taskbar/index.tsx, desktop/frontend/src/hooks/useLocalSession.ts, desktop/frontend/src/interfaces/session.ts
=> fix: Hydration failed

CONTRIBUTING.md
I have found some syntax errors in the document CONTRIBUTING.md and have fixed them here.
=> docs: fix some typo in CONTRIBUTING.md.

controllers/user/config/default/manager_auth_proxy_patch.yaml, controllers/user/config/rbac/role.yaml, controllers/user/controllers/account_controller.go, controllers/user/controllers/helper/cert.go, controllers/user/controllers/helper/csr.go, controllers/user/controllers/helper/kubeconfig.go, controllers/user/controllers/helper/sa.go, controllers/user/controllers/helper/suite_test.go, controllers/user/controllers/payment_controller.go, controllers/user/controllers/user_controller.go, controllers/user/controllers/user_expiration_controller.go, controllers/user/controllers/usergroupnamespacebinding_controller.go, controllers/user/controllers/usergroupuserbinding_controller.go, controllers/user/deploy/manifests/deploy.yaml, controllers/user/main.go
=> feature(main): add sa kubeconfig

controllers/user/config/default/manager_auth_proxy_patch.yaml, controllers/user/controllers/account_controller.go, controllers/user/controllers/helper/sa.go, controllers/user/deploy/manifests/deploy.yaml
=> feature(main): fix image pull for user-controller

.github/workflows/controllers.yml
=> feature(main): add auto build cluster-image

docs/4.0/docs/api/sealos_create.md, docs/4.0/docs/cli/create.md, docs/4.0/i18n/zh-Hans/api/sealos_create.md, docs/4.0/i18n/zh-Hans/cli/create.md, pkg/image/cmd/create.go
=> fix:sealos creat xxxx image not known

cmd/sealos/cmd/add.go, pkg/apply/applydrivers/apply_drivers_default.go, pkg/apply/processor/scale.go, pkg/apply/scale.go, pkg/apply/utils.go
1. remove dup code blocks
2. avoid resync lvscare static pod for all nodes when not master adds or removed
=> optimize the scale process

controllers/user/controllers/helper/cert.go, controllers/user/controllers/helper/csr.go, controllers/user/controllers/helper/kubeconfig.go, controllers/user/controllers/helper/sa.go, controllers/user/controllers/user_controller.go, controllers/user/controllers/usergroupnamespacebinding_controller.go, controllers/user/controllers/usergroupuserbinding_controller.go
=> feature(main): fix miss rbac

pkg/apply/run.go
Signed-off-by: NTH19 <3310288189@qq.com>
This pr just reduces the nesting levels of if in func SetClusterRunArgs
=> improve:make SetClusterRunArgs conform to 'return fast'

desktop/frontend/src/mock/allApps.ts, desktop/frontend/src/mock/appDetailInfo.ts
=> add mock dapps

cmd/sealctl/cmd/registry.go, fork/github.com/heroku/docker-registry-client/registry/repositories.go, go.mod, go.sum, pkg/registry/cmd/list.go, pkg/registry/cmd/prune.go, pkg/registry/cmd/rmi.go, pkg/registry/cmd/save.go, pkg/registry/interface.go, pkg/registry/list.go, pkg/registry/list_test.go, pkg/registry/rmi.go, pkg/registry/save.go
=> feature(main): add registry sdk

docs/4.0/docs/getting-started/kuberentes-life-cycle.md, docs/4.0/i18n/zh-Hans/getting-started/kuberentes-life-cycle.md
=> doc: update k8s image name

CONTRIBUTORS, README.md
Changes:
1. Changed some 'kubernetes' into 'Kubernetes'.
2. Fixed grammar mistake in sentence 'Customize you own distributed applications'. (you -> your)
3. Removed Chinese punctuation in README.md(English document).
Signed-off-by: TomatoQt <a491122844@gmail.com>
=> docs: A few typos

controllers/terminal/deploy/Dockerfile, controllers/user/deploy/Dockerfile
Should resolve user-controller actions failure.
=> fix: use unknown user instead of running useradd

README.md, docs/4.0/i18n/zh-Hans/Intro.md
Fix the README.md and Intro.md
=> fix readme and intro

README.md
=> temp comments out L

controllers/user/config/rbac/role.yaml, controllers/user/controllers/user_controller.go
=> feature(main): add user-controller rbac for sa

pkg/apply/processor/create.go, pkg/apply/processor/install.go, pkg/image/binary/registry.go, pkg/image/buildah/registry/pull.go, pkg/image/cmd/create.go, pkg/image/cmd/merge.go, pkg/image/cmd/pull.go, pkg/image/cmd/save.go, pkg/image/merge.go, pkg/image/types/interface.go, pkg/image/types/types.go
Signed-off-by: yyf1986 <191557539@qq.com>
the cmd pull  policy is "ifnewer",othe all is "missing".
=> [fix]add pull policy

controllers/user/deploy/manifests/deploy.yaml
=> feature(main): add user-controller rbac for sa (#1926)

docs/4.0/i18n/zh-Hans/getting-started/kuberentes-life-cycle.md
=> Update doc typo.

scripts/create_vm_sealos.sh
docs:https://www.sealos.io/blog/2022/10/22/vm-sealos-creat
create a sealos cluster based on multipass quickly.
=> shell:creat a sealos cluster based on multipass

cmd/sealctl/cmd/token.go, pkg/constants/data.go, pkg/runtime/kubeadm.go, pkg/runtime/token.go
=> feature(main): sync ttl for token and kubeadm-certs

pkg/auth/conf/casdoor.yaml
=> fix: casdoor non root security

pkg/image/buildah/image/build.go, pkg/image/buildah/image/common.go
=> feature(main): add GetContextDir for build

README.md
Signed-off-by: ining7 <3213698201@qq.com>
=> fix: error link

README.md
Signed-off-by: ining7 <3213698201@qq.com>
=> del: update readme

README.md
=> feature(main): add sealos action for docs

.github/workflows/release.yml
=> Try fix goreleaser for arm package.

pkg/remote/remote.go, pkg/runtime/kubeadm.go, staging/src/github.com/labring/image-cri-shim/pkg/cri/cri.go
=> feature(main): fix cri socket to multiple CRI

CONTRIBUTING.md
Signed-off-by: Harry <xiaohanwu12@gmail.com>
Modified steps and expressions in `CONTRIBUTING.md` to be more organized.
=> docs: update workspace preparation steps

.github/workflows/release.yml, .goreleaser.yml
=> feature(main): fix docker build image

pkg/runtime/registry.go
=> feature(main): fix default registry ip

cmd/sealos/cmd/run.go, pkg/apply/args.go, pkg/apply/processor/create.go, pkg/apply/processor/delete.go, pkg/apply/processor/install.go, pkg/apply/run.go, pkg/types/v1beta1/cluster_args.go, pkg/types/v1beta1/constants.go
=> feature(main): separate registry from master0

.github/workflows/build_service_auth.yml, service/auth/.gitignore, service/auth/Dockerfile
tested in: https://github.com/maslow/sealos/actions/runs/3344571221/jobs/5539073248
=> Add docker image builder workflow for service auth 

README.md, docs/4.0/docs/cli/build.md, docs/4.0/docs/examples/build-calico-image.md, docs/4.0/docs/getting-started/installation.md, docs/4.0/i18n/zh-Hans/Intro.md, docs/4.0/i18n/zh-Hans/cli/build.md, docs/4.0/i18n/zh-Hans/examples/build-calico-image.md, docs/4.0/i18n/zh-Hans/getting-started/installation.md
=> feature(main): fix buildah download and sealos build

DEVELOPGUIDE.md, docs/4.0/i18n/zh-Hans/getting-started/kuberentes-life-cycle.md
Signed-off-by: xiongxinwei <3293172751nss@gmail.com>
=> docs<git && go-path>: a small number of errors

cmd/sealos/cmd/run.go, pkg/apply/processor/install.go
=> feature(main): add detach for sealos run, never prompt

controllers/metering/config/default/manager_auth_proxy_patch.yaml, controllers/metering/controllers/metering_controller.go
=> feat: use env instead of hard code

pkg/filesystem/rootfs/rootfs_default.go
=> feature(main): replace render charts dir  to scripts dir

cmd/sealos/cmd/run.go, pkg/apply/processor/install.go
=> fix: remove prompt arg

.github/workflows/ci.yml, .github/workflows/controllers.yml, .github/workflows/services.yml, .github/workflows/webhooks.yml
=> feature(main): add container label for repo

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
It is mandatory to fill in some places. Is it not good? I removed it.
=> Remove mandatory requirements

pkg/image/binary/image.go, pkg/image/buildah/image/build.go, pkg/image/cmd/build.go, pkg/image/merge.go, pkg/image/types/types.go
=> feature(main): add save image to build cmd

.github/workflows/ci.yml, .github/workflows/controllers.yml, .github/workflows/release.yml, .github/workflows/services.yml, .github/workflows/webhooks.yml
=> GitHub Actions: Deprecating save-state and set-output commands

pkg/apply/applydrivers/apply_drivers_default.go, pkg/clusterfile/pre_process.go, pkg/template/template.go
=> feature(main): add TryParse for loadClusterfile

pkg/apply/applydrivers/apply_drivers_default.go, pkg/clusterfile/pre_process.go, pkg/template/template.go
Hotfix add TryParse for loadClusterfile (#2017)
=> feature(main): add TryParse for loadClusterfile (#2017)

controllers/user/README.md, controllers/user/config/manager/manager.yaml, controllers/user/deploy/manifests/deploy.yaml.tmpl
=> feature(main): delete pyament env from deploy

controllers/terminal/config/manager/manager.yaml, controllers/terminal/controllers/terminal_controller.go, controllers/terminal/controllers/utils.go, controllers/terminal/deploy/manifests/deploy.yaml
=> fix terminal hardcoded problem

docs/4.0/docs/getting-started/installation.md, docs/4.0/i18n/zh-Hans/getting-started/installation.md
=> Fix yum package manager command.

cloud/deploy/manifests/interfaces/affine/ingress-affine.yaml, desktop/frontend/public/images/affine.svg, desktop/frontend/src/mock/hub/affine.ts, desktop/frontend/src/mock/imagehub.ts, desktop/frontend/src/mock/installedApps.ts, desktop/frontend/src/pages/api/kubernetes/apply/[...params].ts
=> Add affine app demo.

DEVELOPGUIDE.md
=> add build sealos on macos ARM using multipass

DEVELOPGUIDE.md, docs/4.0/docs/getting-started/installation.md, docs/4.0/i18n/zh-Hans/getting-started/installation.md
=> feature(main): add BINS=sealos for docs

pkg/filesystem/rootfs/rootfs_default.go, pkg/guest/guest.go, pkg/guest/guest_test.go
=> feature(main): fix guest func for exec shell

docs/4.0/docs/build-cloud-image/build-cloudImage-with-binary-file.md, docs/4.0/docs/build-cloud-image/build-cloudImage-with-env.md, docs/4.0/docs/build-cloud-image/build-cloudImage-with-helm-charts.md, docs/4.0/docs/build-cloud-image/build-cloudImage-with-yaml.md, docs/4.0/docs/build-cloud-image/build-directory-structure.md
=> add build cloud image docs

fork/github.com/heroku/docker-registry-client/registry/json.go, fork/github.com/heroku/docker-registry-client/registry/manifest.go
https://github.com/heroku/docker-registry-client/issues/82
=> feature(main): fix registry bugs

cmd/sealos/cmd/exec.go, cmd/sealos/cmd/scp.go
=> feature(main): fix gen doc

controllers/user/deploy/Dockerfile
=> feature(main): fix user controller deploy

proposal/README.md
=> Begin proposal process

cloud/deploy/manifests/ingress-cloud/2-godaddy-dns.yaml, cloud/deploy/manifests/interfaces/affine/ingress-affine.yaml, cloud/deploy/manifests/interfaces/kubernetes-dashboard/ingress-kubernetes-dashboard.yaml, cloud/deploy/manifests/interfaces/kuboard/ingress-kuboard.yaml, cloud/deploy/manifests/interfaces/postgres/ha-cluster-pv.yaml, cloud/deploy/manifests/interfaces/postgres/ingress-pgadmin.yaml, cloud/deploy/manifests/interfaces/postgres/pgadmin.yaml, cloud/deploy/manifests/interfaces/redis/ingress-redisinsight.yaml, cloud/deploy/manifests/interfaces/redis/redisinsight.yaml, pkg/auth/conf/casdoor.yaml
=> Support ingress static cache

controllers/cluster/Dockerfile, controllers/cluster/Makefile, controllers/cluster/api/v1/cluster_types.go, controllers/cluster/applier/applier.go, controllers/cluster/config/crd/bases/cluster.sealos.io_clusters.yaml, controllers/cluster/config/samples/cluster.yaml, controllers/cluster/controllers/cluster_controller.go, controllers/cluster/deploy/manifests/deploy.yaml, controllers/infra/Dockerfile, controllers/infra/Makefile, controllers/infra/api/v1/infra_types.go, controllers/infra/config/crd/bases/infra.sealos.io_infras.yaml, controllers/infra/config/samples/infra_v1_infra.yaml, controllers/infra/controllers/infra_controller.go, controllers/infra/deploy/manifests/deploy.yaml, controllers/infra/drivers/aws/get_instance.go, controllers/infra/drivers/create_instance_test.go, controllers/infra/drivers/create_volume_test.go, controllers/infra/drivers/delete_instance_test.go, controllers/infra/drivers/delete_volume_test.go, controllers/infra/drivers/get_instance_test.go, controllers/infra/drivers/modify_volume_test.go, controllers/infra/drivers/price_test.go, controllers/infra/drivers/reconcile.go, controllers/infra/drivers/reconcile_test.go, controllers/infra/drivers/stop_instance_test.go
=> Start Infra and add status 

service/auth/Makefile, service/auth/deploy/manifests/deploy.yaml.tmpl, service/auth/kustomize/manager/kustomization.yaml
=> feature(main): fix auth deploy for cluster-image

desktop/frontend/deploy/manifests/frontend.yaml
=> Update frontend nonRoot user.

pkg/filesystem/rootfs/rootfs_default.go
BUG introduced in this PR #2048 .
`registry` dir in app image must copy to `$ROOTFS/registry`, so that with `image-cri-shim` component, CRI can pull image from local registry.
=> fix: copy registry to the correct path

controllers/cluster/Makefile, controllers/infra/Makefile
Signed-off-by: wxm-github <1264646904@qq.com>
=> reduction Makefile and add build-multi-arch

.gitignore, desktop/frontend/README.md
Add step-by-step debug intro using vscode.
=> Update frontend Readme.

controllers/cluster/go.mod, controllers/cluster/go.sum, controllers/user/go.mod, controllers/user/go.sum
=> del:useless go mod

docs/4.0/docs/examples/how-to-use-env.md
=> docs example : how to use env

desktop/frontend/src/applications/infra/add_page.tsx, desktop/frontend/src/applications/infra/detail_page.module.scss, desktop/frontend/src/applications/infra/detail_page.tsx, desktop/frontend/src/applications/infra/front_page.module.scss, desktop/frontend/src/applications/infra/front_page.tsx, desktop/frontend/src/applications/infra/infra_share.ts, desktop/frontend/src/mock/infra.ts, desktop/frontend/src/pages/api/infra/awsApply.ts, desktop/frontend/src/pages/api/infra/awsApplyCluster.ts, desktop/frontend/src/pages/api/infra/awsDeleteCluster.ts
=> fix scp password and support delete scp

controllers/infra/drivers/aws/create_instance.go, controllers/infra/drivers/create_instance_test.go, controllers/infra/drivers/create_volume_test.go, controllers/infra/drivers/delete_instance_test.go, controllers/infra/drivers/delete_volume_test.go, controllers/infra/drivers/get_instance_test.go, controllers/infra/drivers/modify_volume_test.go, controllers/infra/drivers/price_test.go, controllers/infra/drivers/reconcile.go, controllers/infra/drivers/reconcile_test.go, controllers/infra/drivers/stop_instance_test.go
=> bug: fixed using ssh private key to login instance

controllers/cluster/controllers/cluster_controller.go, controllers/infra/drivers/aws/create_instance.go, pkg/ssh/ssh_test.go, test/exec-cmd-in-mountpoint-dir/imageA/pod.yaml, test/exec-cmd-in-mountpoint-dir/imageB/pod.yaml
=> use user data to permit root login using ssh private key

README.md
Signed-off-by: Xiaohan <962479661@qq.com>
=> fix: delete sealer

README.md
it's necessary when low version, such as 1.24.1
=> Update README.md, add command for untaint tag when low version

controllers/cluster/controllers/cluster_controller.go
=> wait for infra create when get cluster

controllers/cluster/controllers/cluster_controller.go, controllers/infra/controllers/infra_controller.go
=> instead echo to tee

.github/workflows/controllers.yml, .github/workflows/services.yml, .github/workflows/webhooks.yml
=> Update auto build paths config.

controllers/cluster/Makefile, controllers/cluster/README.md, controllers/cluster/controllers/cluster_controller.go, controllers/infra/Makefile
Update controller readme, add buildx usage for testing and publishing.
=> Update Controller Readme.

desktop/frontend/src/pages/api/infra/awsApply.ts, desktop/frontend/src/pages/api/infra/awsApplyCluster.ts, desktop/frontend/src/pages/api/infra/awsDelete.ts, desktop/frontend/src/pages/api/infra/awsDeleteCluster.ts, desktop/frontend/src/pages/api/infra/awsGet.ts, desktop/frontend/src/pages/api/infra/awsGetAll.ts, desktop/frontend/src/pages/api/infra/awsUpdate.ts, desktop/frontend/src/pages/api/infra/getAllCluster.ts, desktop/frontend/src/pages/api/infra/getCluster.ts, desktop/frontend/src/services/backend/kubernetes.ts
=> encapsulate the infra api

desktop/frontend/src/applications/infra/detail_page.tsx, desktop/frontend/src/applications/infra/front_page.tsx
=> Fix the scp timestamp

pkg/ssh/utils.go
=> fix: copy empty merged dir anyway

controllers/infra/Makefile
fix: kustomize makefile with a little enhance
add test -s to check if kustomize exists.
Signed-off-by: ybyang <ybyang7@iflytek.com>
=> fix: kustomize makefile with a little enhance

pkg/runtime/kubeadm_config.go
Set kubelet.ResolverConfig to nil. fix #2074  #1620
=> fix: coredns crash issue.

controllers/user/controllers/user_controller.go, controllers/user/controllers/user_expiration_controller.go, controllers/user/controllers/usergroup_controller.go, controllers/user/controllers/usergroupbinding_controller.go
=> refactor(user): rename doReconcile to reconcile

.github/workflows/ci.yml, .github/workflows/controllers.yml, .github/workflows/release.yml, .github/workflows/services.yml, .github/workflows/webhooks.yml
=> Dev ci to fix controllers dep.

controllers/infra/api/v1/infra_types.go, controllers/infra/config/crd/bases/infra.sealos.io_infras.yaml
Signed-off-by: ybyang <ybyang7@iflytek.com>
=> feat: add more print column like status

controllers/infra/drivers/aws/get_instance.go, controllers/infra/drivers/aws/get_volumes.go
1. add get volumes api
2. get volumes using aws api when using get_instance
Signed-off-by: ybyang <ybyang7@iflytek.com>
=> feat: add get volumes api when using get instnaces

pkg/buildah/login.go
sealos login hub.sealos.uo by kubeconfig.
=> feat. sealos login hub.sealos.io by kubeconfig.

cmd/sealos/cmd/run.go, pkg/constants/contants.go, pkg/runtime/kubeadm.go, pkg/runtime/runtime_getter.go
https://github.com/labring/sealos/issues/2059
=> feature(main): Support configuration file custom vip

pkg/ssh/connect.go, pkg/ssh/scp.go, pkg/ssh/ssh.go, pkg/ssh/sshcmd.go
Support reconnect sftp client to prevent from disrupting the entire run process. default max retry times is 5.
=> fix: reconnect when specified error occur with sftp connection

pkg/ssh/scp.go
=> fix: replace new line sep

pkg/buildah/build.go
=> feature(main): add delete build file scan

pkg/apply/processor/install.go
=> fix: #2232 force override when the prompted answer is yes

pkg/apply/processor/create.go, pkg/apply/processor/install.go, pkg/apply/processor/interface.go, pkg/constants/contants.go, pkg/env/env.go, pkg/runtime/runtime_getter.go, pkg/types/v1beta1/cluster.go
feature(main): support sys env SEALOS_SYS_KUBE_VERSION,SEALOS_SYS_VERSION_MAJOR,SEALOS_SYS_VERSION_MINOR
=> feature(main): support sys env 

docs/4.0/docs/build-cloud-image/build-directory-structure.md
=> feature(main): add build-in env docs

pkg/buildah/build.go, pkg/buildah/common.go, pkg/buildah/from.go, pkg/buildah/interface.go, pkg/buildah/login.go, pkg/buildah/manifest.go, pkg/buildah/pull.go, pkg/buildah/push.go
fix #2226 . set value of `--tls-verify` option default to false.
=> fix: set tls-verify option default to false

controllers/imagehub/api/v1/datapack_types.go, controllers/imagehub/api/v1/image_types.go, controllers/imagehub/config/crd/bases/imagehub.sealos.io_images.yaml, controllers/imagehub/controllers/data_helper.go, controllers/imagehub/controllers/image_controller.go, controllers/imagehub/controllers/organization_controller.go, controllers/imagehub/controllers/repository_controller.go
fix review problem. 
delete useless image detail info.
=> Fix: image hub delete useless image detail info.

.github/workflows/release.yml, .goreleaser.yml
=> ci: adjust files to be checksumed

CHANGELOG/CHANGELOG-4.1.4-rc2.md, scripts/changelog_tpl.sh
=> feature(main): fix changelogs

pkg/env/env.go
=> feature(main): delete warn

controllers/imagehub/api/v1/common_types.go, controllers/imagehub/api/v1/image_webhook.go, controllers/imagehub/deploy/rbac/rbac.yaml
add pass logic for kubernetes-admin.
fix delete logic error.
=> feat. imagehub webhook fix.

go.mod, pkg/apply/processor/scale.go
=> fix: skip handling app type image while scaling cluster

desktop/frontend/src/applications/infra/infra_share.ts, desktop/frontend/src/mock/infra.ts
=> modify the scp yaml field

pkg/buildah/build.go, pkg/buildah/common.go, pkg/buildah/create.go, pkg/buildah/from.go, pkg/buildah/pull.go
=> fix: only set default --platform flag when it's not changed

pkg/apply/applydrivers/apply_drivers_default.go
=> feature(main): change apply logic

CHANGELOG/CHANGELOG-4.1.4-rc3.md
=> feature(main): add rc3 change_log

pkg/apply/processor/create.go, pkg/apply/processor/install.go, pkg/buildah/create.go, pkg/buildah/interface.go
=> refactor buildah interface, arguments as flagsetters

cmd/sealos/cmd/cert.go, pkg/apply/applydrivers/apply_drivers_default.go, pkg/apply/processor/scale.go, pkg/clusterfile/clusterfile.go, pkg/clusterfile/pre_process.go, pkg/clusterfile/util.go, pkg/constants/data.go, pkg/runtime/init.go, pkg/runtime/kubeadm.go, pkg/runtime/runtime.go, pkg/runtime/update_cert.go, staging/src/github.com/labring/image-cri-shim/pkg/server/server.go, staging/src/github.com/labring/image-cri-shim/pkg/server/utils.go, staging/src/github.com/labring/image-cri-shim/pkg/shim/shim.go, test/testhelper/settings/common.go
Close  https://github.com/labring/sealos/issues/2106
=> feature(main): add cert cmd for append certs

controllers/infra/api/v1/infra_types.go, controllers/infra/drivers/aws/get_instance.go
change type to volumn-type in queryPrice
=> fix:fix queryPrice error

controllers/infra/common/common.go, controllers/infra/config/samples/infra_v1_infra.yaml, controllers/infra/controllers/infra_controller.go, controllers/infra/drivers/aws/create_instance.go, controllers/infra/drivers/aws/create_volume.go, controllers/infra/drivers/aws/get_instance.go, controllers/infra/drivers/reconcile.go
Signed-off-by: xiaohan <962479661@qq.com>
=> fix: ensure consistency when crash & fix some bugs

pkg/pay/wechat_payment.go
error info
```
1.6717893358897371e+09  ERROR   get codeURL failed      {"controller": "payment", "controllerGroup": "user.sealos.io", "controllerKind": "Payment", "Payment": {"name":"b1694429-d3ff-44ef-9220-a373a403dd44","namespace":"ns-883a8663-f107-4ce9-b404-7a84413b7345"}, "namespace": "ns-883a8663-f107-4ce9-b404-7a84413b7345", "name": "b1694429-d3ff-44ef-9220-a373a403dd44", "reconcileID": "8b328312-af39-468f-b4df-8be173ab5b0b", "error": "call Prepay err:error http response:[StatusCode: 400 Code: \"PARAM_ERROR\"\nMessage: 输入源“/body/notify_url”映射到值字段“通知地址”字符串规则校验失败，字符串必须匹配正则表达式“^https?://([^\\s/?#\\[\\]\\@]+\\@)?([^\\s/?#\\@:]+)(?::\\d{2,5})?([^\\s?#\\[\\]]*)$”\nDetail:\n{\n  \"location\": \"body\",\n  \"value\": \"\"\n}\nHeader:\n - …
```
=> fix:payment add defaultcallbackURL

cmd/sealos/cmd/run.go, pkg/buildah/constants.go, pkg/buildah/interface.go, pkg/buildah/load.go, pkg/buildah/login.go, pkg/buildah/save.go
=> feature(main): change default archive is oci

controllers/imagehub/deploy/rbac/rbac.yaml
=> update datapacks rbac.

deploy/registry/README.md, deploy/registry/install_base_server.md
=> Update registry doc

cmd/sealos/cmd/root.go, cmd/sealos/cmd/status.go, docs/4.0/docs/getting-started/kuberentes-support.md, pkg/checker/cluster_checker.go, pkg/checker/cluster_checker_test.go, pkg/checker/constants.go, pkg/checker/cri_shim_checker.go, pkg/checker/crictl_checker.go, pkg/checker/initsystem_check.go, pkg/checker/node_checker.go, pkg/checker/pod_checker.go, pkg/checker/registry_checker.go, pkg/checker/svc_checker.go, pkg/client-go/kubernetes/healthy.go, pkg/runtime/defaults/default_kubeadm_config.go, pkg/runtime/defaults/v125/default_kubeadm_config.go, pkg/utils/initsystem/initsystem.go, pkg/utils/initsystem/initsystem_unix.go, pkg/utils/initsystem/initsystem_windows.go
=> feature(main): add status cmd for post check

pkg/runtime/kubeadm.go, pkg/runtime/reset.go
=> feature(main): fix etcd config

CHANGELOG/CHANGELOG-4.1.4-rc4.md, CHANGELOG/README.md
=> feature(main): add changelog

fork/github.com/heroku/docker-registry-client/registry/errortransport.go, fork/github.com/heroku/docker-registry-client/registry/tokentransport.go, pkg/buildimage/chart.go, pkg/buildimage/manifests/manifests.go, pkg/registry/distributionpkg/client/transport/http_reader.go
=> feature(main): fix ci error

docs/4.0/docs/getting-started/customize-cluster.md, docs/4.0/i18n/zh-Hans/getting-started/customize-cluster.md
close https://github.com/labring/sealos/issues/2137
=> feature(main): change calico docs

docs/4.0/docs/examples/sealctl-registry.md, fork/github.com/heroku/docker-registry-client/registry/json.go, fork/github.com/heroku/docker-registry-client/registry/manifest.go, fork/github.com/heroku/docker-registry-client/registry/repositories.go, pkg/registry/cmd/flags.go, pkg/registry/cmd/list.go, pkg/registry/cmd/prune.go, pkg/registry/cmd/registry.go, pkg/registry/cmd/rmi.go, pkg/registry/cmd/save.go, pkg/registry/cmd/status.go, pkg/registry/filter.go, pkg/registry/filter_test.go, pkg/registry/interface.go, pkg/registry/list.go, pkg/registry/list_test.go, pkg/registry/save.go, pkg/registry/status.go
close https://github.com/labring/sealos/issues/1878
=> feature(main): fix registry find manifest logic

cmd/sealos/cmd/cert.go, pkg/apply/applydrivers/apply_drivers_default.go, pkg/apply/processor/interface.go
=> feature(main): add cert for old version

controllers/imagehub/api/v1/datapack_types.go, controllers/imagehub/config/crd/bases/imagehub.sealos.io_datapacks.yaml, controllers/imagehub/controllers/repository_controller.go, controllers/imagehub/deploy/manifests/deploy.yaml
add size to imagegrid. fix repository reconcile.
=> add size to imagegrid. fix repository reconcile.

desktop/frontend/src/components/start_menu/charge_button.tsx, docs/4.0/docs/build-cloud-image/build-template-intro.md, docs/4.0/i18n/zh-Hans/build-cloud-image/build-template-intro.md
=> Docs: add build template docs

desktop/frontend/src/components/app_window/index.tsx, desktop/frontend/src/components/taskbar/index.tsx, desktop/frontend/src/stores/app.ts
=> Fixed the application window switch problem

desktop/frontend/src/mock/hub/terminal.ts
=> Update terminal image tag

docs/4.0/docs/build-cloud-image/build-cloudImage-with-binary-file.md, docs/4.0/docs/build-cloud-image/build-cloudImage-with-helm-charts.md, docs/4.0/docs/build-cloud-image/build-with-sealos-exec-and-scp.md
=> update build cloud image docs

desktop/frontend/src/components/app_window/index.tsx, desktop/frontend/src/stores/app.ts, desktop/frontend/src/styles/globals.scss
=> Fixed Firefox scrollbar & switch app problem

controllers/infra/controllers/infra_controller.go, controllers/infra/drivers/aws/create_instance.go, controllers/infra/drivers/aws/get_instance.go, controllers/infra/drivers/aws/stop_instance.go, controllers/infra/drivers/reconcile.go, controllers/infra/go.mod, go.work.sum, pkg/env/test/shim/shim.yaml, pkg/utils/controller/retry_create_or_update.go
=> add ssh-privatekey secret to prevent ssh problems

pkg/registry/distributionpkg/client/transport/http_reader.go
=> Fix ci semgrep

pkg/apply/run.go
=> bugfix: 'sealos run' cannot scale cluster

pkg/apply/applydrivers/apply_drivers_default.go, pkg/apply/run.go
```
root@lmaster:~# sealos run docker.io/labring/kustomize:v4.5.6
Error: master ip(s) must specified
master ip(s) must specified
```
such errors will happen
=> bugfix: sealos run error 

docs/4.0/docs/cloud/Intro.md, docs/4.0/docs/cloud/apps/scp.md, docs/4.0/docs/cloud/design/imagehub.md, docs/4.0/docs/cloud/getting-started/index.md
=> New Cloud doc location.

docs/4.0/docs/examples/how-to-upgrade-cluster.md
=> Fix doc typo.

controllers/user/config/default/manager_auth_proxy_patch.yaml, controllers/user/controllers/helper/kubeconfig.go, controllers/user/deploy/manifests/config/default/manager_auth_proxy_patch.yaml
=> bugfix: set kubeconfig server 

controllers/infra/drivers/aws/create_instance.go, controllers/infra/drivers/aws/create_instance_test.go, controllers/terminal/README_zh.md
=> add clean all aws key pairs

cmd/sealos/cmd/gen.go, pkg/apply/apply.go, pkg/apply/apply_test.go, pkg/apply/gen.go, pkg/apply/gen_test.go, pkg/apply/reset.go, pkg/apply/run.go, pkg/apply/run_test.go
=> refactor: rename apply pkg

pkg/apply/processor/create.go, pkg/apply/processor/interface.go, pkg/apply/processor/scale.go
close #2389 
cluster status might be overwriten by inappropriate usage
=> bugfix: add node failure

pkg/checker/cluster_checker.go, pkg/checker/node_checker.go, pkg/checker/pod_checker.go, pkg/checker/svc_checker.go, pkg/runtime/runtime_getter.go, pkg/types/v1beta1/cluster_args.go
=> refactor: autoLoad apiServer ip and port

docs/4.0/i18n/zh-Hans/examples/pull-private-image.md
=> docs:pull private image tutorial in cloud

pkg/buildah/constants.go, pkg/buildah/interface.go
=> fix: export function FormatReferenceWithTransportName

cmd/sealos/cmd/gen.go, docs/4.0/docs/Development-Guidelines/buildah-module.md, pkg/apply/gen.go, pkg/apply/gen_test.go, pkg/apply/processor/interface.go, pkg/buildah/common.go, pkg/buildah/merge.go, pkg/runtime/kubeadm.go
=> docs(main): fix gen before pull image and inspect it

cmd/sealos/cmd/root.go, pkg/apply/processor/interface.go
=> fix: inspect image in gen command

desktop/frontend/src/applications/app_store/app_store_common.ts, desktop/frontend/src/applications/app_store/components/imagehub_loading.tsx, desktop/frontend/src/applications/app_store/detail_page.tsx
=> add image detail skeleton

docs/4.0/i18n/zh-Hans/cloud/apps/postgres.md
https://github.com/cdjianghan/sealos/blob/pgsqlReadme/docs/4.0/docs/cloud/apps/postgres.md
https://github.com/cdjianghan/sealos/blob/pgsqlReadme/docs/4.0/i18n/zh-Hans/cloud/apps/
**this two place can show pic**
=> fix pg doc img bug

pkg/buildah/common.go, pkg/buildah/inspect.go, pkg/buildah/interface.go
=> feat: apply feature #2405 on sealos inspect command

test/testpg/pgstresstest.go
=> write a pgsql Stress Test in /test

desktop/frontend/src/applications/infra/add_page.tsx, desktop/frontend/src/applications/infra/infra_share.ts, desktop/frontend/src/mock/infra.ts
=> sealos cloud provider version upgraded

README.md
=> update sealos version to 4.1.4

desktop/frontend/src/applications/infra/add_page.tsx, desktop/frontend/src/applications/infra/infra_share.ts, desktop/frontend/src/applications/pgsql/add_page.module.scss, desktop/frontend/src/applications/pgsql/add_page.tsx, desktop/frontend/src/applications/pgsql/components/controlled_fluent.module.scss, desktop/frontend/src/applications/pgsql/components/controlled_fluent.tsx, desktop/frontend/src/applications/pgsql/pgsql_common.ts, desktop/frontend/src/components/markdown/index.tsx, desktop/frontend/src/styles/globals.scss
=> pgsql form validation

desktop/frontend/src/components/app_window/help_docs.tsx, desktop/frontend/src/components/app_window/index.tsx, desktop/frontend/src/mock/installedApps.ts, desktop/frontend/src/stores/app.ts
=> app header add document link

docs/4.0/docs/cloud/examples/use_cname_for_custom_host.md, docs/4.0/i18n/zh-Hans/cloud/examples/use_cname_for_custom_host.md
=> Add cname doc

controllers/infra/controllers/infra_controller.go, controllers/infra/drivers/aws/create_instance.go, controllers/infra/drivers/aws/get_instance.go
=> update userData to support multiple AMIs

desktop/frontend/package.json, desktop/frontend/pnpm-lock.yaml, desktop/frontend/src/applications/app_store/app_store_common.scss, desktop/frontend/src/applications/app_store/app_store_common.ts, desktop/frontend/src/applications/app_store/components/pgination.module.scss, desktop/frontend/src/applications/app_store/components/pgination.tsx, desktop/frontend/src/applications/app_store/detail_page.tsx, desktop/frontend/src/applications/app_store/index.tsx, desktop/frontend/src/applications/app_store/store_page.tsx, desktop/frontend/src/applications/infra/add_page.tsx, desktop/frontend/src/applications/infra/detail_page.tsx, desktop/frontend/src/applications/infra/infra_share.ts, desktop/frontend/src/components/iconfont/index.tsx, desktop/frontend/src/mock/infra.ts, desktop/frontend/src/mock/installedApps.ts, desktop/frontend/src/pages/api/image_hub/get_list.ts, desktop/frontend/src/services/backend/kubernetes.ts
1. image hub list paging
2. sealos cloud provider detail version
3. change sealos document link
=> image hub list paging & pagination component

controllers/user/testdata/account/README.md, controllers/user/testdata/account/recharge.go
=> feat: add account recharge way

README.md
=> Add sealos cloud docs link in readme

docs/4.0/docs/Development-Guidelines/buildah-module.md, pkg/apply/processor/install.go, pkg/apply/processor/interface.go, pkg/buildah/inspect.go, pkg/buildah/interface.go, pkg/buildah/interface_test.go, pkg/buildah/merge.go
=> fix(main): fix inspect local image

.github/workflows/ci.yml, .github/workflows/controllers.yml, .github/workflows/services.yml, .github/workflows/webhooks.yml
=> fix(main): fix ci for buildx

docs/4.0/docs/getting-started/kuberentes-support.md
=> docs(main): fix 404 for changelog addr

desktop/frontend/src/components/app_window/index.tsx, desktop/frontend/src/components/desktop_content/index.tsx, desktop/frontend/src/mock/installedApps.ts, desktop/frontend/src/stores/app.ts
=> Fixed application drag boundaries

docs/4.0/docs/cloud/examples/use_cname_for_custom_host.md, docs/4.0/i18n/zh-Hans/cloud/examples/use_cname_for_custom_host.md, proposal/design/en/imagehub.md, proposal/design/en/imagehub/datapack.md, proposal/design/zh/imagehub/datapack设计.md, proposal/design/zh/imagehub设计.md
=> Update cloud docs.

docs/4.0/docs/getting-started/installation.md, docs/4.0/i18n/zh-Hans/Intro.md, docs/4.0/i18n/zh-Hans/getting-started/installation.md
Signed-off-by: 中弈 <fanux@sealos.io>
=> update docs to v4.1.4
